from pathlib import Path
root=Path(__file__).parent.parent
h=(root/'outputs/tests-v4.cjs').read_text().split('const checks=`')[0]
checks=r'''
{
const results=[];function check(b,m){if(!b)throw Error(m);results.push(m)}const near=(a,b)=>Math.abs(a-b)<1e-8*Math.max(1,Math.abs(a),Math.abs(b)),copy=x=>JSON.parse(JSON.stringify(x));toast=()=>{};saveState=()=>{};render=()=>{};closeModal=()=>{};updateNotificationBadge=()=>{};
function fresh(at=Date.UTC(2026,9,10,10)){setWall(at);state=migrateState(freshState());state.videos=[];state.ecosystem.shortsSeeded=true;for(const c of state.channels)c.nextUploadAt=at+10000*DAY;return channelBy('me')}
function own(id='earn-long',type='video'){const v=makeNPCPublication(channelBy('me'),3,RealClock.now(),type);v.id=id;v.dateStatus='real';v.realCreatedAt=v.publishedAt;state.videos.push(v);initializeDistribution(v,channelBy('me'));initializeSocialVideo(v);return v}
function add(v,views=1000,watch=views*300,engaged=0,t=RealClock.now(),feed=engaged){v.views+=views;v.watchSeconds+=watch;if(isShort(v))v.shortStats.viewedExposures+=engaged;historyAdd(v,t,{views,watchSeconds:watch,viewedExposures:engaged,qualifiedFeedViews:feed});return v}
function tick(ms){setWall(RealClock.now()+ms);settleTime()}
function approve(){channelBy('me').subscribers=1200;channelBy('me').audienceProfile=createAudienceProfile(channelBy('me'),state);demographicProfile(channelBy('me'));check(applyEarning(),'Eligible channel can apply');check(state.earn.status==='pending'&&state.earn.reviewAt-state.earn.submittedAt===10*60e3,'Review delay uses ten real minutes');state.simulation.speed=0;tick(10*60e3);check(state.earn.status==='active','Deterministic virtual review approves fulfilled requirements')}
let c=fresh(),v=own(),short=own('earn-short','short');check(!earnEligible()&&!applyEarning(),'New channel cannot apply');const initial=copy(state);tick(HOUR);check(qualifiedTotals().hours>0&&qualifiedTotals().shorts>0,'Real engine events grow qualified long hours and engaged Feed views');check(qualifiedTotals().hours<v.watchSeconds/3600+.00001,'Shorts watch time is never added to long qualification');check(short.earning.qualification.reduce((s,r)=>s+r.engaged,0)<short.shortStats.viewedExposures,'Search and external Shorts exposures are excluded from Feed qualification');
c=fresh();v=own();short=own('short','short');const foreign=makeNPCPublication(state.channels[1],1,RealClock.now(),'video');state.videos.push(foreign);let p=savePlaylist({title:'Первая подборка',description:'Серии фильмов',visibility:'public'});check(p.createdAt===RealClock.now()&&p.videoIds.length===0,'Playlist starts empty with real dates');playlistInclude(p,v.id,true);playlistInclude(p,short.id,true);playlistInclude(p,foreign.id,true);playlistInclude(p,v.id,true);check(p.videoIds.length===3&&new Set(p.videoIds).size===3,'Own video, Shorts and foreign video can be included without duplicates');check(foreign.channelId!=='me'&&p.videoIds.every(id=>typeof id==='string'),'Playlist stores references and never changes video ownership');check(playlistCover(p)===thumbnail(v),'Default cover uses the first available video');movePlaylistEntry(p,short.id,-1);check(p.videoIds[0]===short.id&&playlistCover(p)===thumbnail(short),'Button reordering changes sequence and default cover');const id=p.id,created=p.createdAt;setWall(RealClock.now()+1000);savePlaylist({id,title:'Новое название',description:'Новое описание',visibility:'unlisted',cover:'data:image/png;base64,dGVzdA=='});check(p.id===id&&p.createdAt===created&&p.title==='Новое название'&&p.description==='Новое описание'&&p.updatedAt===RealClock.now(),'Editing playlist preserves identity and creation date');check(playlistCover(p)===p.cover,'Custom cover overrides first video');check(playlistPage(p).includes('Воспроизвести все')&&playlistPage(p).includes('Новое описание'),'Playlist page renders metadata and play-all');foreign.visibility='private';check(playlistVideos(p).length===2&&playlistPage(p).includes('недоступна'),'Foreign private publication is skipped gracefully');p.videoIds.push('missing-video');check(playlistVideos(p).length===2&&playlistPage(p).includes('2 недоступных'),'Deleted references remain editable but cannot play');
location.hash='#/shorts/'+short.id+'?playlist='+p.id;check(playlistContext().index===0&&shortsPage(short.id).includes('playlist-controls')&&shortsCatalog.length===1,'Mixed playlist opens isolated existing Shorts player');state.preferences.playlistAuto=false;check(!playlistStep(1,true),'Automatic advance is disabled by default');state.preferences.playlistAuto=true;check(playlistStep(1,true)&&location.hash.includes(v.id),'Enabled automatic advance follows mixed-format order');location.hash='#/watch/'+v.id+'?playlist='+p.id;check(!playlistStep(1,true),'Playlist stops at end without repeat');state.preferences.playlistRepeat=true;check(playlistStep(1,true)&&location.hash.includes(short.id),'Repeat wraps to first available publication');location.hash='#/watch/'+v.id+'?playlist='+p.id;check(watchPage(v).includes('playlist-repeat'),'Normal player exposes repeat and automatic controls');check(playlistControls().includes('2 / 2'),'Position excludes unavailable entries');state.preferences.playlistRepeat=false;playlistInclude(p,short.id,false);check(!p.videoIds.includes(short.id)&&videoBy(short.id)===short,'Removing an entry keeps its publication');const hiddenNPC={...copy(p),id:'hidden-npc-playlist',channelId:foreign.channelId,title:'Hidden NPC collection',visibility:'unlisted'};state.playlists.push(hiddenNPC);check(!playlistLibrary().includes(hiddenNPC.title)&&playlistPage(hiddenNPC).includes(hiddenNPC.title),'Unlisted foreign playlists are reachable by direct link but absent from discovery');hiddenNPC.visibility='private';check(!playlistAccessible(hiddenNPC),'Another channel’s private playlist is unavailable');const count=state.videos.length;check(deletePlaylist(p.id)&&state.videos.length===count,'Deleting playlist keeps every video');let rejected=false;try{savePlaylist({title:'',visibility:'public'})}catch{rejected=true}check(rejected,'Empty playlist names are rejected');
// No retroactive revenue, separate formulas and per-video controls.
c=fresh();v=own();short=own('short','short');add(v,100000,4000*3600);check(revenueTotal().income===0&&revenueTotal().views===0,'One hundred thousand pre-program views earn no retroactive revenue');approve();const active=state.earn.activeAt;check(active===RealClock.now()&&state.earn.activationViews[v.id].views===v.views,'Activation records its timestamp and view counter baseline');add(v,20000,6000000);add(short,20000,400000,18000,RealClock.now(),17000);let longR=revenueTotal(0,v.id),shortR=revenueTotal(0,short.id);check(longR.views===20000&&longR.playbacks>0&&longR.playbacks<longR.views,'Only new long views enter the model and some have no ads');check(longR.adImpressions>=longR.playbacks&&near(longR.gross,longR.adImpressions/1000*(longR.gross/longR.adImpressions*1000)),'Ad impressions and gross CPM are mathematically consistent');check(near(longR.income,longR.net*.55)&&longR.gross===longR.net,'Long creator share is applied exactly once');check(shortR.engaged===17000&&shortR.playbacks===0&&shortR.adImpressions===0&&shortR.gross===0,'Shorts use qualified Feed engaged views and no per-video ad impressions');check(near(shortR.income,shortR.allocation*.45)&&shortR.income>0,'Shorts pay forty-five percent of allocated pool exactly once');check(shortR.income/shortR.views<longR.income/longR.views,'Different models yield lower effective Shorts RPM in this scenario');check(near(revenueTotal().income,longR.income+shortR.income),'Channel income equals the sum of formats and publications');check(near(revenueSeries(28).reduce((s,r)=>s+r.income,0),revenueTotal(28).income),'Daily graph sum equals selected-period channel income');check(near(revenueSeries(28,v.id).reduce((s,r)=>s+r.income,0),longR.income),'Per-video daily graph equals individual income');
const before=longR.income;setVideoEarning(v,false);add(v,10000,3000000);check(revenueTotal(0,v.id).income===before&&revenueTotal(0,v.id).views===30000,'Off consumes new views with zero income and includes them in RPM denominator');setVideoEarning(v,true);add(v,10000,3000000);check(revenueTotal(0,v.id).income>before&&revenueTotal(0,v.id).views===40000,'Re-enabling pays only future new views');const once=revenueTotal().income;historyAdd(v,RealClock.now(),{views:10000,watchSeconds:3000000});check(revenueTotal().income===once,'Repeated journal invocation cannot credit counters a second time');setVideoEarning(short,false);const shortBefore=revenueTotal(0,short.id).income;add(short,1000,10000,900);check(revenueTotal(0,short.id).income===shortBefore,'Shorts Feed participation can be disabled without erasing income');setVideoEarning(short,true);add(short,1000,10000,900);check(revenueTotal(0,short.id).income>shortBefore,'Shorts Feed participation resumes on new engaged views');
v.visibility='private';const qBefore=qualifiedTotals().hours,privateBefore=revenueTotal(0,v.id).income;add(v,1000,300000);check(revenueTotal(0,v.id).income===privateBefore&&qualifiedTotals().hours===qBefore,'Private new views earn no income or qualified watch time');v.visibility='unlisted';add(v,1000,300000);check(revenueTotal(0,v.id).income===privateBefore,'Unlisted new views do not earn income');v.visibility='public';v.title='Обзор фильма ужасов';check(suitability(v).status==='eligible','Genre alone does not invent advertiser violations');v.contentFacts='Натуралистичное насилие показано подробно';check(suitability(v).status==='limited','Explicit supplied violent metadata limits advertising');v.contentFacts='Инструкция по изготовлению бомбы';check(suitability(v).status==='off','Clearly dangerous instruction metadata blocks advertising');v.contentFacts='';check(suitability(v).status==='eligible','Insufficient metadata cannot invent violations');check(videoEarnPanel(short).includes('CPM отдельного Shorts не применяется'),'Shorts analytics explain that individual ad CPM is unavailable');check(earnPage().includes('Виртуальная партнёрская программа'),'Studio monetization UI renders a real interactive program');
const saved=copy(state),savedIncome=revenueTotal().income;state=validateImport(copy(saved));settleTime();check(revenueTotal().income===savedIncome,'Import and replay with no new interval cannot duplicate money');state=unpackState(packState(state));state=migrateState(state);check(revenueTotal().income===savedIncome,'Compact storage roundtrip retains all monetary precision');state.simulation.speed=5;tick(HOUR);const offline=revenueTotal().income;check(offline>savedIncome,'Existing offline simulation produces income through actual view events');settleTime();check(revenueTotal().income===offline,'An offline interval cannot produce duplicate income');const postViews=v.views;state.simulation.speed=0;tick(DAY);check(revenueTotal().income===offline&&v.views===postViews,'Pause consumes real time without views or money');state.simulation.speed=20;settleTime();check(revenueTotal().income===offline,'Resuming never monetizes paused time');
// A one-Short repeat nests a replay event before the initial engaged-view journal flush.
const one=savePlaylist({title:'One Short',videoIds:[short.id]});location.hash='#/shorts/'+short.id+'?playlist='+one.id;state.preferences.playlistAuto=true;state.preferences.playlistRepeat=true;shortPlayback={id:short.id,time:short.duration,elapsed:short.duration,playing:false,viewed:true,lastTick:0,loop:0};const beforeRepeat=revenueTotal(0,short.id);short.views++;short.shortStats.viewedExposures++;playlistEnded(short.id);historyAdd(short,RealClock.now(),{views:1,viewedExposures:1,qualifiedFeedViews:1});const afterRepeat=revenueTotal(0,short.id);check(afterRepeat.views-beforeRepeat.views===2&&afterRepeat.engaged-beforeRepeat.engaged===1,'Single-Short repeat counts replay and first view separately without swallowing engaged revenue');location.hash='#/studio/earn';
// Separate country demand, duration and finite creator-pool allocation.
c=fresh();v=own();short=own('short','short');add(v,50000,4000*3600);approve();const splitBase=copy(state);add(short,10000,100000,9000);const single=copy(revenueTotal(0,short.id));state=copy(splitBase);short=videoBy('short');v=videoBy('earn-long');for(let i=0;i<10;i++)add(short,1000,10000,900);check(near(single.income,revenueTotal(0,short.id).income)&&near(single.allocation,revenueTotal(0,short.id).allocation),'Splitting the same Shorts engaged-view increment preserves allocation and creator income');const baseShort=revenueTotal(0,short.id).allocation;add(short,1e12,1e12,1e12);const capped=revenueTotal(0,short.id).allocation,maxPool=EARN_CONFIG.shortPool.reduce((a,b)=>a+b)*seasonDemand(RealClock.now());check(capped>baseShort&&capped<maxPool,'Very large Shorts exposure cannot allocate more than the available monthly pool');const firstHuge=capped-baseShort;add(short,1e12,1e12,1e12);check(revenueTotal(0,short.id).allocation-capped<firstHuge,'A finite pool gives diminishing incremental allocation as the channel share grows');
const brief=own('brief'),film=own('film');brief.duration=60;film.duration=1200;film.seed=brief.seed;film.params=copy(brief.params);add(brief,10000,100000);add(film,10000,100000);check(revenueTotal(0,film.id).adImpressions>revenueTotal(0,brief.id).adImpressions&&revenueTotal(0,film.id).income>revenueTotal(0,brief.id).income,'Longer eligible videos can receive additional ad impressions and different income');const geoBase=copy(state);channelBy('me').audienceProfile.demographics.countries=[0,0,0,0,1,0];const high=own('high-geo');add(high,10000,100000);const highIncome=revenueTotal(0,high.id).income;state=copy(geoBase);channelBy('me').audienceProfile.demographics.countries=[1,0,0,0,0,0];const low=own('low-geo');add(low,10000,100000);check(highIncome>revenueTotal(0,low.id).income,'Geographic composition affects fictional ad demand and CPM');
// Real review deadline splits the same view engine interval.
c=fresh();v=own();add(v,50000,4000*3600);c.subscribers=1000;check(applyEarning(),'Offline-review test can apply');state.simulation.speed=20;const initialViews=v.views;tick(30*60e3);const post=revenueTotal(0,v.id);check(state.earn.activeAt===state.earn.reviewAt,'Offline approval activates at the processed real deadline');check(post.views>0&&post.views<v.views-initialViews,'Views before offline approval remain unpaid');check(state.earn.activeAt<=RealClock.now(),'Income activation never occurs in a future virtual day');
c=fresh();v=own();add(v,50000,4000*3600);c.subscribers=1000;applyEarning();c.subscribers=999;state.simulation.speed=0;tick(10*60e3);check(state.earn.status==='rejected'&&state.earn.reason.length>20&&revenueTotal().income===0,'Review deterministically rejects unmet conditions with a reason');
// Rolling eligibility boundaries use civil days, including DST timezones.
c=fresh();v=own();short=own('short','short');c.subscribers=1000;state.earn.since=RealClock.now()-400*DAY;add(v,10,4000*3600,0,calendarCutoff(365));check(qualifiedTotals().hours===4000,'Long hours at inclusive 365-day cutoff count');setWall(nextLocalDay(RealClock.now()));check(qualifiedTotals().hours===0,'Long hours expire exactly across the 365-day boundary');add(short,10000000,0,10000000,calendarCutoff(90));check(qualifiedTotals().shorts===10000000&&earnEligible(),'Qualified Shorts at inclusive 90-day cutoff satisfy alternative threshold');setWall(nextLocalDay(RealClock.now()));check(qualifiedTotals().shorts===0&&!earnEligible(),'Qualified Shorts expire across the 90-day boundary');
// Month finalization, payouts, deletion and bounded journals preserve every dollar.
c=fresh();v=own();short=own('short','short');add(v,100000,4000*3600);approve();add(v,1000000,300000000);add(short,1000000,30000000,900000);const earned=revenueTotal().income;check(earned>100&&state.earn.paidTotal===0&&availableBalance()===0,'Current estimated month cannot be paid even above the threshold');setWall(+new Date(2026,10,6,23));earnMaintenance();check(state.earn.paidTotal===0&&finalizedTotal()===0,'Previous month remains estimated before configured close day');setWall(+new Date(2026,10,7,0));earnMaintenance();check(near(finalizedTotal(),earned)&&state.earn.paidTotal>=100,'Closing completed month finalizes revenue and creates virtual payout');check(state.earn.payouts.length===1&&state.earn.payouts[0].kind==='simulated','Payout journal uses an explicit simulation type');const paid=state.earn.paidTotal;earnMaintenance();check(state.earn.paidTotal===paid&&state.earn.payouts.length===1,'Finalization and payouts are idempotent');check(availableBalance()>=0&&availableBalance()<.01,'Only fractional cents remain after a simulated payout');add(v,10000,3000000);check(state.earn.paidTotal===paid&&revenueTotal().income>earned,'Next current month starts estimated without paying it early');const cashBeforeDelete=revenueTotal().income;state.videos=state.videos.filter(x=>x.id!==short.id);earnMaintenance();check(revenueTotal().income===cashBeforeDelete,'Deleting a publication keeps previously earned money');check(qualifiedTotals().shorts===0,'Deleted Shorts cannot qualify the program');
for(let i=0;i<410;i++){setWall(nextLocalDay(RealClock.now()));add(v,100,30000);earnMaintenance()}const book=state.earn.books[v.id];check(book.days.length<=400&&v.earning.qualification.length<=366&&book.before.views>0,'Daily revenue and qualification journals are bounded without losing earlier totals');check(EARN_FIELDS.every(k=>near(book.totals[k],book.before[k]+book.days.reduce((s,r)=>s+r[k],0))),'Compaction conserves every revenue and advertising metric');check(near(revenueTotal().income,Object.values(state.earn.months).reduce((s,m)=>s+m.income,state.earn.finalizedArchive)),'Monthly accounting equals per-video and archived lifetime income');check(!state.earn.books[short.id]&&state.earn.archive.short.income>0,'Old deleted publication totals move into bounded format archive');check(near(revenueSeries(0).reduce((s,r)=>s+r.income,0),revenueTotal().income),'Lifetime monthly chart conserves all revenue after daily compaction');
check(near(revenueSeries(0,v.id).reduce((s,r)=>s+r.income,0),revenueTotal(0,v.id).income),'Individual lifetime chart conserves compacted revenue with an archive point');
// Migration and import integrity.
let good=copy(state);check(validateImport(copy(good)).earn.paidTotal===good.earn.paidTotal,'Valid full financial backup passes validation');for(const [name,mutate]of [['negative money',s=>s.earn.paidTotal=-1],['inconsistent totals',s=>s.earn.books[v.id].totals.income+=1],['duplicate payout',s=>s.earn.payouts.push(copy(s.earn.payouts[0]))],['unknown creator version',s=>s.creatorVersion=99],['forged balance',s=>s.earn.finalizedArchive+=100]]){const bad=copy(good);mutate(bad);let reject=false;try{validateImport(bad)}catch{reject=true}check(reject,'Import rejects '+name)}
c=fresh();v=own();p=savePlaylist({title:'Сохранённая серия',description:'Текст',visibility:'public',videoIds:[v.id]});good=copy(state);const keep=validateImport(copy(good));check(keep.playlists[0].title===p.title&&keep.playlists[0].videoIds[0]===v.id,'Playlist content and order survive export validation');let bad=copy(good);bad.playlists[0].videoIds.push(v.id);rejected=false;try{validateImport(bad)}catch{rejected=true}check(rejected,'Import rejects duplicate playlist entries');bad=copy(good);bad.playlists[0].cover='javascript:alert(1)';rejected=false;try{validateImport(bad)}catch{rejected=true}check(rejected,'Import rejects unsafe playlist covers');const old=copy(state);delete old.creatorVersion;delete old.playlists;delete old.earn;for(const video of old.videos)delete video.earning;old.videos[0].views=12345;old.videos[0].watchSeconds=54321;const migrated=validateImport(copy(old));check(migrated.videos[0].views===12345&&migrated.videos[0].watchSeconds===54321&&migrated.playlists.length===0,'V4 migration preserves old statistics and initializes empty collections');check(migrated.earn.status==='none'&&Object.keys(migrated.earn.books).length===0,'V4 migration cannot retroactively invent money');check(migrated.videos[0].earning.cursor.views===12345,'Migration consumes legacy view counters as a non-paying baseline');const stable=JSON.stringify(migrated.earn);migrateState(migrated);check(JSON.stringify(migrated.earn)===stable,'Creator migration is idempotent');
window.v5Results={passed:results.length,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone,results};
}
})();
'''
(root/'outputs/tests-v5.cjs').write_text(h+'const checks='+repr(checks).replace('\\n','\\n')+';\ntry{vm.runInContext(source+checks,context,{timeout:120000});console.log(JSON.stringify(context.window.v5Results,null,2))}catch(e){console.error(e);process.exitCode=1}\n')
