// YOUTRUBE 5.0 — references-only collections and event-based virtual accounting.
// All monetary rates below are fictional simulation parameters, never live market quotes.
const EARN_CONFIG={subscribers:1000,watchHours:4000,shortViews:10000000,reviewDelay:10*60e3,creatorLong:.55,creatorShort:.45,payoutThreshold:100,finalizeDay:7,qualificationDays:366,revenueDays:400,monthLimit:120,payoutLimit:120,playlistLimit:100,entriesLimit:500,countryCPM:[1.3,1.8,1.1,1.6,7.5,3.8],shortPool:[180000,50000,30000,45000,220000,300000],backgroundEngaged:[1.2e9,3e8,2e8,3e8,9e8,1.6e9]};
const EARN_FIELDS=['views','engaged','playbacks','adImpressions','gross','net','allocation','income'];
const earnZero=()=>Object.fromEntries(EARN_FIELDS.map(k=>[k,0]));
function earnMerge(a,b){for(const k of EARN_FIELDS)a[k]+=(b[k]||0);return a}
function money(n,precise=false){return '$'+Math.max(0,n).toLocaleString('en-US',{minimumFractionDigits:precise?4:2,maximumFractionDigits:precise?4:2})}
function monthKey(t){const d=new Date(t);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')}
function monthStart(key,offset=0,day=1){const [y,m]=key.split('-').map(Number);return +new Date(y,m-1+offset,day)}
function earnMonth(key){return state.earn.months[key]??={income:0,finalized:false,engaged:Array(6).fill(0)}}
function initializeEarningVideo(v,migrating=false){if(v.channelId!=='me')return;v.earning??={enabled:true,cursor:{views:migrating?v.views:0,watch:migrating?v.watchSeconds:0,engaged:migrating?(v.shortStats?.viewedExposures||0):0},qualification:[]};return v.earning}
function initializeCreatorState(s){if(s.creatorVersion===1)return s;const at=Math.min(RealClock.now(),s.simulation.lastSimulationTimestamp);s.playlists??=[];s.earn??={status:'none',since:at,submittedAt:0,reviewAt:0,activeAt:0,reason:'',books:{},months:{},archive:{video:earnZero(),short:earnZero()},finalizedArchive:0,paidTotal:0,payouts:[],payoutsArchive:0};s.preferences.playlistAuto??=false;s.preferences.playlistRepeat??=false;for(const v of s.videos)initializeEarningVideo(v,true);s.creatorVersion=1;return s}
const makeBeforeCreator=makeNPCPublication;makeNPCPublication=function(...args){const v=makeBeforeCreator(...args);initializeEarningVideo(v);return v};
const migrateBeforeCreator=migrateState;migrateState=function(s){migrateBeforeCreator(s);return initializeCreatorState(s)};
const freshBeforeCreator=freshState;freshState=function(){return initializeCreatorState(freshBeforeCreator())};
function qualifiedTotals(at=RealClock.now()){let watch=0,short=0;const longCut=calendarCutoff(365,at),shortCut=calendarCutoff(90,at);for(const v of mine()){if(v.visibility!=='public'||v.archived)continue;for(const row of initializeEarningVideo(v).qualification){if(row.at>at)continue;if(!isShort(v)&&row.at>=longCut)watch+=row.watch;if(isShort(v)&&row.at>=shortCut)short+=row.engaged}}return{subscribers:channelBy('me').subscribers,hours:watch/3600,shorts:short}}
function earnEligible(at=RealClock.now()){const q=qualifiedTotals(at);return q.subscribers>=EARN_CONFIG.subscribers&&(q.hours>=EARN_CONFIG.watchHours||q.shorts>=EARN_CONFIG.shortViews)}
function applyEarning(){settleTime();if(state.earn.status==='active'||state.earn.status==='pending'||!earnEligible())return false;Object.assign(state.earn,{status:'pending',submittedAt:RealClock.now(),reviewAt:RealClock.now()+EARN_CONFIG.reviewDelay,reason:''});saveState(true);return true}
function reviewEarning(at){const e=state.earn;if(e.status!=='pending'||at<e.reviewAt)return false;const ok=earnEligible(at);e.status=ok?'active':'rejected';e.reason=ok?'Условия виртуальной программы выполнены.':'За время проверки условия перестали выполняться. Проверьте открытый доступ публикаций и показатели, затем подайте заявку снова.';e.decidedAt=at;if(ok){e.activeAt=at;e.activationViews=Object.fromEntries(mine().map(v=>[v.id,{views:v.views,engaged:v.shortStats?.viewedExposures||0}]))}eventNotification('earn:decision:'+e.submittedAt,ok?'Виртуальная монетизация подключена. Доход начисляется только на новые подходящие просмотры.':e.reason,'studio/earn','earn',at);return true}
function suitability(v){const text=[v.title,v.description,v.contentFacts].filter(Boolean).join(' ').toLocaleLowerCase('ru');if(/(?:инструкция|пошагов[а-яёa-z]* руководство)\s+(?:по\s+)?(?:изготовлен[а-яёa-z]*\s+(?:бомб|взрывчат)|продаж[а-яёa-z]*\s+наркотик)/u.test(text))return{status:'off',factor:0,label:'Не монетизируется',reason:'В метаданных прямо заявлено опасное руководство.'};if(/\b(?:graphic violence|explicit sexual)\b|(?:натуралистич[а-яёa-z]*|шокирующ[а-яёa-z]*)\s+(?:насили|сцен[а-яёa-z]*\s+насилия)|(?:подробн[а-яёa-z]*|крупн[а-яёa-z]*)\s+(?:сцен[а-яёa-z]*\s+)?(?:кровопролити|жесток)/u.test(text))return{status:'limited',factor:.18,label:'Ограниченная монетизация',reason:'В метаданных явно описаны сцены, ограничивающие рекламный спрос.'};return{status:'eligible',factor:1,label:'Подходит для монетизации',reason:'В доступных метаданных не найдено явных ограничений. Изображение и звук не проверяются.'}}
function earningStatus(v){const s=suitability(v);if(state.earn.status!=='active')return{status:'off',label:'Программа ещё не подключена'};if(!initializeEarningVideo(v).enabled)return{status:'off',label:isShort(v)?'Участие в Shorts Feed выключено':'Монетизация выключена'};if(v.visibility!=='public'||v.archived)return{status:'off',label:'Нужен открытый доступ'};return s}
function setVideoEarning(v,enabled){if(!v||v.channelId!=='me'||state.earn.status!=='active')return false;settleTime();initializeEarningVideo(v).enabled=!!enabled;saveState(true);return true}
function revenueBook(v){if(!Object.hasOwn(state.earn.books,v.id))state.earn.books[v.id]={type:isShort(v)?'short':'video',title:v.title,totals:earnZero(),before:earnZero(),days:[]};return state.earn.books[v.id]}
function seasonDemand(at){const d=new Date(at);return [0.78,.83,.95,.96,1.00,.94,.88,.92,1.07,1.12,1.32,1.45][d.getMonth()]}
function nicheDemand(v){const base={Технологии:1.55,Обучение:1.35,Игры:.92,Развлечения:.9,Путешествия:1.12,Дизайн:1.3,Музыка:.85,Спорт:1.04,Подкасты:1.18,Новости:1.05}[v.category]||1;const finance=/финанс|инвестиц|экономик/.test((v.title+' '+v.description).toLowerCase())?1.24:1;return base*finance*(.88+seeded(v.seed,'ad-demand')*.24)}
function creditRevenue(v,at,views,engaged){const e=state.earn;if(e.status!=='active'||at<e.activeAt||views<=0)return;const delta=earnZero();delta.views=views;const status=earningStatus(v);if(status.factor>0){const countries=demographicProfile(channelBy('me')).countries,season=seasonDemand(at),month=earnMonth(monthKey(at));if(isShort(v)){delta.engaged=engaged*status.factor;const budgets=EARN_CONFIG.shortPool.map(x=>x*season);countries.forEach((share,i)=>{const old=month.engaged[i],add=delta.engaged*share,background=EARN_CONFIG.backgroundEngaged[i];delta.allocation+=budgets[i]*(background*add/((background+old)*(background+old+add)));month.engaged[i]+=add});delta.income=delta.allocation*EARN_CONFIG.creatorShort}else{const niche=nicheDemand(v),geo=countries.reduce((sum,w,i)=>sum+w*EARN_CONFIG.countryCPM[i],0),fill=clamp((.38+v.params.contentQuality*.22)*Math.sqrt(season*niche),.22,.86)*status.factor,midroll=v.duration>=480?Math.min(1.8,(v.duration-360)/900):0,nonSkip=.08+seeded(v.seed,'non-skip')*.14;delta.playbacks=views*fill;delta.adImpressions=delta.playbacks*(1+midroll+nonSkip);const cpm=geo*niche*season*(.92+nonSkip);delta.gross=delta.adImpressions/1000*cpm;delta.net=delta.gross;delta.income=delta.net*EARN_CONFIG.creatorLong}}
 const b=revenueBook(v);b.title=v.title;earnMerge(b.totals,delta);const day=localDay(at);let row=b.days.find(x=>x.at===day);if(!row){row={at:day,...earnZero()};b.days.push(row);b.days.sort((a,b)=>a.at-b.at)}earnMerge(row,delta);earnMonth(monthKey(at)).income+=delta.income;
 const cut=calendarCutoff(EARN_CONFIG.revenueDays,RealClock.now());while(b.days.length&&b.days[0].at<cut)earnMerge(b.before,b.days.shift());
}
// The cursor is a watermark of actual engine counters. Calling a journal hook twice cannot create money.
let creatorEventAt=-1,creatorEventDay=0,creatorWallStart=0,creatorWallEnd=0,creatorQualificationCut=0;
function creatorCalendar(t){const now=RealClock.now();if(now<creatorWallStart||now>=creatorWallEnd){creatorWallStart=localDay(now);creatorWallEnd=nextLocalDay(now);creatorQualificationCut=calendarCutoff(EARN_CONFIG.qualificationDays,now)}if(t!==creatorEventAt){creatorEventAt=t;creatorEventDay=localDay(t)}return{day:creatorEventDay,cut:creatorQualificationCut}}
const historyBeforeCreator=historyAdd;historyAdd=function(v,t,d){historyBeforeCreator(v,t,d);if(v.channelId!=='me'||!state.earn||!(d.views||d.watchSeconds||d.viewedExposures))return;const x=initializeEarningVideo(v),cursor=x.cursor,rawViews=Math.max(0,Math.min(d.views||0,v.views-cursor.views)),watch=Math.max(0,Math.min(d.watchSeconds||0,v.watchSeconds-cursor.watch)),engaged=Math.max(0,Math.min(d.qualifiedFeedViews||0,(v.shortStats?.viewedExposures||0)-cursor.engaged));if(d.views)cursor.views=Math.min(v.views,cursor.views+rawViews);if(d.watchSeconds)cursor.watch=Math.min(v.watchSeconds,cursor.watch+watch);if(d.viewedExposures)cursor.engaged=Math.max(cursor.engaged,v.shortStats?.viewedExposures||0);t=Math.min(t,RealClock.now());if(t<state.earn.since)return;
 const dates=creatorCalendar(t);if(v.visibility==='public'&&!v.archived&&(watch||engaged)){const at=dates.day;let row=x.qualification.at(-1);if(row?.at!==at)row=x.qualification.find(r=>r.at===at);if(!row){row={at,watch:0,engaged:0};x.qualification.push(row);x.qualification.sort((a,b)=>a.at-b.at)}row.watch+=isShort(v)?0:watch;row.engaged+=isShort(v)?engaged:0}while(x.qualification.length&&x.qualification[0].at<dates.cut)x.qualification.shift();creditRevenue(v,t,rawViews,engaged)};
// Review splits an existing engine step at the real deadline; pre-approval views stay unpaid.
const simulateBeforeCreator=simulateStep;simulateStep=function(from,to){const due=state.earn?.status==='pending'?state.earn.reviewAt:Infinity;if(due>from&&due<to){simulateBeforeCreator(from,due);reviewEarning(due);simulateBeforeCreator(due,to)}else{reviewEarning(from);simulateBeforeCreator(from,to)}};
function earnMaintenance(at=RealClock.now()){if(!state?.earn)return;reviewEarning(at);const e=state.earn;for(const [key,m]of Object.entries(e.months))if(!m.finalized&&at>=monthStart(key,1,EARN_CONFIG.finalizeDay)){m.finalized=true;m.finalizedAt=monthStart(key,1,EARN_CONFIG.finalizeDay)}const keys=Object.keys(e.months).sort();while(keys.length>EARN_CONFIG.monthLimit){const key=keys.shift(),m=e.months[key];if(!m.finalized)break;e.finalizedArchive+=m.income;delete e.months[key]}const balance=availableBalance();if(balance+1e-9>=EARN_CONFIG.payoutThreshold){const amount=Math.floor((balance+1e-9)*100)/100;e.paidTotal+=amount;e.payouts.unshift({id:uid('virtual'),at,amount,through:keys.filter(k=>e.months[k].finalized).at(-1)||'',kind:'simulated'});if(e.payouts.length>EARN_CONFIG.payoutLimit)e.payoutsArchive+=e.payouts.pop().amount;eventNotification('earn:payout:'+e.paidTotal,'Виртуальная выплата: '+money(amount)+'. Запись симулятора, без перевода денег.','studio/earn','earn',at)}const cut=calendarCutoff(EARN_CONFIG.revenueDays,at);for(const [id,b]of Object.entries(e.books)){while(b.days.length&&b.days[0].at<cut)earnMerge(b.before,b.days.shift());if(!videoBy(id)&&!b.days.length){earnMerge(e.archive[b.type],b.totals);delete e.books[id]}}}
function finalizedTotal(){return state.earn.finalizedArchive+Object.values(state.earn.months).filter(m=>m.finalized).reduce((s,m)=>s+m.income,0)}
function availableBalance(){return Math.max(0,finalizedTotal()-state.earn.paidTotal)}
const batchBeforeCreator=simulationBatch;simulationBatch=function*(ms){yield* batchBeforeCreator(ms);earnMaintenance()};
function revenueTotal(days=0,id=null,type=null){const out=earnZero(),cut=days?calendarCutoff(days):0;for(const [key,b]of Object.entries(state.earn.books)){if(id&&id!==key||type&&b.type!==type)continue;if(!days)earnMerge(out,b.totals);else for(const row of b.days)if(row.at>=cut&&row.at<=RealClock.now())earnMerge(out,row)}if(!days&&!id)for(const [format,a]of Object.entries(state.earn.archive))if(!type||type===format)earnMerge(out,a);return out}
function revenueSeries(days=28,id=null){const now=RealClock.now(),start=days?calendarCutoff(days):localDay(state.earn.activeAt||now),map=new Map();for(const [key,b]of Object.entries(state.earn.books)){if(id&&key!==id)continue;for(const row of b.days)if(row.at>=start&&row.at<=now)map.set(row.at,(map.get(row.at)||0)+row.income)}// Lifetime charts aggregate by month beyond the retained daily window, using the monthly accounting ledger.
 if(!days&&!id&&start<calendarCutoff(EARN_CONFIG.revenueDays)){const points=Object.entries(state.earn.months).sort().map(([k,m])=>({at:monthStart(k),income:m.income}));if(state.earn.finalizedArchive)points.unshift({at:start,income:state.earn.finalizedArchive,archive:true});return points.length?points:[{at:localDay(now),income:0}]}
 const points=[];for(let t=Math.max(start,calendarCutoff(EARN_CONFIG.revenueDays));t<=now;t=nextLocalDay(t))points.push({at:t,income:map.get(t)||0});if(!days&&id&&state.earn.books[id]?.before?.income)points.unshift({at:start,income:state.earn.books[id].before.income,archive:true});return points.length?points:[{at:localDay(now),income:0}]}
// Collections store IDs only: removing a collection never removes its publications.
function playlistBy(id){return state.playlists.find(p=>p.id===id)}
function playlistAccessible(p){return p&&(p.visibility!=='private'||p.channelId==='me')}
function playlistVideos(p){return p.videoIds.map(videoBy).filter(v=>v&&!v.archived&&(v.visibility!=='private'||v.channelId==='me'))}
function playlistCover(p){const first=playlistVideos(p)[0];return safeImage(p.cover)||(first?thumbnail(first):'')}
function playlistArt(p){const src=playlistCover(p);return `<div class="playlist-art">${src?`<img src="${esc(src)}" alt="Обложка плейлиста" loading="lazy">`:'<div class="playlist-empty-art">'+icon('content')+'</div>'}<span>${playlistVideos(p).length} видео</span></div>`}
function savePlaylist({id,title,description='',visibility='private',cover='',videoIds}={}){title=String(title||'').trim();if(!title||title.length>100||description.length>3000||!['public','unlisted','private'].includes(visibility))throw Error('Укажите название до 100 символов, описание до 3000 и видимость.');if(videoIds&&(!Array.isArray(videoIds)||videoIds.length>EARN_CONFIG.entriesLimit))throw Error('В плейлисте может быть до 500 публикаций.');let p=id?playlistBy(id):null;if(id&&(!p||p.channelId!=='me'))throw Error('Плейлист недоступен для редактирования.');if(!p){if(state.playlists.filter(p=>p.channelId==='me').length>=EARN_CONFIG.playlistLimit)throw Error('Можно создать до 100 плейлистов.');p={id:uid('playlist'),channelId:'me',createdAt:RealClock.now(),videoIds:[]};state.playlists.push(p)}if(videoIds){if(videoIds.length>EARN_CONFIG.entriesLimit)throw Error('В плейлисте может быть до 500 публикаций.');p.videoIds=[...new Set(videoIds.filter(id=>videoBy(id)))]}Object.assign(p,{title,description,visibility,cover,updatedAt:RealClock.now()});saveState(true);return p}
function playlistInclude(p,id,include){if(!p||p.channelId!=='me'||!videoBy(id))return false;const exists=p.videoIds.includes(id);if(include&&!exists){if(p.videoIds.length>=EARN_CONFIG.entriesLimit)throw Error('В плейлисте уже 500 публикаций.');p.videoIds.push(id)}else if(!include&&exists)p.videoIds=p.videoIds.filter(x=>x!==id);if(exists!==include){p.updatedAt=RealClock.now();saveState(true)}return true}
function movePlaylistEntry(p,id,direction){if(!p||p.channelId!=='me')return false;const i=p.videoIds.indexOf(id),j=i+direction;if(i<0||j<0||j>=p.videoIds.length)return false;[p.videoIds[i],p.videoIds[j]]=[p.videoIds[j],p.videoIds[i]];p.updatedAt=RealClock.now();saveState(true);return true}
function deletePlaylist(id){const p=playlistBy(id);if(p?.channelId!=='me')return false;state.playlists=state.playlists.filter(x=>x.id!==id);saveState(true);return true}
function playlistCards(list){return `<div class="playlist-grid">${list.map(p=>`<article class="playlist-card"><a href="#/playlist/${p.id}">${playlistArt(p)}<h3>${esc(p.title)}</h3></a><p class="tiny muted">${channelLabel(channelBy(p.channelId))} · ${visibilityLabel(p.visibility)}</p><a class="text-btn" href="#/playlist/${p.id}">Открыть плейлист</a></article>`).join('')}</div>`}
function playlistLibrary(){const list=state.playlists.filter(p=>p.channelId==='me'||p.visibility==='public');return `<div class="section-head"><h1>Плейлисты</h1>${btn('playlist-create','Создать плейлист','create','primary')}</div>${list.length?playlistCards(list):empty('Соберите свою подборку','Видео, Shorts, серии фильмов — всё в одном плейлисте.',btn('playlist-create','Создать плейлист','create','primary'))}`}
function playlistRoute(p,v){return videoRoute(v)+'?playlist='+encodeURIComponent(p.id)}
function playlistPage(p){if(!playlistAccessible(p))return unavailable('Плейлист недоступен');const vs=playlistVideos(p),own=p.channelId==='me',missing=p.videoIds.length-vs.length;return `<div class="playlist-layout"><aside class="playlist-summary">${playlistArt(p)}<h1>${esc(p.title)}</h1><a href="#/channel/${p.channelId}">${channelLabel(channelBy(p.channelId))}</a><p class="tiny muted">${vs.length} видео · ${formatDuration(vs.reduce((s,v)=>s+v.duration,0))}<br>${visibilityLabel(p.visibility)} · обновлён ${date(p.updatedAt)}</p><p>${esc(p.description||'Добавьте описание своей подборки.')}</p><div class="row wrap">${vs.length?`<a class="btn primary" href="#/${playlistRoute(p,vs[0])}">${icon('play')}Воспроизвести все</a>`:''}${own?btn('playlist-edit','Изменить','edit','outline',`data-id="${p.id}"`)+btn('playlist-delete','Удалить','delete','outline',`data-id="${p.id}"`):''}${btn('playlist-share','Ссылка','share','outline',`data-id="${p.id}"`)}</div>${missing?`<p class="earn-note">${missing} недоступных публикаций пропущено. Удалённые видео и чужие закрытые публикации не воспроизводятся.</p>`:''}${own?'<p class="earn-note">Меняйте порядок перетаскиванием или кнопками ↑ ↓. Удаление из подборки сохраняет само видео. Закрытые видео видны только их владельцу.</p>':''}</aside><section aria-label="Видео плейлиста">${p.videoIds.length?p.videoIds.map((id,i)=>{const v=vs.find(v=>v.id===id);return `<article class="playlist-row" data-playlist="${p.id}" data-entry="${esc(id)}" ${own?'draggable="true"':''}><span class="tiny muted">${i+1}</span>${v?`<a href="#/${playlistRoute(p,v)}"><img src="${esc(thumbnail(v))}" alt=""></a><div><a href="#/${playlistRoute(p,v)}"><h3>${esc(v.title)}</h3></a><p class="tiny muted">${channelLabel(channelBy(v.channelId))} · ${formatDuration(v.duration)}<br>${formatViews(v.views)}${isShort(v)?' · Shorts':''}${v.visibility!=='public'?' · '+visibilityLabel(v.visibility):''}</p></div>`:'<div class="muted">—</div><div class="muted tiny">Публикация недоступна</div>'}${own?`<div class="playlist-order">${btn('playlist-up','↑','','outline',`data-id="${p.id}" data-video="${esc(id)}" aria-label="Переместить выше" ${i===0?'disabled':''}`)}${btn('playlist-down','↓','','outline',`data-id="${p.id}" data-video="${esc(id)}" aria-label="Переместить ниже" ${i===p.videoIds.length-1?'disabled':''}`)}${ib('playlist-remove','Убрать из плейлиста','close',`data-id="${p.id}" data-video="${esc(id)}"`)}</div>`:''}</article>`}).join(''):empty('В плейлисте пока нет видео','Откройте меню любой публикации и выберите «Сохранить в плейлист».',link('home','Найти видео','home'))}</section></div>`}
let playlistDraft=null,playlistSaveVideo=null;
function playlistModal(p=null,videoId=null){playlistDraft={id:p?.id||null,cover:p?.cover||'',videoId,pending:0};openModal(p?'Изменить плейлист':'Создать плейлист',`<form id="playlist-form"><div class="field"><label for="playlist-title">Название</label><input class="input" id="playlist-title" name="title" maxlength="100" required value="${esc(p?.title||'')}"></div><div class="field"><label for="playlist-description">Описание</label><textarea class="input" id="playlist-description" name="description" maxlength="3000" rows="3">${esc(p?.description||'')}</textarea></div><div class="field"><label for="playlist-visibility">Видимость</label><select class="select" id="playlist-visibility" name="visibility">${['public','unlisted','private'].map(k=>`<option value="${k}"${(p?.visibility||'private')===k?' selected':''}>${visibilityLabel(k)}</option>`).join('')}</select><small>«По ссылке» не появляется во вкладке публичного канала. Данные доступны только в этом браузере и резервной копии.</small></div><div class="playlist-cover-preview" id="playlist-cover-preview">${p?playlistArt(p):'<div class="playlist-empty-art">Обложка первого видео</div>'}</div><div class="row wrap">${imageInput('playlist-cover','Загрузить обложку')}${btn('playlist-cover-reset','Из первого видео','','outline')}</div><p class="form-error" id="playlist-error" role="alert"></p><button class="btn primary" type="submit">Сохранить плейлист</button></form>`,'',true)}
function playlistSaveModal(id){if(!videoBy(id))return;playlistSaveVideo=id;closeDropdown();const list=state.playlists.filter(p=>p.channelId==='me');openModal('Сохранить в плейлист',`<p class="tiny muted">${esc(videoBy(id).title)} · можно выбрать несколько подборок</p><div>${list.length?list.map(p=>`<label class="playlist-check"><input type="checkbox" data-playlist-check="${p.id}" data-video="${id}" ${p.videoIds.includes(id)?'checked':''}><span>${esc(p.title)}<small class="muted" style="display:block">${visibilityLabel(p.visibility)} · ${p.videoIds.length} видео</small></span></label>`).join(''):'<p class="earn-note">Создайте первый плейлист.</p>'}</div>`,btn('playlist-create-for-video','Создать плейлист','create','outline',`data-video="${id}"`)+btn('close-modal','Готово','','primary'),true)}
const imageBeforeCreator=handleImage;handleImage=async function(input){if(input.name!=='playlist-cover')return imageBeforeCreator(input);const draft=playlistDraft;if(!draft||!input.files[0])return;draft.pending++;try{const image=await optimizeImage(input.files[0],'thumbnail'),ref=await ImageStore.put(image);if(playlistDraft!==draft||!$('#playlist-form'))return;draft.cover=ref;$('#playlist-cover-preview').innerHTML=`<img src="${image}" alt="Обложка плейлиста">`;toast('Обложка готова. Сохраните плейлист.')}catch(e){toast(e.message)}finally{draft.pending--}};
const channelBeforeCreator=channelPage;channelPage=function(c){let html=channelBeforeCreator(c);if(!c)return html;const end=html.indexOf('</div>',html.indexOf('<div class="tabs"'));const tab=`<button class="tab${channelTab==='playlists'?' active':''}" role="tab" aria-selected="${channelTab==='playlists'}" data-action="channel-tab" data-tab="playlists">Плейлисты</button>`;html=html.slice(0,end)+tab+html.slice(end);const body=html.indexOf('</div>',html.indexOf('<div class="tabs"'))+6;const own=c.id==='me',lists=state.playlists.filter(p=>p.channelId===c.id&&(own||p.visibility==='public'));if(channelTab==='playlists')html=html.slice(0,body)+`<div class="section-head"><h2>Плейлисты</h2>${own?btn('playlist-create','Создать плейлист','create','primary'):''}</div>`+(lists.length?playlistCards(lists):empty('Пока нет плейлистов','Соберите подборку из любимых публикаций.',own?btn('playlist-create','Создать плейлист','create','primary'):''));else if(channelTab==='home'){const visible=lists.filter(p=>p.visibility==='public');if(visible.length)html+=`<section><div class="section-head"><h2>Плейлисты</h2><button class="text-btn" data-action="channel-tab" data-tab="playlists">Смотреть все</button></div>${playlistCards(visible.slice(0,4))}</section>`}return html};
function playlistContext(){const id=readRoute().query.get('playlist'),p=playlistBy(id);if(!playlistAccessible(p))return null;const vs=playlistVideos(p),videoId=readRoute().path.split('/')[1],index=vs.findIndex(v=>v.id===videoId);return index<0?null:{p,vs,index}}
function playlistControls(short=false){const ctx=playlistContext();if(!ctx)return '';return `<div class="playlist-controls${short?' playlist-controls-short':''}" data-playlist-controls><div class="title"><a href="#/playlist/${ctx.p.id}"><strong>${esc(ctx.p.title)}</strong></a><p class="tiny muted">${ctx.index+1} / ${ctx.vs.length} · плейлист</p></div>${btn('playlist-prev','Предыдущее','back','outline')}${btn('playlist-next','Следующее','play','outline')}<label class="playlist-switch"><input type="checkbox" id="playlist-auto" ${state.preferences.playlistAuto?'checked':''}>Автопереход</label><label class="playlist-switch"><input type="checkbox" id="playlist-repeat" ${state.preferences.playlistRepeat?'checked':''}>Повторять</label></div>`}
function playlistStep(direction,automatic=false){const ctx=playlistContext();if(!ctx)return false;if(automatic&&!state.preferences.playlistAuto)return false;let index=ctx.index+direction;if(index<0||index>=ctx.vs.length){if(!state.preferences.playlistRepeat){if(!automatic)toast(direction>0?'Конец плейлиста':'Начало плейлиста');return false}index=(index+ctx.vs.length)%ctx.vs.length}const v=ctx.vs[index];if(v.id===ctx.vs[ctx.index].id){playlistEndKey='';if(isShort(v)){shortPlayback.time=0;shortPlayback.elapsed=0;shortPlayback.playing=true;shortPlayback.lastTick=performance.now();v.views++;v.shortStats.rewatches++;v.traffic[6]++;if(v.channelId==='me')historyAdd(v,RealClock.now(),{views:1,rewatches:1});recordLocalShort(v,1,1);syncChannelTotals();saveState();updateShortControls()}else{player.time=0;player.viewRecorded=false;player.playing=true;updatePlayer()}return true}location.hash='/'+playlistRoute(ctx.p,v);return true}
let playlistEndKey='';function playlistEnded(id){const ctx=playlistContext();if(!ctx||ctx.vs[ctx.index].id!==id)return;const key=location.hash+':'+id;if(playlistEndKey===key)return;playlistEndKey=key;if(!playlistStep(1,true)&&state.preferences.playlistAuto)toast('Плейлист завершён')}
const watchBeforeCreator=watchPage;watchPage=function(v){const html=watchBeforeCreator(v);return playlistContext()?html.replace('<h1 class="watch-title">',playlistControls()+'<h1 class="watch-title">'):html};
const shortsBeforeCreator=shortsPage;shortsPage=function(id){const ctx=playlistContext();if(!ctx)return shortsBeforeCreator(id);const v=videoBy(id);if(!v||!isShort(v))return unavailable('Shorts не найден');shortsCatalog=[id];shortsWindow={start:0,end:1};return playlistControls(true)+`<div class="shorts-feed" id="shorts-feed" tabindex="0" aria-label="Shorts из плейлиста">${shortFrame(v,0).replace('<span class="short-position">1 / 1</span>','<span class="short-position">'+(ctx.index+1)+' / '+ctx.vs.length+'</span>')}</div>`};
const shortStepBeforeCreator=shortStep;shortStep=function(direction){return playlistContext()?playlistStep(direction):shortStepBeforeCreator(direction)};
const routeBeforeCreator=routeChange;routeChange=function(){playlistEndKey='';routeBeforeCreator();const ctx=playlistContext();if(ctx&&readRoute().path.startsWith('watch/')){player.playing=true;updatePlayer()}};
actions['playlist-create']=()=>playlistModal();actions['playlist-create-for-video']=b=>playlistModal(null,b.dataset.video);actions['playlist-edit']=b=>{const p=playlistBy(b.dataset.id);if(p?.channelId==='me')playlistModal(p)};actions['save-playlist']=b=>playlistSaveModal(b.dataset.id);
actions['playlist-cover-reset']=()=>{if(!playlistDraft)return;playlistDraft.cover='';const v=playlistDraft.id?playlistVideos(playlistBy(playlistDraft.id))[0]:videoBy(playlistDraft.videoId);$('#playlist-cover-preview').innerHTML=v?`<img src="${esc(thumbnail(v))}" alt="Обложка первого видео">`:'<div class="playlist-empty-art">Обложка первого видео</div>'};
actions['playlist-up']=b=>{movePlaylistEntry(playlistBy(b.dataset.id),b.dataset.video,-1);renderContent()};actions['playlist-down']=b=>{movePlaylistEntry(playlistBy(b.dataset.id),b.dataset.video,1);renderContent()};actions['playlist-remove']=b=>{const p=playlistBy(b.dataset.id);if(p?.channelId!=='me')return;p.videoIds=p.videoIds.filter(id=>id!==b.dataset.video);p.updatedAt=RealClock.now();saveState(true);renderContent()};
actions['playlist-delete']=b=>confirmModal('Удалить плейлист?','Публикации останутся на платформе. Будет удалена только подборка.','playlist-delete-confirm','Удалить',`data-id="${b.dataset.id}"`);actions['playlist-delete-confirm']=b=>{if(deletePlaylist(b.dataset.id)){closeModal();location.hash='/playlists';render()}};actions['playlist-prev']=()=>playlistStep(-1);actions['playlist-next']=()=>playlistStep(1);
actions['playlist-share']=b=>{const p=playlistBy(b.dataset.id);if(!playlistAccessible(p))return;openModal('Ссылка на плейлист',`<p class="earn-note">${p.visibility==='private'?'Закрытый плейлист доступен только владельцу. ':''}Ссылка работает с данными этого браузера. Для переноса используйте резервную копию.</p><input class="input" id="share-link" readonly aria-label="Ссылка на плейлист" value="${esc(location.href.split('#')[0]+'#/playlist/'+p.id)}">`,btn('copy-link','Копировать','share','primary'),true)};
document.addEventListener('submit',e=>{if(e.target.id!=='playlist-form')return;e.preventDefault();try{const draft=playlistDraft;if(!draft)throw Error('Откройте редактор снова.');if(draft.pending)throw Error('Дождитесь обработки обложки.');const form=new FormData(e.target),p=savePlaylist({id:draft.id,title:String(form.get('title')),description:String(form.get('description')),visibility:String(form.get('visibility')),cover:draft.cover});if(draft.videoId)playlistInclude(p,draft.videoId,true);playlistDraft=null;closeModal();if(draft.videoId)playlistSaveModal(draft.videoId);else{location.hash='/playlist/'+p.id;render()}toast('Плейлист сохранён')}catch(error){$('#playlist-error').textContent=error.message}});
document.addEventListener('change',e=>{const el=e.target;if(el.dataset.playlistCheck){try{playlistInclude(playlistBy(el.dataset.playlistCheck),el.dataset.video,el.checked)}catch(error){el.checked=false;toast(error.message)}}if(el.id==='playlist-auto'||el.id==='playlist-repeat'){state.preferences[el.id==='playlist-auto'?'playlistAuto':'playlistRepeat']=el.checked;playlistEndKey='';saveState()}});
let playlistDrag=null;document.addEventListener('dragstart',e=>{const row=e.target.closest('.playlist-row[draggable=true]');if(!row||playlistBy(row.dataset.playlist)?.channelId!=='me')return;playlistDrag={playlist:row.dataset.playlist,id:row.dataset.entry};e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',row.dataset.entry)});document.addEventListener('dragover',e=>{const row=e.target.closest('.playlist-row');if(playlistDrag&&row?.dataset.playlist===playlistDrag.playlist){e.preventDefault();row.classList.add('drag-over')}});document.addEventListener('dragleave',e=>e.target.closest('.playlist-row')?.classList.remove('drag-over'));document.addEventListener('dragend',()=>{playlistDrag=null;$$('.drag-over').forEach(e=>e.classList.remove('drag-over'))});document.addEventListener('drop',e=>{const row=e.target.closest('.playlist-row');if(!playlistDrag||row?.dataset.playlist!==playlistDrag.playlist)return;e.preventDefault();const p=playlistBy(playlistDrag.playlist),id=playlistDrag.id,target=row.dataset.entry;if(p?.channelId==='me'&&id!==target){p.videoIds=p.videoIds.filter(x=>x!==id);p.videoIds.splice(p.videoIds.indexOf(target),0,id);p.updatedAt=RealClock.now();saveState(true);renderContent()}playlistDrag=null});
function earnStatsCards(entries){return `<div class="earn-grid">${entries.map(([label,value,note])=>`<div class="earn-card"><label>${label}</label><strong class="earn-live">${value}</strong><small>${note||'Виртуальные USD'}</small></div>`).join('')}</div>`}
function revenueChart(days,id=null){const pts=revenueSeries(days,id),max=Math.max(.000001,...pts.map(p=>p.income)),width=800,height=170,total=pts.reduce((s,p)=>s+p.income,0),coords=pts.map((p,i)=>`${20+i*760/Math.max(1,pts.length-1)},${185-p.income/max*height}`).join(' ');return `<div class="panel"><div class="section-head"><h2>Доход ${!days&&pts.some(p=>p.archive)?'· включая архив':''}</h2><strong>${money(total,true)}</strong></div><svg class="earn-chart" preserveAspectRatio="none" viewBox="0 0 ${width} 210" role="img" aria-label="График виртуального дохода: ${esc(money(total,true))}"><line x1="20" y1="185" x2="780" y2="185" stroke="var(--border)"/><line x1="20" y1="100" x2="780" y2="100" stroke="var(--border)" stroke-dasharray="4 5"/><polyline points="${coords}" fill="none" stroke="#26a6a0" stroke-width="3" stroke-linejoin="round"/>${pts.map((p,i)=>`<circle cx="${20+i*760/Math.max(1,pts.length-1)}" cy="${185-p.income/max*height}" r="${pts.length>100?1:3}" fill="#26a6a0"><title>${p.archive?'Архив закрытых месяцев':date(p.at)}: ${money(p.income,true)}</title></circle>`).join('')}</svg><div class="earn-chart-labels"><span>${date(pts[0].at)}</span><span>${date(pts.at(-1).at)}</span></div><p class="earn-note">Максимум за точку: ${money(max,true)}</p><p class="earn-note">${!days&&state.earn.activeAt<calendarCutoff(EARN_CONFIG.revenueDays)?'За всё время: месяцы; старые закрытые месяцы объединены в архив. ':''}Последние 400 дней хранятся по дням. Суммы до округления; наведите на точку.</p></div>`}
function qualificationPanel(){const e=state.earn,q=qualifiedTotals(),progress=(label,value,target,suffix,note)=>`<div class="earn-progress"><label class="tiny muted">${label}</label><strong>${value.toLocaleString('ru-RU',{maximumFractionDigits:1})} <small class="tiny muted">/ ${target.toLocaleString('ru-RU')} ${suffix}</small></strong><div class="earn-track" role="progressbar" aria-label="${label}" aria-valuenow="${Math.min(target,value)}" aria-valuemin="0" aria-valuemax="${target}"><span style="width:${Math.min(100,value/target*100)}%"></span></div><p class="tiny muted">${note}</p></div>`;return `<section class="panel"><h2>${e.status==='active'?'Условия программы':'Путь к партнёрской программе'}</h2><p class="earn-note">1 000 подписчиков и одно из двух условий: часы обычных видео или заинтересованные просмотры Shorts Feed.</p><div class="earn-progress-grid">${progress('Подписчики',Math.floor(q.subscribers),EARN_CONFIG.subscribers,'','Число подписчиков вашего канала')}${progress('Часы обычных публичных видео',q.hours,EARN_CONFIG.watchHours,'ч','Последние 365 календарных дней · Shorts исключены')}${progress('Заинтересованные просмотры Shorts',q.shorts,EARN_CONFIG.shortViews,'','Последние 90 дней · только открытые Shorts Feed, без повторов')}</div><p class="earn-note">Достоверный учёт начинается с ${dateTimeLabel(e.since,true)}. Старые общие просмотры и watch time сохранены в аналитике; без сведений о видимости в момент просмотра они не добавляются в квалификацию. Закрытые, удалённые и доступные только по ссылке публикации не учитываются.</p>${e.status==='active'?`<p class="earn-status">✓ Монетизация подключена · ${dateTimeLabel(e.activeAt,true)}</p>`:e.status==='pending'?`<p class="badge">На рассмотрении</p><p class="earn-note">Подано ${dateTimeLabel(e.submittedAt,true)}. Локальная проверка завершится после ${dateTimeLabel(e.reviewAt,true)} — около 10 реальных минут.</p>`:`${e.status==='rejected'?`<p class="form-error">${esc(e.reason)}</p>`:''}${btn('earn-apply','Подать заявку','','primary',earnEligible()?'':'disabled')}<p class="earn-note">${earnEligible()?'Условия выполнены. Можно отправить локальную заявку.':'Продолжайте публиковать и развивать канал.'}</p>`}</section>`}
function payoutPanel(){const e=state.earn,key=monthKey(RealClock.now()),prev=monthKey(monthStart(key,-1)),estimated=Object.values(e.months).filter(m=>!m.finalized).reduce((s,m)=>s+m.income,0);return `<section class="panel"><h2>Расчётные периоды и виртуальные выплаты</h2>${earnStatsCards([['Текущий месяц',money(e.months[key]?.income||0),'Estimated revenue · ещё не закрыт'],['Предыдущий месяц',money(e.months[prev]?.income||0),e.months[prev]?.finalized?'Finalized revenue':'Оценка · закрытие 7-го числа'],['Закрытый доход',money(finalizedTotal()),'Finalized revenue · накопительно'],['Доступный баланс',money(availableBalance()),'Закрытый доход минус виртуальные выплаты'],['Виртуально выплачено',money(e.paidTotal),'Simulated payout · переводов нет'],['Ожидает закрытия',money(estimated),'Оценка текущего и недавнего периода']])}<p class="earn-note">Месяц закрывается 7-го числа следующего месяца по местному реальному календарю. При балансе от ${money(EARN_CONFIG.payoutThreshold)} автоматически создаётся виртуальная запись до целых центов. Текущий месяц не выплачивается. Общий заработок ${money(revenueTotal().income,true)} включает оценочный и закрытый доход.</p><div class="earn-table-wrap"><table class="earn-table"><thead><tr><th>Дата</th><th>Закрыто по месяц</th><th>Сумма</th><th>Тип</th></tr></thead><tbody>${e.payouts.length?e.payouts.map(p=>`<tr><td>${dateTimeLabel(p.at,true)}</td><td>${esc(p.through||'Архив')}</td><td>${money(p.amount)}</td><td>Виртуальная выплата</td></tr>`).join(''):'<tr><td colspan="4">Виртуальных выплат пока нет</td></tr>'}${e.payoutsArchive?`<tr><td colspan="2">Архив предыдущих выплат</td><td>${money(e.payoutsArchive)}</td><td>Simulated payout</td></tr>`:''}</tbody></table></div></section>`}
function shortPoolBreakdown(){const key=monthKey(RealClock.now()),counts=state.earn.months[key]?.engaged||Array(6).fill(0),season=seasonDemand(RealClock.now());return `<p>Пул текущего месяца · ${key}. Все параметры вымышлены.</p><div class="earn-table-wrap"><table class="earn-table"><thead><tr><th>География</th><th>Доступный пул</th><th>Доля канала</th><th>Выделено каналу</th></tr></thead><tbody>${COUNTRY_LABELS.map((label,i)=>{const pool=EARN_CONFIG.shortPool[i]*season,share=counts[i]/(EARN_CONFIG.backgroundEngaged[i]+counts[i]);return `<tr><td>${label}</td><td>${money(pool)}</td><td>${(share*100).toFixed(5)}%</td><td>${money(pool*share,true)}</td></tr>`}).join('')}</tbody></table></div><p>Доход автора = выделенная часть × 45%. «Выделено» учитывает все подходящие Shorts канала этого месяца; повторное чтение таблицы ничего не начисляет.</p>`}
function earnModelPanel(){return `<div class="earn-model"><details class="panel"><summary>Как считается доход обычных видео</summary><p>Новые просмотры → доля воспроизведений с рекламой → рекламные показы → рекламный доход → 55% автору. Доля с рекламой зависит от пригодности и спроса; у длинных видео возможны дополнительные показы. География, категория, сезон и тип рекламы меняют CPM.</p><p>CPM = рекламный доход ÷ рекламные показы × 1 000, до распределения. RPM = доход автора ÷ все новые просмотры после подключения × 1 000, включая просмотры с выключенной монетизацией. В модели рекламный доход до распределения равен чистому доходу: дополнительных вычетов нет. Доля автора применяется один раз.</p></details><details class="panel"><summary>Как работает пул Shorts Feed</summary><p>Заинтересованные просмотры Feed без повторов распределяются по географии. В каждом месяце доступен конечный виртуальный пул каждой страны. Доля канала = его накопленные подходящие просмотры ÷ (его просмотры + фоновая аудитория платформы). Новому приросту выделяется только прирост доли пула; автор получает 45% этой суммы.</p><p>Сезон меняет доступный пул. Это агрегированная модель без определения музыки и лицензий. RPM Shorts здесь считается на все новые просмотры; рекламные показы и CPM отдельного Shorts не определяются.</p>${shortPoolBreakdown()}</details></div><p class="earn-note">Все ставки, фоновые аудитории и доллары вымышлены. Это автономная экономическая модель, без реальных рекламных ставок, платёжных сервисов и банковских данных.</p>`}
function earnDashboard(days=28){const all=revenueTotal(),range=revenueTotal(days),long=revenueTotal(days,null,'video'),short=revenueTotal(days,null,'short');return `${earnStatsCards([['За последние 28 дней',money(revenueTotal(28).income),'Estimated revenue'],['За последние 7 дней',money(revenueTotal(7).income),'Estimated revenue'],['Доход за всё время',money(all.income),'Накопленный заработок, до выплат'],['Средний RPM',money(range.views?range.income/range.views*1000:0,true),'Все новые просмотры · выбранный период'],['Средний CPM',long.adImpressions?money(long.gross/long.adImpressions*1000,true):'—','Только реклама обычных видео'],['Обычные видео',money(long.income),'Выбранный период'],['Shorts Feed',money(short.income),'Выбранный период']])}${revenueChart(days)}<section class="panel" style="margin:22px 0"><h2>Доход публикаций · ${days?days+' дней':'всё время'}</h2><div class="earn-table-wrap"><table class="earn-table"><thead><tr><th>Публикация</th><th>Формат</th><th>Новые просмотры</th><th>Доход</th><th>RPM</th></tr></thead><tbody>${Object.entries(state.earn.books).map(([id,b])=>{const r=revenueTotal(days,id);return `<tr><td>${videoBy(id)?`<a href="#/studio/video/${id}">${esc(b.title)}</a>`:esc(b.title)+' · удалено'}</td><td>${b.type==='short'?'Shorts':'Видео'}</td><td>${exact(r.views)}</td><td>${money(r.income,true)}</td><td>${money(r.views?r.income/r.views*1000:0,true)}</td></tr>`}).join('')||'<tr><td colspan="5">Новые просмотры после подключения появятся здесь.</td></tr>'}${!days&&state.earn.archive.video.views+state.earn.archive.short.views?`<tr><td>Архив удалённых публикаций</td><td>Все</td><td>${exact(state.earn.archive.video.views+state.earn.archive.short.views)}</td><td>${money(state.earn.archive.video.income+state.earn.archive.short.income,true)}</td><td>—</td></tr>`:''}</tbody></table></div></section>${payoutPanel()}${earnModelPanel()}`}
function earnPeriod(){const n=Number(readRoute().query.get('days')??28);return [0,7,28,90].includes(n)?n:28}
function earnPage(){const days=earnPeriod();return `<div class="studio-page"><div class="section-head"><h1>Монетизация</h1><select class="select earn-period" id="earn-period" aria-label="Период дохода">${[[7,'7 дней'],[28,'28 дней'],[90,'90 дней'],[0,'Всё время']].map(([n,label])=>`<option value="${n}"${days===n?' selected':''}>${label}</option>`).join('')}</select></div><div class="earn-intro"><span class="badge">Виртуальная партнёрская программа</span><h2>Ваши идеи могут приносить доход</h2><p>Развивайте канал, следите за рекламной экономикой публикаций и получайте виртуальные доллары. Учёт связан с реальными датами и новыми просмотрами.</p></div><div id="earn-qualification">${qualificationPanel()}</div><div id="earn-dynamic">${state.earn.status==='active'?earnDashboard(days):earnModelPanel()}</div></div>`}
function videoEarnPanel(v){const e=state.earn;if(v?.channelId!=='me')return '';const x=initializeEarningVideo(v),s=suitability(v),r=revenueTotal(earnPeriod(),v.id),enabled=e.status==='active';return `<section class="panel earn-video" id="video-earn" data-earn-video="${v.id}"><div class="section-head"><div><h2>${isShort(v)?'Доход Shorts Feed':'Доход от рекламы'}</h2><p class="earn-note">${enabled?'Новые просмотры после '+dateTimeLabel(e.activeAt,true):'Подключите виртуальную партнёрскую программу в разделе «Монетизация».'}</p></div>${enabled?btn('earn-toggle',x.enabled?(isShort(v)?'Участие в Feed: On':'Монетизация: On'):(isShort(v)?'Участие в Feed: Off':'Монетизация: Off'),'','outline',`data-id="${v.id}" aria-pressed="${x.enabled}"`):link('studio/earn','Монетизация','analytics','btn outline')}</div><span class="earn-status ${s.status==='limited'?'limited':s.status==='off'?'off':''}">${s.label}</span><p class="earn-note">${esc(s.reason)} ${earningStatus(v).label}.</p>${earnStatsCards([['Estimated revenue',money(r.income,true),'Выбранный период'],['RPM',money(r.views?r.income/r.views*1000:0,true),'Доход автора / все новые просмотры × 1 000'],[isShort(v)?'Выделено из пула':'CPM',isShort(v)?money(r.allocation,true):r.adImpressions?money(r.gross/r.adImpressions*1000,true):'—',isShort(v)?'Выделено до доли автора 45%':'До доли автора 55%'],[isShort(v)?'Подходящие просмотры Feed':'Monetized playbacks',exact(isShort(v)?r.engaged:r.playbacks),isShort(v)?'Без повторов; с учётом пригодности':'Воспроизведения с рекламой'],['Новые просмотры',exact(r.views),'После подключения, включая Off'],[isShort(v)?'Модель':'Рекламные показы',isShort(v)?'Creator Pool':exact(r.adImpressions),isShort(v)?'CPM отдельного Shorts не применяется':'Может быть больше воспроизведений']])}${revenueChart(earnPeriod(),v.id)}<p class="earn-note">Период дохода: ${earnPeriod()?earnPeriod()+' дней':'всё время'}. <a href="#/studio/video/${v.id}?days=7">7 дней</a> · <a href="#/studio/video/${v.id}?days=28">28 дней</a> · <a href="#/studio/video/${v.id}?days=90">90 дней</a> · <a href="#/studio/video/${v.id}?days=0">Всё время</a>. Ранее заработанный доход сохраняется при выключении, смене видимости и удалении публикации.</p></section>`}
const analyticsBeforeCreator=analytics;analytics=function(v=null){const html=analyticsBeforeCreator(v);return v?html+videoEarnPanel(v):html+`<div class="studio-page"><div class="panel"><h2>Доход канала</h2><p class="earn-note">${state.earn.status==='active'?'За последние 28 дней: '+money(revenueTotal(28).income):'Подключите виртуальную монетизацию после выполнения условий.'}</p>${link('studio/earn','Открыть монетизацию','analytics','btn outline')}</div></div>`};
const contentBeforeCreator=contentPage;contentPage=function(){return contentBeforeCreator().replace(/(<tr data-video="([^"]+)">)([\s\S]*?)(<\/tr>)/g,(row,start,id,body,end)=>{const v=videoBy(id);if(!v)return row;const s=earningStatus(v);const badge=`<a href="#/studio/video/${v.id}" class="earn-status ${s.status==='limited'?'limited':s.status==='off'?'off':''}" title="${esc(s.label)}" aria-label="Монетизация: ${esc(s.label)}" data-earn-badge="${v.id}">$</a>`;return start+body.replace('<div class="row gap8">','<div class="row gap8">'+badge)+end})};
actions['earn-apply']=()=>{if(applyEarning()){renderContent();toast('Заявка отправлена. Проверка займёт 10 реальных минут.')}};actions['earn-toggle']=b=>{const v=videoBy(b.dataset.id);if(v&&setVideoEarning(v,!initializeEarningVideo(v).enabled))renderContent()};
document.addEventListener('change',e=>{if(e.target.id==='earn-period')location.hash='/studio/earn?days='+e.target.value});
const updateBeforeCreator=updateLive;let earnQualifiedKey='',earnDashboardKey='',earnVideoKey='';updateLive=function(){updateBeforeCreator();if(!state?.earn)return;earnMaintenance();const q=$('#earn-qualification'),dash=$('#earn-dynamic'),panel=$('#video-earn'),status=state.earn.status,qualifiedKey=JSON.stringify([qualifiedTotals(),status,state.earn.reason]);if(q&&qualifiedKey!==earnQualifiedKey&&!q.contains(document.activeElement)){q.innerHTML=qualificationPanel();earnQualifiedKey=qualifiedKey}const dashboardKey=JSON.stringify([status,revenueTotal(earnPeriod()),state.earn.paidTotal,finalizedTotal(),earnPeriod()]);if(dash&&dashboardKey!==earnDashboardKey&&!dash.contains(document.activeElement)){const opened=[...$$('details',dash)].map(x=>x.open);dash.innerHTML=status==='active'?earnDashboard(earnPeriod()):earnModelPanel();$$('details',dash).forEach((x,i)=>x.open=!!opened[i]);earnDashboardKey=dashboardKey}if(panel&&!panel.contains(document.activeElement)){const v=videoBy(panel.dataset.earnVideo),key=v?JSON.stringify([v.id,status,v.earning?.enabled,v.visibility,suitability(v),revenueTotal(earnPeriod(),v.id),earnPeriod()]):'';if(v&&key!==earnVideoKey){panel.outerHTML=videoEarnPanel(v);earnVideoKey=key}}};
// Validate raw creator data before older validators can migrate or mutate it.
const validateBeforeCreator=validateImport;validateImport=function(data){
 const fail=()=>{throw Error('Некорректные данные плейлистов или виртуальной монетизации. Текущие данные сохранены.')},finite=n=>typeof n==='number'&&Number.isFinite(n)&&n>=0&&n<=1e22,near=(a,b)=>Math.abs(a-b)<=1e-7*Math.max(1,Math.abs(a),Math.abs(b)),idOK=id=>typeof id==='string'&&/^[-a-zA-Z0-9]+$/.test(id),time=n=>finite(n)&&n<=RealClock.now()+60000,unique=(list,key)=>new Set(list.map(key)).size===list.length;
 if(data.creatorVersion!==undefined&&data.creatorVersion!==1)fail();if(data.creatorVersion===undefined&&(data.earn!==undefined||data.playlists!==undefined))fail();
 if(data.creatorVersion===1){
  if(!Array.isArray(data.playlists)||data.playlists.length>200||!data.earn||typeof data.preferences?.playlistAuto!=='boolean'||typeof data.preferences?.playlistRepeat!=='boolean')fail();
  for(const p of data.playlists){if(!p||!idOK(p.id)||!data.channels.some(c=>c.id===p.channelId)||typeof p.title!=='string'||!p.title.trim()||p.title.length>100||typeof p.description!=='string'||p.description.length>3000||!['public','unlisted','private'].includes(p.visibility)||typeof p.cover!=='string'||p.cover.length>500000||p.cover&&!/^(asset:[a-zA-Z0-9-]+|data:image\/(webp|png|jpeg|gif)[;,])/.test(p.cover)||!Array.isArray(p.videoIds)||p.videoIds.length>EARN_CONFIG.entriesLimit||p.videoIds.some(id=>!idOK(id))||!unique(p.videoIds,id=>id)||!time(p.createdAt)||!time(p.updatedAt)||p.updatedAt<p.createdAt)fail()}if(!unique(data.playlists,p=>p.id))fail();
  const e=data.earn;if(!['none','pending','active','rejected'].includes(e.status)||![e.since,e.submittedAt,e.activeAt].every(time)||!finite(e.reviewAt)||e.reviewAt>RealClock.now()+EARN_CONFIG.reviewDelay+60000||typeof e.reason!=='string'||!e.books||Array.isArray(e.books)||Object.keys(e.books).length>6000||!e.months||Array.isArray(e.months)||Object.keys(e.months).length>EARN_CONFIG.monthLimit+1||!e.archive||![e.finalizedArchive,e.paidTotal,e.payoutsArchive].every(finite)||!Array.isArray(e.payouts)||e.payouts.length>EARN_CONFIG.payoutLimit)fail();
  if(e.status==='active'&&(!e.activeAt||e.activeAt<e.submittedAt||e.activeAt<e.reviewAt)||e.status==='pending'&&(e.activeAt||e.reviewAt!==e.submittedAt+EARN_CONFIG.reviewDelay))fail();
  const validMetric=r=>r&&EARN_FIELDS.every(k=>finite(r[k]));let totalIncome=0;for(const [id,b]of Object.entries(e.books)){if(!idOK(id)||!['video','short'].includes(b.type)||typeof b.title!=='string'||b.title.length>500||!validMetric(b.totals)||!validMetric(b.before)||!Array.isArray(b.days)||b.days.length>EARN_CONFIG.revenueDays+1||!unique(b.days,r=>r.at))fail();const sum={...b.before};for(const row of b.days){if(!validMetric(row)||!time(row.at)||row.at<localDay(e.activeAt))fail();earnMerge(sum,row)}if(EARN_FIELDS.some(k=>!near(sum[k],b.totals[k])))fail();if(b.type==='video'&&(!near(b.totals.income,b.totals.net*EARN_CONFIG.creatorLong)||!near(b.totals.gross,b.totals.net)||b.totals.playbacks>b.totals.views+1e-6||b.totals.engaged||b.totals.allocation)||b.type==='short'&&(!near(b.totals.income,b.totals.allocation*EARN_CONFIG.creatorShort)||b.totals.adImpressions||b.totals.gross||b.totals.net||b.totals.playbacks||b.totals.engaged>b.totals.views+1e-6))fail();totalIncome+=b.totals.income}
  for(const format of ['video','short']){const a=e.archive[format];if(!validMetric(a))fail();if(format==='video'&&!near(a.income,a.net*EARN_CONFIG.creatorLong)||format==='short'&&!near(a.income,a.allocation*EARN_CONFIG.creatorShort))fail();totalIncome+=a.income}
  let monthly=e.finalizedArchive,finalized=e.finalizedArchive;for(const [key,m]of Object.entries(e.months)){if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(key)||monthStart(key)>RealClock.now()||!finite(m.income)||typeof m.finalized!=='boolean'||!Array.isArray(m.engaged)||m.engaged.length!==6||!m.engaged.every(finite)||m.finalized&&(!time(m.finalizedAt)||m.finalizedAt<monthStart(key,1,EARN_CONFIG.finalizeDay)))fail();monthly+=m.income;if(m.finalized)finalized+=m.income}
  if(!near(monthly,totalIncome)||e.paidTotal>finalized+1e-6||!near(e.payoutsArchive+e.payouts.reduce((s,p)=>s+(p.amount||0),0),e.paidTotal))fail();for(const p of e.payouts)if(!idOK(p.id)||!time(p.at)||!finite(p.amount)||p.amount<EARN_CONFIG.payoutThreshold-.001||p.kind!=='simulated'||typeof p.through!=='string'||!near(p.amount*100,Math.round(p.amount*100)))fail();if(!unique(e.payouts,p=>p.id))fail();
  for(const v of data.videos.filter(v=>v.channelId==='me')){const x=v.earning;if(!x||typeof x.enabled!=='boolean'||!x.cursor||![x.cursor.views,x.cursor.watch,x.cursor.engaged].every(finite)||x.cursor.views>v.views+1e-5||x.cursor.watch>v.watchSeconds+1e-5||x.cursor.engaged>(v.shortStats?.viewedExposures||0)+1e-5||!Array.isArray(x.qualification)||x.qualification.length>EARN_CONFIG.qualificationDays+1||!unique(x.qualification,r=>r.at))fail();for(const r of x.qualification)if(!time(r.at)||!finite(r.watch)||!finite(r.engaged)||isShort(v)&&r.watch||!isShort(v)&&r.engaged)fail()}
  if(e.status!=='active'&&totalIncome>0)fail();
 }
 return validateBeforeCreator(data);
};
