// YOUTRUBE 2.0 / BACKWARD-COMPATIBLE SCHEMA
const assetCache=new Map();let npcPublishBudget=0,pendingAssets={},analyticsFocus=null;
const isShort=v=>v?.type==='short';
const videoRoute=v=>(isShort(v)?'shorts/':'watch/')+v.id;
paths.shorts='m15 2 6 4-5 4 4 3-11 9-6-4 5-4-4-3Zm-5 7v7l6-3.5Z';paths.comments='M21 3H3v14h4v5l6-5h8Z';
function migrateState(s){if(![1,2].includes(s.version))throw Error('Неизвестная версия данных.');s.version=2;s.ecosystem??={shortsSeeded:false,pruned:0};s.user.shortHistory??=[];s.preferences.shortAutoplay??=false;s.preferences.shortMuted??=true;s.channels.forEach(c=>{if(c.id==='me')return;c.shortProbability??=({Игры:.68,Развлечения:.65,Музыка:.55,Спорт:.6,Новости:.45,Обучение:.22,Подкасты:.35}[c.niche]||.42);c.uploadSerial??=4;c.nextUploadAt??=s.simulation.now+(1+seeded(c.seed,'schedule')*3)*864e5/Math.max(1,c.uploadFrequency);c.publicationHistory??=[];c.archivedViews??=0;c.archivedCount??=0});s.videos.forEach(v=>{v.type??='video';v.archived??=false;while(v.traffic.length<SOURCE_NAMES.length)v.traffic.push(0);if(isShort(v)){v.shortParams??=shortParameters(v,s.channels.find(c=>c.id===v.channelId));initializeShort(v,false);}v.history.forEach(h=>{for(const k of ['shownInFeed','viewedExposures','swipedAway','rewatches'])h[k]??=0})});s.userChannel=s.channels.find(c=>c.id==='me');return s}
// IMAGES: durable writes before replacing inline data; inline fallback on any failure.
const ImageStore={db:null,available:false,
 async open(){if(!globalThis.indexedDB)return;try{this.db=await new Promise((resolve,reject)=>{const req=indexedDB.open('youtrube.images',1);const timeout=setTimeout(()=>reject(Error('storage timeout')),3500);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains('images'))req.result.createObjectStore('images')};req.onsuccess=()=>{clearTimeout(timeout);resolve(req.result)};req.onerror=()=>{clearTimeout(timeout);reject(req.error)};req.onblocked=()=>{clearTimeout(timeout);reject(Error('storage blocked'))}});this.db.onversionchange=()=>{this.db.close();this.available=false};this.available=true;await this.hydrate()}catch{this.available=false}},
 async hydrate(){if(!this.db)return;await new Promise((resolve,reject)=>{const tx=this.db.transaction('images','readonly'),req=tx.objectStore('images').openCursor();req.onsuccess=()=>{const cursor=req.result;if(cursor){assetCache.set('asset:'+cursor.key,cursor.value);cursor.continue()}};tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})},
 async put(data,key=null){if(!data||String(data).startsWith('asset:'))return data;if(!this.available)return data;const id=key||uid('image');try{await new Promise((resolve,reject)=>{const tx=this.db.transaction('images','readwrite');tx.objectStore('images').put(data,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});assetCache.set('asset:'+id,data);return 'asset:'+id}catch{toast('Изображение сохранено в резервном формате.');return data}},
 async clear(){if(this.db){try{await new Promise((resolve,reject)=>{const tx=this.db.transaction('images','readwrite');tx.objectStore('images').clear();tx.oncomplete=resolve;tx.onerror=reject})}catch{}}assetCache.clear()},
 async collect(){if(!this.available)return;const used=new Set();state.channels.forEach(c=>[c.avatar,c.banner].forEach(x=>{if(x?.startsWith('asset:'))used.add(x)}));state.videos.forEach(v=>{if(v.thumbnail?.startsWith('asset:'))used.add(v.thumbnail)});try{const tx=this.db.transaction('images','readwrite'),store=tx.objectStore('images');for(const ref of assetCache.keys())if(!used.has(ref)){store.delete(ref.slice(6));assetCache.delete(ref)}}catch{}}
};
async function migrateImages(){let moved=0;for(const c of state.channels)if(c.id==='me')for(const k of ['avatar','banner'])if(c[k]?.startsWith('data:')){const old=c[k],ref=await ImageStore.put(old,'legacy-'+hash(old)+'-'+k);if(ref!==old){c[k]=ref;moved++}}for(const v of mine())if(v.thumbnail?.startsWith('data:')){const old=v.thumbnail,ref=await ImageStore.put(old,'legacy-'+hash(old));if(ref!==old){v.thumbnail=ref;moved++}}if(moved){state.userChannel=channelBy('me');if(!saveState(true)){for(const c of state.channels)for(const k of ['avatar','banner'])if(c[k]?.startsWith('asset:'))c[k]=assetCache.get(c[k])||c[k];state.videos.forEach(v=>{if(v.thumbnail?.startsWith('asset:'))v.thumbnail=assetCache.get(v.thumbnail)||v.thumbnail});saveState(true)}}}
const baseExport=exportData;
exportData=async function(){try{saveState(true);const backup=JSON.parse(JSON.stringify(state));backup.assets={};state.channels.forEach(c=>[c.avatar,c.banner].forEach(ref=>{if(ref?.startsWith('asset:'))backup.assets[ref]=assetCache.get(ref)}));state.videos.forEach(v=>{if(v.thumbnail?.startsWith('asset:'))backup.assets[v.thumbnail]=assetCache.get(v.thumbnail)});const blob=new Blob([JSON.stringify(backup)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='youtrube-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Данные и изображения экспортированы')}catch{toast('Не удалось экспортировать данные.')}};
actions.export=exportData;
actions.restore=async function(){if(!pendingImport)return;try{for(const [ref,data] of Object.entries(pendingAssets)){if(!/^asset:[a-zA-Z0-9-]+$/.test(ref)||!/^data:image\/(webp|png|jpeg|gif)[;,]/.test(data||''))throw Error('Некорректное изображение в резервной копии.');const result=await ImageStore.put(data,ref.slice(6));if(!result.startsWith('asset:')){pendingImport.channels.forEach(c=>{if(c.avatar===ref)c.avatar=data;if(c.banner===ref)c.banner=data});pendingImport.videos.forEach(v=>{if(v.thumbnail===ref)v.thumbnail=data})}}const refs=[...pendingImport.channels.flatMap(c=>[c.avatar,c.banner]),...pendingImport.videos.map(v=>v.thumbnail)].filter(x=>x?.startsWith('asset:'));if(refs.some(ref=>!assetCache.has(ref)))throw Error('В резервной копии отсутствуют изображения. Текущие данные сохранены.');state=migrateState(pendingImport);pendingImport=null;pendingAssets={};await migrateImages();seedShortEcosystem();imageCache.clear();settleTime();syncChannelTotals();saveState(true);closeModal();setTheme(state.preferences.theme);render();toast('Данные и изображения восстановлены')}catch(e){toast(e.message)}};
// SHORTS DISTRIBUTION: exposure, swipe, completion and repeat viewing.
function shortParameters(v,c){const r=rng(hash(v.seed+':short'));const q=clamp(v.params.contentQuality*.8+.12+r()*.13,.12,.99),fit=clamp(v.params.audienceFit*.82+.08+r()*.13);const completion=clamp(.18+q*.7+r()*.12-Math.max(0,v.duration-35)/500,.15,.99),rewatch=clamp(Math.pow(q,3)*(.1+r()*.55)*(v.duration<65?1:.55),.003,.65),viewed=clamp(.2+q*.62+fit*.12-(1-v.params.clickability)*.08,.18,.96);return{shortsQuality:q,audienceFit:fit,viewedRate:viewed,swipeAwayRate:1-viewed,completionRate:completion,rewatchRate:rewatch,averageViewDuration:v.duration*(.25+.77*completion+rewatch*1.25),engagementRate:.025+q*.065,shortsMomentum:0,distributionScore:0,potential:clamp(Math.exp(normal(r)*1.5-.25)*(.4+q),.08,60),lastWaveHour:-1,velocity:0}}
function initializeShort(v,reset=false){v.type='short';v.shortParams??=shortParameters(v,channelBy(v.channelId));v.shortStats??={shownInFeed:0,viewedExposures:0,swipedAway:0,rewatches:0};v.impressions=0;if(reset){v.views=v.likes=v.dislikes=v.comments=v.watchSeconds=v.subscribersGained=0;v.history=[];v.traffic=Array(SOURCE_NAMES.length).fill(0)}const p=v.shortParams;p.distributionScore=clamp(p.viewedRate*.32+p.completionRate*.28+clamp(p.rewatchRate/.45)*.17+clamp(p.engagementRate/.09)*.13+p.audienceFit*.1);return v}
function shortExposureRate(v,c,t){const p=v.shortParams,age=Math.max(0,(t-v.publishedAt)/3600e3),success=clamp((p.distributionScore-.49)*3.7,0,1.6),base=(115+Math.pow(c.subscribers,.6)*.65)*(.6+p.audienceFit);let wave=age<1?.65:age<12?1+success*p.potential*Math.pow(age/2,1.55):age<36?(1+success*p.potential*32)*Math.exp(-Math.pow((age-18)/20,2)):(.18+v.params.evergreenFactor*.18)+(1+success*p.potential*9)*Math.exp(-(age-36)/24);if(age>30){const center=50+seeded(v.seed,'waveCenter')*50;wave+=success*success*p.potential*16*Math.exp(-Math.pow((age-center)/10,2));wave+=success*success*p.potential*8*Math.exp(-Math.pow((age-center-50)/15,2))}const saturation=1/(1+v.views/(6000+p.potential*65000+Math.pow(c.subscribers+1,.8)*80));return clamp(base*wave*(1+p.shortsMomentum*8)*saturation*(.5+p.distributionScore),0,550000)}
function applyShortExposure(v,shown,t,hours){const c=channelBy(v.channelId),p=v.shortParams,s=v.shortStats,viewed=shown*p.viewedRate,swiped=shown-viewed,rewatches=viewed*p.rewatchRate,views=viewed+rewatches,watchSeconds=views*p.averageViewDuration,likes=views*p.engagementRate,subscribers=views*(.00025+p.shortsQuality*p.audienceFit*.005)/(1+c.subscribers/2e6);s.shownInFeed+=shown;s.viewedExposures+=viewed;s.swipedAway+=swiped;s.rewatches+=rewatches;v.views+=views;v.likes+=likes;v.dislikes+=views*(.001+(1-p.shortsQuality)*.012);v.comments+=views*(.0004+p.engagementRate*.06);v.watchSeconds+=watchSeconds;v.subscribersGained+=subscribers;c.subscribers+=subscribers;p.velocity=views/Math.max(hours,.0001);c.authority=clamp(c.authority+(p.distributionScore-c.authority)*Math.min(hours*.0003,.015),.05,.98);v.params.recommendationScore=p.distributionScore;v.traffic[6]+=views*.93;v.traffic[2]+=views*.035;v.traffic[3]+=views*.025;v.traffic[4]+=views*.01;if(c.id==='me')historyAdd(v,t,{views,likes,subscribersGained:subscribers,watchSeconds,impressions:0,shownInFeed:shown,viewedExposures:viewed,swipedAway:swiped,rewatches})}
function simulateShortStep(v,from,to){const hours=(to-from)/3600e3;if(!hours)return;const c=channelBy(v.channelId),p=v.shortParams,mid=(from+to)/2,hourIndex=Math.floor(to/3600e3);if(p.lastWaveHour!==hourIndex){p.lastWaveHour=hourIndex;if(seeded(v.seed,'shortSpike'+hourIndex)<Math.pow(p.distributionScore,3)*.006&&v.views>75&&to-v.publishedAt<7*864e5)p.shortsMomentum=clamp(p.shortsMomentum+.3+p.shortsQuality*.5)}p.shortsMomentum*=Math.exp(-hours/9);const rate=shortExposureRate(v,c,mid)*(.94+seeded(v.seed,'sRate'+hourIndex)*.12);applyShortExposure(v,rate*hours,to,hours)}
// LIVING ECOSYSTEM: independent publication clocks, bounded offline batches.
const SHORT_TOPICS={Технологии:['Один приём для удобного рабочего места','Нужна ли вам эта функция?'],Музыка:['Мелодия, которая меняет настроение','Один аккорд — целая история'],Игры:['Секрет, который легко пропустить','Вот почему этот уровень гениален'],Новости:['Что изменилось в городе сегодня','Одна идея из мира науки'],Развлечения:['Попробовать новое за одну минуту','Неожиданный поворот обычного дня'],Обучение:['Запомните это простое правило','О сложном за 60 секунд'],Спорт:['Движение, с которого начинается утро','Маленький шаг к большой привычке'],Подкасты:['Мысль, которую хочется сохранить','Ответ, который заставил задуматься'],Путешествия:['Рассвет, ради которого стоит проснуться','Тропа за следующим поворотом'],Дизайн:['Одна деталь меняет всё','Почему эта форма работает']};
function makeNPCPublication(c,index,at,type,initial=false){const v=makeVideo(c,index,state.simulation.now);v.id='npc-'+c.id+'-'+index+'-'+hash(at);v.seed=hash(c.seed+':publication:'+index);v.publishedAt=at;v.type=type;v.archived=false;v.title=type==='short'?SHORT_TOPICS[c.niche][index%2]:(TOPICS[c.niche][index%4][0]+(index>5?' · '+['Новый взгляд','Практика','Личный опыт','Детали'][Math.floor(index/4)%4]:''));v.duration=type==='short'?18+num(seeded(v.seed,'duration')*72):300+num(seeded(v.seed,'duration')*1500);v.thumbnail=null;v.params=params(v,c);v.views=v.impressions=v.likes=v.dislikes=v.comments=v.watchSeconds=v.subscribersGained=0;v.history=[];v.traffic=Array(SOURCE_NAMES.length).fill(0);if(type==='short'){initializeShort(v);if(initial){const shown=Math.exp(8+normal(rng(v.seed))*1.5);applyShortExposure(v,shown,at,24)}}return v}
function seedShortEcosystem(){if(state.ecosystem.shortsSeeded)return;for(const c of state.channels.filter(c=>c.id!=='me')){for(let i=0;i<2;i++){const n=100+i,at=state.simulation.now-(.1+seeded(c.seed,n)*7)*864e5;const v=makeNPCPublication(c,n,at,'short',true);state.videos.push(v);c.publicationHistory.push({id:v.id,type:v.type,at})}}state.ecosystem.shortsSeeded=true;syncChannelTotals()}
function publishNPCDue(now){if(npcPublishBudget<=0)return;const due=state.channels.filter(c=>c.id!=='me'&&c.nextUploadAt<=now).sort((a,b)=>a.nextUploadAt-b.nextUploadAt);for(const c of due){if(npcPublishBudget<=0)break;const serial=c.uploadSerial++,at=c.nextUploadAt,type=seeded(c.seed,'type'+serial)<c.shortProbability?'short':'video';const v=makeNPCPublication(c,serial,at,type);state.videos.push(v);c.publicationHistory.push({id:v.id,type,at});c.publicationHistory=c.publicationHistory.slice(-60);c.nextUploadAt=at+(1.3+seeded(c.seed,'wait'+serial)*5)*864e5/Math.max(1,c.uploadFrequency);npcPublishBudget--}}
function pruneNPC(){const npc=state.videos.filter(v=>v.channelId!=='me');if(npc.length<=280)return;const protectedIds=new Set([...state.history.map(h=>h.videoId),...state.user.shortHistory.map(h=>h.videoId),...state.user.watchLater,...Object.keys(state.user.reactions)]);const candidates=npc.filter(v=>!protectedIds.has(v.id)).sort((a,b)=>a.publishedAt-b.publishedAt);const remove=new Set(candidates.slice(0,Math.max(0,npc.length-260)).map(v=>v.id));for(const v of npc)if(remove.has(v.id)){const c=channelBy(v.channelId);c.archivedViews=(c.archivedViews||0)+v.views;c.archivedCount=(c.archivedCount||0)+1;state.ecosystem.pruned++}state.videos=state.videos.filter(v=>!remove.has(v.id));imageCache.clear()}
// Format-aware recommendation scoring, with strong repeat and diversity penalties.
function shortRecommendations(exclude=null,category='Все'){const recent=new Map(state.user.shortHistory.map((h,i)=>[h.videoId,1-i/Math.max(1,state.user.shortHistory.length)])),windowIndex=Math.floor(state.simulation.now/3600e3);const candidates=state.videos.filter(v=>isShort(v)&&!v.archived&&v.visibility==='public'&&v.id!==exclude&&!state.user.notInterested.includes(v.id)&&!state.user.blockedChannels.includes(v.channelId)&&(category==='Все'||v.category===category)).map(v=>({v,score:(state.user.interests[v.category]||.35)*.28+v.shortParams.distributionScore*.25+(state.subscriptions.includes(v.channelId)?.2:0)+Math.exp(-(state.simulation.now-v.publishedAt)/(7*864e5))*.1+seeded(v.seed,'feed'+windowIndex)*.25-(recent.get(v.id)||0)*.45+(v.shortParams.shortsMomentum||0)*.07}));const result=[],topics={},channels={};while(candidates.length&&result.length<32){candidates.sort((a,b)=>(b.score-(topics[b.v.category]||0)*.07-(channels[b.v.channelId]||0)*.14)-(a.score-(topics[a.v.category]||0)*.07-(channels[a.v.channelId]||0)*.14));const v=candidates.shift().v;result.push(v);topics[v.category]=(topics[v.category]||0)+1;channels[v.channelId]=(channels[v.channelId]||0)+1}return result}
// ORIGINAL ARTWORK: format-specific illustrations, rendered only on demand.
const baseArt=art;
function svgUrl(s){return 'data:image/svg+xml;charset=utf-8,'+encodeURIComponent(s)}
function themedScene(v,w,h){const p=PALETTES[v.seed%8],theme=v.category;let scene='';if(['Путешествия','Спорт'].includes(theme)){scene=`<circle cx="${w*.73}" cy="${h*.2}" r="${w*.12}" fill="${p[2]}"/><path d="M0 ${h*.74} ${w*.32} ${h*.33} ${w*.46} ${h*.62} ${w*.67} ${h*.22} ${w} ${h*.77}V${h}H0Z" fill="${p[1]}"/><path d="m${w*.67} ${h*.22} ${-w*.08} ${h*.21} ${w*.065} ${-h*.025} ${w*.046} ${h*.016}Z" fill="#fff" opacity=".8"/><path d="M0 ${h*.84}Q${w*.27} ${h*.63} ${w*.6} ${h*.83}T${w} ${h*.76}V${h}H0Z" fill="${p[0]}" opacity=".85"/><path d="M${w*.52} ${h}q${-w*.13} ${-h*.17} ${w*.08} ${-h*.2}t${w*.05} ${-h*.14}" stroke="${p[2]}" stroke-width="${w*.022}" fill="none"/><g stroke="${p[1]}" stroke-width="${w*.008}" opacity=".65"><path d="M${w*.1} ${h*.12}h${w*.1}M${w*.08} ${h*.15}h${w*.16}M${w*.09} ${h*.18}h${w*.09}"/></g>`}
else if(theme==='Музыка'||theme==='Подкасты'){scene=`<circle cx="${w*.56}" cy="${h*.53}" r="${w*.31}" fill="${p[1]}"/><circle cx="${w*.56}" cy="${h*.53}" r="${w*.24}" fill="${p[0]}"/><circle cx="${w*.56}" cy="${h*.53}" r="${w*.09}" fill="${p[2]}"/><g stroke="${p[1]}" fill="none" stroke-width="${w*.008}" opacity=".5">${[.14,.19,.22,.27].map(x=>`<circle cx="${w*.56}" cy="${h*.53}" r="${w*x}"/>`).join('')}</g><path d="M${w*.8} ${h*.13}v${h*.31}l${-w*.12} ${h*.13}" stroke="${p[2]}" stroke-width="${w*.018}" fill="none"/><path d="M${w*.05} ${h*.78}q${w*.15} ${-h*.12} ${w*.3} 0t${w*.3} 0t${w*.3} 0" fill="none" stroke="${p[1]}" stroke-width="${w*.01}"/>`}
else if(theme==='Игры'){scene=`<g transform="translate(${w*.13} ${h*.24})"><path d="M0 ${h*.19} ${w*.32} 0 ${w*.69} ${h*.17} ${w*.35} ${h*.35}Z" fill="${p[1]}"/><path d="M0 ${h*.19}v${h*.11}l${w*.35} ${h*.19}v${-h*.14}Z" fill="${p[2]}"/><path d="M${w*.35} ${h*.35} ${w*.69} ${h*.17}v${h*.15}l${-w*.34} ${h*.17}Z" fill="${p[1]}" opacity=".5"/><path d="M${w*.35} ${h*.3}v${-h*.24}l${w*.13} ${h*.07}v${h*.22}Z" fill="${p[2]}"/><circle cx="${w*.26}" cy="${h*.1}" r="${w*.045}" fill="${p[0]}"/><path d="m${w*.05} ${h*.18} ${w*.16} ${-h*.08} ${w*.06} ${h*.035}" stroke="${p[0]}" stroke-width="${w*.012}" fill="none"/></g><g fill="${p[2]}"><circle cx="${w*.85}" cy="${h*.14}" r="${w*.012}"/><circle cx="${w*.13}" cy="${h*.15}" r="${w*.016}"/></g>`}
else if(theme==='Новости'){scene=`<g fill="${p[1]}"><path d="M${w*.11} ${h*.8}V${h*.3}h${w*.2}v${h*.5}M${w*.36} ${h*.8}V${h*.18}h${w*.26}v${h*.62}M${w*.68} ${h*.8}V${h*.42}h${w*.2}v${h*.38}"/></g><g stroke="${p[0]}" stroke-width="${w*.012}">${Array.from({length:7},(_,i)=>`<path d="M${w*.14} ${h*(.35+i*.057)}h${w*.14}M${w*.4} ${h*(.23+i*.072)}h${w*.18}"/>`).join('')}</g><path d="M0 ${h*.83}q${w*.5} ${-h*.18} ${w} 0" stroke="${p[2]}" stroke-width="${w*.02}" fill="none"/>`}
else if(theme==='Технологии'){scene=`<g transform="translate(${w*.25} ${h*.17}) rotate(8)"><rect width="${w*.46}" height="${h*.58}" rx="${w*.045}" fill="${p[1]}"/><rect x="${w*.025}" y="${h*.035}" width="${w*.41}" height="${h*.47}" rx="${w*.02}" fill="${p[0]}"/><circle cx="${w*.23}" cy="${h*.25}" r="${w*.11}" fill="${p[2]}"/><path d="M${w*.09} ${h*.4}h${w*.26}" stroke="${p[1]}" stroke-width="${w*.012}"/></g><circle cx="${w*.14}" cy="${h*.68}" r="${w*.07}" fill="${p[2]}"/><path d="M${w*.75} ${h*.43}h${w*.13}m${-w*.065} ${-h*.06}v${h*.12}" stroke="${p[1]}" stroke-width="${w*.008}"/>`}
else{scene=`<g transform="translate(${w*.12} ${h*.22})"><rect width="${w*.72}" height="${h*.5}" rx="${w*.02}" fill="${p[1]}"/><circle cx="${w*.24}" cy="${h*.2}" r="${w*.14}" fill="${p[0]}"/><path d="m${w*.38} ${h*.06} ${w*.24} ${h*.34}h${-w*.4}Z" fill="${p[2]}"/><path d="M${w*.05} ${h*.43}h${w*.23}m${w*.03} 0h${w*.27}" stroke="${p[0]}" stroke-width="${w*.008}"/></g><g fill="${p[2]}" opacity=".4"><circle cx="${w*.08}" cy="${h*.17}" r="${w*.018}"/><circle cx="${w*.9}" cy="${h*.8}" r="${w*.04}"/></g>`}return scene}
art=function(v,banner=false){if(banner)return baseArt(v,banner);const p=PALETTES[v.seed%8];if(!isShort(v)&&v.seed%3===0)return baseArt(v);const portrait=isShort(v),w=portrait?540:960,h=portrait?960:540;const source=(v.artText||v.title||v.category).toUpperCase().replace(/[—:·]/g,' ').split(/\s+/).slice(0,portrait?6:5);const lines=[];source.forEach(word=>{if(!lines.length||lines.at(-1).length+word.length> (portrait?17:26))lines.push(word);else lines[lines.length-1]+=' '+word});const titleY=portrait?80:55,fs=portrait?30:36;return svgUrl(`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="${p[0]}"/>${themedScene(v,w,h)}<rect x="0" y="0" width="${w}" height="${portrait?230:175}" fill="${p[0]}" opacity=".82"/><text x="${w*.07}" y="${portrait?38:28}" font-family="Arial,sans-serif" fill="${p[1]}" font-size="${portrait?12:11}" letter-spacing="3">${esc(v.category.toUpperCase())}</text>${lines.slice(0,portrait?4:3).map((l,i)=>`<text x="${w*.07}" y="${titleY+i*(fs+8)}" font-family="Arial,sans-serif" font-weight="800" fill="${p[2]}" font-size="${fs}" letter-spacing="-.7">${esc(l)}</text>`).join('')}<text x="${w*.07}" y="${h*.94}" font-family="Arial,sans-serif" fill="${p[1]}" font-size="${portrait?12:14}" letter-spacing="3">${portrait?'SHORTS / YouTrube':'СМОТРИ. ДУМАЙ. ОТКРЫВАЙ.'}</text></svg>`)};
// FORMAT-AWARE UI / preserve the original routes and shared controls.
function shortCard(v){const c=channelBy(v.channelId);return `<article class="short-card" data-short="${v.id}"><a class="short-thumb" href="#/shorts/${v.id}" aria-label="Shorts: ${esc(v.title)}"><img src="${esc(thumbnail(v))}" alt="" loading="lazy"><span class="short-type-badge">Shorts</span><span class="duration">${formatDuration(v.duration)}</span></a><div class="short-card-info"><div class="short-card-copy"><a class="card-title" href="#/shorts/${v.id}">${esc(v.title)}</a><div class="card-meta"><span data-views="${v.id}">${formatViews(v.views)}</span> · <a href="#/channel/${c.id}">${esc(c.name)}</a></div></div>${ib('video-menu','Действия с Shorts','more',`data-id="${v.id}" class="icon-btn card-more"`)}</div></article>`}
function shortsSection(vs,title='Shorts'){if(!vs.length)return '';return `<section class="shorts-section"><div class="shorts-section-head"><h2 class="shorts-title">${icon('shorts')}${esc(title)}</h2>${link('shorts','Смотреть все','play','btn outline')}</div><div class="shorts-rail">${vs.slice(0,10).map(shortCard).join('')}</div></section>`}
const baseHome=home;
home=function(){const vs=recommendations(),shorts=shortRecommendations(null,activeCategory);const chips=`<div class="chips" aria-label="Категории">${['Все',...CATEGORIES].map(c=>`<button class="chip${activeCategory===c?' active':''}" data-action="category" data-category="${esc(c)}" aria-pressed="${activeCategory===c}">${esc(c)}</button>`).join('')}</div>`;return chips+grid(vs.slice(0,6),'Нет рекомендаций','home')+shortsSection(shorts)+ (vs.length>6?grid(vs.slice(6)): '')};
channelPage=function(c){if(!c)return unavailable('Канал не найден');const own=c.id==='me',all=state.videos.filter(v=>v.channelId===c.id&&!v.archived&&(own||v.visibility==='public')).sort((a,b)=>b.publishedAt-a.publishedAt),videos=all.filter(v=>!isShort(v)),shorts=all.filter(isShort),banner=safeImage(c.banner)||art({seed:c.seed,artText:c.name,artSubtitle:c.handle,category:c.niche},true);const heading=`<img class="channel-banner" src="${esc(banner)}" alt="Шапка канала ${esc(c.name)}"><div class="channel-head">${avatar(c,'large')}<div class="channel-copy"><h1>${esc(c.name)}</h1><div class="muted">${esc(c.handle)} · <span data-subs="${c.id}">${formatSubscribers(c.subscribers)}</span> · ${videos.length} видео · ${shorts.length} Shorts</div><p class="muted">${esc(c.description.slice(0,150))}${c.description.length>150?'…':''}</p><div class="row wrap">${own?link('studio/customization','Настроить канал','edit')+link('studio/content','Управление контентом','content'):subscribeButton(c)}</div></div></div><div class="tabs" role="tablist">${[['home','Главная'],['videos','Видео'],['shorts','Shorts'],['about','О канале']].map(([id,t])=>`<button class="tab${channelTab===id?' active':''}" role="tab" aria-selected="${channelTab===id}" data-action="channel-tab" data-tab="${id}">${t}</button>`).join('')}</div>`;let body;if(channelTab==='about')body=`<div class="panel about-panel"><h2>О канале</h2><p>${esc(c.description)}</p><hr class="divider"><div class="metric-list">${[['Адрес канала',c.handle],['Дата создания',date(c.createdAt)],['Всего просмотров',exact(c.totalViews)],['Публикации',all.length]].map(([a,b])=>`<div class="metric-line"><span>${a}</span><strong>${esc(b)}</strong></div>`).join('')}</div></div>`;else if(channelTab==='shorts')body=shorts.length?`<div class="short-grid">${shorts.map(shortCard).join('')}</div>`:empty('Пока нет Shorts','Короткая история может стать началом большого разговора.',own?btn('create-short','Создать Shorts','shorts','primary'):link('shorts','Открыть Shorts','shorts'));else body=(channelTab==='home'&&!videos.length&&shorts.length?'':grid(channelTab==='home'?videos.slice(0,9):videos,'Пока здесь тихо',own?'create':'home'))+(channelTab==='home'?shortsSection(shorts):'');return heading+body};
const baseSearch=searchPage;
searchPage=function(q){const html=baseSearch(q),holder=document.createElement('div');holder.innerHTML=html;const cards=$$('.short-card',holder);if(!cards.length)return html;const shortHtml=cards.map(c=>c.outerHTML).join('');cards.forEach(c=>c.remove());return holder.innerHTML+`<section class="search-short-block"><h2 class="shorts-title">${icon('shorts')}Shorts</h2><div class="short-grid" style="margin-top:18px">${shortHtml}</div></section>`};
const baseSubscriptions=subscriptions;
subscriptions=function(){return baseSubscriptions()+shortsSection(state.videos.filter(v=>isShort(v)&&!v.archived&&v.visibility==='public'&&state.subscriptions.includes(v.channelId)).sort((a,b)=>b.publishedAt-a.publishedAt),'Shorts из подписок')};
const baseVideoModal=videoModal;
videoModal=function(v=null){baseVideoModal(v);applyPublicationFormat()};
function applyPublicationFormat(){const short=videoDraft.type==='short',preview=$('#thumbnail-preview');if(!preview)return;preview.classList.toggle('portrait',short);$('#format-hint').textContent=short?'Вертикальная история · до 3 минут':'Горизонтальное видео';$$('[data-action=publish-type]').forEach(b=>b.classList.toggle('primary',b.dataset.type===videoDraft.type));const copy=$('.upload-tile .muted',preview);if(copy)copy.textContent='Изображение в формате '+(short?'9:16':'16:9');const duration=$('#video-duration');duration.setAttribute('aria-description',short?'Shorts — не более 3 минут':'Длительность видео')}
actions['publish-type']=async function(b){if(!videoDraft||videoDraft.id)return;const type=b.dataset.type;if(type===videoDraft.type)return;videoDraft.type=type;const duration=$('#video-duration');if(type==='short'&&parseDuration(duration.value)>180)duration.value='0:45';else if(type==='video'&&duration.value==='0:45')duration.value='10:00';applyPublicationFormat();if(videoDraft.originalThumbnail){videoDraft.pending++;try{const image=await optimizeImage(videoDraft.originalThumbnail,type==='short'?'short':'thumbnail');videoDraft.thumbnail=await ImageStore.put(image);$('#thumbnail-preview').innerHTML=`<img src="${esc(image)}" alt="Превью публикации">`}catch(e){toast(e.message)}finally{videoDraft.pending--}}};
actions['create-short']=function(){videoModal();actions['publish-type']({dataset:{type:'short'}})};
// CHANNEL ANALYTICS: combined totals, accurate CTR, separate subscriber total and gain.
function analyticsVideos(){const filter=readRoute().query.get('type')||'all';return mine().filter(v=>filter==='all'||v.type===(filter==='shorts'?'short':'video'))}
aggregate=function(vs,days=period){const out={views:0,watchSeconds:0,subscribersGained:0,impressions:0,likes:0,dislikes:0,comments:0,shownInFeed:0,viewedExposures:0,swipedAway:0,rewatches:0},cutoff=days===0?0:state.simulation.now-days*864e5;let ordinaryViews=0;for(const v of vs){if(days===0){for(const k of Object.keys(out))out[k]+=(k in (v.shortStats||{})?v.shortStats[k]:v[k])||0;if(!isShort(v))ordinaryViews+=v.views}else for(const h of v.history.filter(h=>h.timestamp+3600e3>=cutoff)){for(const k of Object.keys(out))out[k]+=h[k]||0;if(!isShort(v))ordinaryViews+=h.views||0}}out.ctr=out.impressions?ordinaryViews/out.impressions:0;out.viewedRate=out.viewedExposures+out.swipedAway?out.viewedExposures/(out.viewedExposures+out.swipedAway):0;out.retention=out.views?vs.reduce((n,v)=>n+v.watchSeconds,0)/Math.max(1,vs.reduce((n,v)=>n+v.views*v.duration,0)):0;return out};
const baseStatCards=statCards;
statCards=function(stats,video=false){if(!isShort(analyticsFocus)&&readRoute().query.get('type')!=='shorts')return baseStatCards(stats,video).replace('Показы</label>','Показы видео</label>').replace('CTR значков</label>','CTR значков видео</label>');const values=[['Просмотры',formatNumber(stats.views),'views'],['Время просмотра',(stats.watchSeconds/3600).toLocaleString('ru-RU',{maximumFractionDigits:1})+' ч','watchSeconds'],['Новые подписчики','+'+formatNumber(stats.subscribersGained),'subscribersGained'],['Показано в ленте',formatNumber(stats.shownInFeed),'shownInFeed'],['Продолжили смотреть',pct(stats.viewedRate),'viewedRate']];return `<div class="stat-grid">${values.map(([label,value,key])=>`<button class="stat-card" data-action="${key==='viewedRate'?'shorts-explain':'chart-metric'}" data-metric="${key}" aria-label="${key==='viewedRate'?'Как рассчитывается доля просмотров':'График: '+label}" aria-pressed="${chartMetric===key}"${key===chartMetric?' style="border-color:var(--chart)"':''}><label>${label}</label><div class="stat-value" data-stat="${key}">${value}</div><small>${period===0?'За всё время':'За выбранный период'}</small></button>`).join('')}</div>`};
const baseAnalytics=analytics;
analytics=function(v=null){analyticsFocus=v;if(chartMetric==='shownInFeed'&&!isShort(v)&&readRoute().query.get('type')!=='shorts')chartMetric='views';const html=baseAnalytics(v);const prefix=v?'':`<div class="subscriber-total"><span>Всего подписчиков<br><small>Текущее число на всём канале</small></span><strong data-total-subs>${exact(channelBy('me').subscribers)}</strong></div>`;const filter=v?'':`<div class="format-filter" style="margin-bottom:18px"><label for="analytics-type" class="muted tiny">Формат контента</label><select id="analytics-type" class="select"><option value="all"${!readRoute().query.get('type')||readRoute().query.get('type')==='all'?' selected':''}>Весь контент</option><option value="video"${readRoute().query.get('type')==='video'?' selected':''}>Видео</option><option value="shorts"${readRoute().query.get('type')==='shorts'?' selected':''}>Shorts</option></select></div>`;return html.replace('<div class="stat-grid">',prefix+filter+'<div class="stat-grid">')};
const baseAnalyticsBottom=analyticsBottom;
analyticsBottom=function(vs,v){if(!isShort(v))return baseAnalyticsBottom(vs,v);const s=v.shortStats,resolved=s.viewedExposures+s.swipedAway,viewed=resolved?s.viewedExposures/resolved:0,swiped=resolved?s.swipedAway/resolved:0,average=v.views?v.watchSeconds/v.views:0;return `<div class="below-analytics" id="analytics-bottom"><div class="panel"><h3>Смотрели или пролистали</h3><p class="panel-subheading">За всё время · ${exact(s.shownInFeed)} показов в ленте</p><div class="ratio-bar" role="img" aria-label="${pct(viewed)} смотрели, ${pct(swiped)} пролистали"><div class="ratio-viewed" style="width:${viewed*100}%"></div><div class="ratio-swiped" style="width:${swiped*100}%"></div></div><div class="ratio-legend"><div><strong>${pct(viewed)}</strong>Продолжили смотреть</div><div><strong>${pct(swiped)}</strong>Пролистали</div></div><div class="metric-list"><div class="metric-line"><span>Средняя длительность</span><strong>${formatDuration(average)}</strong></div><div class="metric-line"><span>Средний процент просмотра</span><strong class="${average>v.duration?'retention-over':''}">${(average/v.duration*100).toLocaleString('ru-RU',{maximumFractionDigits:1})} %</strong></div><div class="metric-line"><span>Повторные просмотры</span><strong>${exact(s.rewatches)}</strong></div><div class="metric-line"><span>Время просмотра</span><strong>${(v.watchSeconds/3600).toLocaleString('ru-RU',{maximumFractionDigits:1})} ч</strong></div></div></div><div class="panel"><h3>Вовлечение аудитории</h3><p class="panel-subheading">За всё время</p><div class="metric-list">${[['Просмотры',exact(v.views)],['Нравится',exact(v.likes)],['Не нравится',exact(v.dislikes)],['Комментарии',exact(v.comments+v.localComments.length)],['Новые подписчики','+'+exact(v.subscribersGained)],['Показано в ленте',exact(s.shownInFeed)],['Длительность Shorts',formatDuration(v.duration)]].map(([k,n])=>`<div class="metric-line"><span>${k}</span><strong>${n}</strong></div>`).join('')}</div></div>${traffic(vs)}</div>`};
const baseTraffic=traffic;
traffic=function(vs){return baseTraffic(vs)};
const baseUpdateLive=updateLive;
updateLive=function(){baseUpdateLive();$$('[data-total-subs]').forEach(el=>el.textContent=exact(channelBy('me').subscribers));if(isShort(analyticsFocus)&&state.currentRoute.startsWith('studio/video/')){const v=analyticsFocus,s=aggregate([v]);$$('[data-stat]').forEach(el=>{const k=el.dataset.stat;if(k==='shownInFeed')el.textContent=formatNumber(aggregate([v]).shownInFeed);if(k==='viewedRate')el.textContent=pct(s.viewedRate)})}};
actions['shorts-explain']=()=>openModal('Просмотр или пролистывание',`<p class="readable">Доля зрителей, которые продолжили смотреть, рассчитывается из показов в ленте. Повторные просмотры могут увеличивать число просмотров и среднюю длительность, но не увеличивают число новых показов.</p>`,btn('close-modal','Понятно','','primary'),true);
document.addEventListener('change',e=>{if(e.target.id==='analytics-type'){chartMetric='views';location.hash='/studio/analytics'+(e.target.value==='all'?'':'?type='+e.target.value)}});
// VERTICAL VIEWER / scroll-snap with a bounded DOM window.
let shortsObserver=null,shortsCatalog=[],shortsWindow={start:0,end:0},shortPlayback={id:null,time:0,elapsed:0,playing:true,viewed:false,lastTick:0,loop:0};
function shortFrame(v,index){const c=channelBy(v.channelId),reaction=state.user.reactions[v.id];return `<article class="shorts-item" data-short-id="${v.id}" data-index="${index}" aria-label="Shorts: ${esc(v.title)}"><div class="short-stage"><img src="${esc(thumbnail(v))}" alt="${esc(v.title)}" loading="${index===0?'eager':'lazy'}">${ib('short-play','Пауза Shorts','pause','class="icon-btn short-toggle"')}<span class="short-position">${index+1} / ${shortsCatalog.length}</span><div class="short-footer"><div class="short-channel row"><a href="#/channel/${c.id}" aria-label="Канал ${esc(c.name)}">${avatar(c,'small')}</a><a href="#/channel/${c.id}">${esc(c.handle)}</a>${subscribeButton(c)}</div><h2>${esc(v.title)}</h2><button class="text-btn" data-action="short-description" data-id="${v.id}">Описание · <span data-views="${v.id}">${formatViews(v.views)}</span></button></div><div class="short-actions"><div class="short-action"><button data-action="reaction" data-id="${v.id}" data-reaction="like" aria-label="Нравится" aria-pressed="${reaction==='like'}">${icon('like')}</button><span data-likes="${v.id}">${formatNumber(v.likes)}</span></div><div class="short-action"><button data-action="reaction" data-id="${v.id}" data-reaction="dislike" aria-label="Не нравится" aria-pressed="${reaction==='dislike'}">${icon('dislike')}</button><span>Не нравится</span></div><div class="short-action"><button data-action="short-comments" data-id="${v.id}" aria-label="Комментарии">${icon('comments')}</button><span data-comments="${v.id}">${exact(v.comments+v.localComments.length)}</span></div><div class="short-action"><button data-action="share" data-id="${v.id}" aria-label="Поделиться">${icon('share')}</button><span>Поделиться</span></div><div class="short-action"><button data-action="video-menu" data-id="${v.id}" aria-label="Ещё">${icon('more')}</button></div></div><div class="short-progress"><span></span></div></div></article>`}
function shortsPage(id=''){const target=id?videoBy(id):null;if(id&&(!target||!isShort(target)||(target.visibility==='private'&&target.channelId!=='me')))return unavailable('Shorts не найден');const recs=shortRecommendations(target?.id);shortsCatalog=[...(target?[target]:[]),...recs].map(v=>v.id);shortsWindow={start:0,end:Math.min(12,shortsCatalog.length)};if(!shortsCatalog.length)return empty('Пока нет Shorts','Опубликуйте вертикальную историю или сбросьте скрытые рекомендации.',btn('create-short','Создать Shorts','shorts','primary'));return `<div class="shorts-feed" id="shorts-feed" tabindex="0" aria-label="Лента Shorts">${shortsCatalog.slice(0,12).map((id,i)=>shortFrame(videoBy(id),i)).join('')}</div><div class="short-nav">${ib('short-prev','Предыдущий Shorts','back','class="icon-btn up"')}${ib('short-next','Следующий Shorts','back','class="icon-btn down"')}</div>`}
function finishShort(){const v=videoBy(shortPlayback.id);if(v&&!shortPlayback.viewed&&shortPlayback.elapsed>0){v.shortStats.swipedAway++;interest(v,-.035);if(v.channelId==='me')historyAdd(v,state.simulation.now,{swipedAway:1});saveState()}shortPlayback.id=null}
function stopShorts(){if(shortsObserver){shortsObserver.disconnect();shortsObserver=null}finishShort()}
function mountShorts(){const feed=$('#shorts-feed');if(!feed)return;shortsObserver=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting&&e.intersectionRatio>.62).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)activateShort(visible.target.dataset.shortId)},{root:feed,threshold:[.1,.65,.9]});$$('.shorts-item',feed).forEach(el=>shortsObserver.observe(el));feed.addEventListener('scroll',()=>{const active=$('.shorts-item[data-short-id="'+shortPlayback.id+'"]');if(active&&Number(active.dataset.index)>=shortsWindow.end-3)extendShortWindow()},{passive:true});activateShort(shortsCatalog[0])}
function activateShort(id){if(shortPlayback.id===id)return;finishShort();const v=videoBy(id);if(!v)return;shortPlayback={id,time:0,elapsed:0,playing:true,viewed:false,lastTick:performance.now(),loop:0};v.shortStats.shownInFeed++;state.user.shortHistory=[{videoId:id,timestamp:state.simulation.now},...state.user.shortHistory.filter(x=>x.videoId!==id)].slice(0,200);state.history=[{videoId:id,timestamp:state.simulation.now},...state.history.filter(x=>x.videoId!==id)].slice(0,CONFIG.historyLimit);if(v.channelId==='me')historyAdd(v,state.simulation.now,{shownInFeed:1});if(location.hash!=='#/shorts/'+id)history.replaceState(null,'','#/shorts/'+id);state.currentRoute='shorts/'+id;saveState();updateShortControls();updateLive()}
function extendShortWindow(){const feed=$('#shorts-feed');if(!feed||shortsWindow.end>=shortsCatalog.length)return;const start=shortsWindow.end,end=Math.min(start+6,shortsCatalog.length);for(let i=start;i<end;i++){feed.insertAdjacentHTML('beforeend',shortFrame(videoBy(shortsCatalog[i]),i));shortsObserver?.observe(feed.lastElementChild)}shortsWindow.end=end;if(end-shortsWindow.start>18){const elements=$$('.shorts-item',feed).slice(0,6),height=elements.reduce((n,e)=>n+e.getBoundingClientRect().height,0);for(const e of elements){shortsObserver?.unobserve(e);e.remove()}shortsWindow.start+=6;feed.scrollTop-=height}}
function shortStep(direction){const feed=$('#shorts-feed');if(!feed)return;let index=shortsCatalog.indexOf(shortPlayback.id)+direction;while(index>=0&&index<shortsCatalog.length){const v=videoBy(shortsCatalog[index]);if(v&&!state.user.blockedChannels.includes(v.channelId)&&!state.user.notInterested.includes(v.id))break;index+=direction}if(index<0){toast('Вы в начале ленты');return}if(index>=shortsCatalog.length){toast('Вы посмотрели подборку. Откройте Shorts снова для новых рекомендаций.');return}let el=$('.shorts-item[data-index="'+index+'"]',feed);if(!el){shortsObserver?.disconnect();const start=Math.max(0,index-3),end=Math.min(shortsCatalog.length,start+12);feed.innerHTML=shortsCatalog.slice(start,end).map((id,i)=>shortFrame(videoBy(id),i+start)).join('');shortsWindow={start,end};$$('.shorts-item',feed).forEach(e=>shortsObserver?.observe(e));el=$('.shorts-item[data-index="'+index+'"]',feed)}el?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'})}
function updateShortControls(){const frame=$('.shorts-item[data-short-id="'+shortPlayback.id+'"]');if(!frame)return;const button=$('[data-action=short-play]',frame);button.innerHTML=icon(shortPlayback.playing?'pause':'play');button.setAttribute('aria-label',shortPlayback.playing?'Пауза Shorts':'Воспроизвести Shorts');const progress=$('.short-progress span',frame),v=videoBy(shortPlayback.id);if(v&&progress)progress.style.width=(shortPlayback.time/v.duration*100)+'%'}
setInterval(()=>{if(!shortPlayback.id||!shortPlayback.playing||document.visibilityState==='hidden'||$('.modal'))return;const now=performance.now(),dt=Math.min(1,(now-shortPlayback.lastTick)/1000);shortPlayback.lastTick=now;const v=videoBy(shortPlayback.id);if(!v)return;shortPlayback.time+=dt;shortPlayback.elapsed+=dt;let watch=0,views=0,viewed=0,rewatches=0;if(!shortPlayback.viewed&&shortPlayback.elapsed>=Math.min(2,v.duration)){shortPlayback.viewed=true;v.views++;v.shortStats.viewedExposures++;views=1;viewed=1;watch=shortPlayback.elapsed;interest(v,.045)}else if(shortPlayback.viewed)watch=dt;v.watchSeconds+=watch;if(views)v.traffic[6]+=views;if(shortPlayback.time>=v.duration){if(state.preferences.shortAutoplay){shortStep(1);shortPlayback.playing=false}else{shortPlayback.time=0;shortPlayback.loop++;v.views++;v.shortStats.rewatches++;v.traffic[6]++;views++;rewatches++}}if(v.channelId==='me'&&(watch||views||viewed))historyAdd(v,state.simulation.now,{views,watchSeconds:watch,viewedExposures:viewed,rewatches});if(views){syncChannelTotals();saveState();updateLive()}updateShortControls()},250);
actions['short-play']=()=>{shortPlayback.playing=!shortPlayback.playing;shortPlayback.lastTick=performance.now();updateShortControls()};actions['short-prev']=()=>shortStep(-1);actions['short-next']=()=>shortStep(1);
actions['short-description']=b=>{const v=videoBy(b.dataset.id);if(!v)return;openModal(v.title,`<p class="muted tiny" style="margin-bottom:16px">${formatViews(v.views)} · ${date(v.publishedAt)} · ${formatDuration(v.duration)}</p><p class="short-desc">${esc(v.description||'Автор не добавил описание.')}</p><p class="muted tiny" style="margin-top:16px">${v.tags.map(t=>'#'+esc(t)).join(' ')}</p>`,btn('close-modal','Закрыть','','outline'),true)};
function showShortComments(v){openModal('Комментарии · '+exact(v.comments+v.localComments.length),`<div class="short-comments"><p class="muted tiny">${esc(v.title)}</p><form class="comment-form" id="short-comment-form" data-id="${v.id}">${avatar(channelBy('me'),'small')}<input name="comment" aria-label="Комментарий Shorts" placeholder="Напишите комментарий" maxlength="1000" required><button type="submit" class="btn">${icon('share')}Отправить</button></form>${v.localComments.map(x=>`<div class="comment">${avatar(channelBy('me'),'small')}<div><strong class="tiny">${esc(x.author)}</strong><p>${esc(x.text)}</p></div></div>`).join('')}<p class="tiny muted">Аудитория оставила ${exact(v.comments)} комментариев.</p></div>`,btn('close-modal','Закрыть','','outline'),true)}
actions['short-comments']=b=>{const v=videoBy(b.dataset.id);if(v)showShortComments(v)};
document.addEventListener('submit',e=>{if(e.target.id!=='short-comment-form')return;e.preventDefault();const v=videoBy(e.target.dataset.id),text=e.target.comment.value.trim();if(v&&text){v.localComments.unshift({id:uid('comment'),text,author:channelBy('me').name,at:state.simulation.now});v.localComments=v.localComments.slice(0,100);saveState();showShortComments(v);updateLive();toast('Комментарий добавлен')}});
document.addEventListener('keydown',e=>{if(!state?.currentRoute.startsWith('shorts')||$('.modal')||$('.dropdown')||(e.key===' '&&/BUTTON|A/.test(e.target.tagName))||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(['ArrowDown','PageDown','ArrowUp','PageUp',' '].includes(e.key)){e.preventDefault();if(e.key===' ')actions['short-play']();else shortStep(e.key==='ArrowDown'||e.key==='PageDown'?1:-1)}});
const baseNotInterested=actions['not-interested'],baseBlockChannel=actions['block-channel'];actions['not-interested']=b=>{baseNotInterested(b);if(state.currentRoute.startsWith('shorts'))shortStep(1)};actions['block-channel']=b=>{baseBlockChannel(b);if(state.currentRoute.startsWith('shorts'))shortStep(1)};
const baseSettings=settings;settings=function(){const html=baseSettings();return html.replace('<div class="settings-row"><div><strong>Рекомендации',`<div class="settings-row"><div><strong>Автопереход Shorts</strong><p>После окончания автоматически открывать следующую короткую историю.</p></div><select id="short-autoplay" class="select" aria-label="Автопереход Shorts"><option value="off"${!state.preferences.shortAutoplay?' selected':''}>Выключен</option><option value="on"${state.preferences.shortAutoplay?' selected':''}>Включён</option></select></div><div class="settings-row"><div><strong>Рекомендации`).replace('Настройки, метаданные и небольшие структуры','Настройки, метаданные и небольшие структуры').replace('Данных ·','данных ·').replace('Сохранено локально',ImageStore.available?'Изображения в IndexedDB':'Резервный режим')};
document.addEventListener('change',e=>{if(e.target.id==='short-autoplay'){state.preferences.shortAutoplay=e.target.value==='on';saveState()}});
const baseDeleteVideo=deleteVideo;deleteVideo=function(id){baseDeleteVideo(id);ImageStore.collect()};
const basePhase=phase;phase=function(v,t=state.simulation.now){if(!isShort(v))return basePhase(v,t);const age=(t-v.publishedAt)/3600e3;return age<1?'Тестовая аудитория':age<12?'Расширение ленты':age<36?'Пик интереса':age<150?'Следующие волны':'Долгий хвост'};

function fastForwardNPCSchedules(now){for(const c of state.channels)if(c.id!=='me'&&c.nextUploadAt<=now)c.nextUploadAt=now+(0.3+seeded(c.seed,'catchup'+Math.floor(now/864e5)))*864e5/Math.max(1,c.uploadFrequency)}
const baseAvatar=avatar;avatar=function(c,cls=''){return baseAvatar({...c,avatar:safeImage(c.avatar)||null},cls)};
