from pathlib import Path
import json,hashlib
root=Path(__file__).parent.parent
names={'creator_moscow':'v5-results.json','creator_new_york':'v5-results-new-york.json','creator_kathmandu':'v5-results-kathmandu.json','images_and_restore':'v5-assets-results.json','v4_regression':'v5-regression-v4.json','v3_regression':'v5-regression-v3-final.json','calendar_moscow':'v5-calendar-moscow.json','calendar_new_york':'v5-calendar-new-york.json','calendar_kathmandu':'v5-calendar-kathmandu.json'}
suites={k:json.loads((root/'work'/v).read_text()) for k,v in names.items()}
def labels(d):
 yield from d.get('results',[])
 for x in d.get('suites',[]): yield from labels(x)
all_labels=[label for d in suites.values() for label in labels(d)]
browser=[
'Existing v4 channel, three publications and community poll/image remain after migration',
'Studio monetization navigation and pre-qualification disabled application appear',
'Create a public playlist through the form',
'Add an ordinary video through the video menu',
'Add a Short to the same playlist through its menu',
'Channel playlist tab shows correct card and count',
'Channel home exposes the compact public-playlist section',
'Reorder mixed entries with accessible arrow buttons',
'Edit playlist title and description is retained',
'Upload and optimize a custom playlist cover through the file chooser',
'Reload preserves title, order, cover and entries',
'Play all opens the existing Shorts player with playlist context',
'Next opens the ordinary player and previous returns to Shorts',
'Playlist auto and repeat preferences survive navigation',
'Actual timed playback automatically follows Short, own video and foreign video',
'End of sequence stops without repeat',
'Repeat returns from the last entry to the first Short',
'375px playlist layout has no page-level horizontal overflow',
'Mobile playlist arrow controls and all three entries remain visible',
'Financial fixture generated by the real engine imports successfully',
'Active dashboard renders seven income/RPM/CPM/format cards',
'Changing the period updates graph and selected-period totals',
'Individual Shorts analytics exposes pool allocation, engaged views and no video CPM',
'Shorts Feed toggle persists Off after reload and can be re-enabled',
'Studio Content displays monetization status badges',
'Finalized months and simulated payout journal are visible and distinct from estimated month',
'Shorts model details display finite country pools and current allocation shares',
'375px revenue layout and internally scrollable tables have no page-level horizontal overflow',
'Dark theme renders the revenue interface and remains responsive',
'Import restores the prior test channel, community and custom-cover playlist',
'1200px desktop and 375px mobile sizes were checked; viewport reset after QA',
'Browser console contains no warning or error on the verified final pages'
]
html=root/'outputs/index.html';sha=hashlib.sha256(html.read_bytes()).hexdigest()
report={'version':'YouTrube 5.0','date':'2026-10-10','artifact':'index.html','sha256':sha,'bytes':html.stat().st_size,'javascriptSyntax':'passed','uniqueAutomatedAssertions':len(set(all_labels)),'successfulAssertionExecutions':len(all_labels),'browserChecks':browser,'browserCheckCount':len(browser),'testOrigins':{'isolated':'http://127.0.0.1:8766','originalOriginUntouched':'http://127.0.0.1:8765'},'fixtures':'Synthetic test data only; prior test-channel backup restored after financial QA.','suites':suites}
(root/'outputs/test-results-v5.json').write_text(json.dumps(report,ensure_ascii=False,indent=2))
bench=next(s['benchmarks'] for s in suites['v3_regression']['suites'] if 'benchmarks' in s)
body='''# YouTrube 5.0 — отчёт об обновлении

Готовый автономный файл: [index.html](@ROOT@/outputs/index.html). Проект продолжает версии 3.1 и 4.0, дизайн и существующий движок сохранены. Весь рабочий код находится в одном HTML; сервер, аккаунты и внешние зависимости для приложения не нужны.

## Как обновить

Замените прежний `index.html` новым файлом и обновите страницу по прежнему адресу, в том же браузере. Данные сохраняются в существующих localStorage и IndexedDB. При переносе на другой домен, порт или в другой браузер используйте «Настройки → Экспорт / Импорт»: данные не встроены в сам HTML.

Плейлисты доступны в основной навигации и во вкладке канала. Монетизация находится в YouTrube Studio.

## Плейлисты

- Создание и редактирование названия, описания, видимости и обложки; открытый доступ, доступ по ссылке и приватный режим.
- Обложка первого доступного видео либо загруженное изображение, оптимизированное существующим механизмом и сохранённое в IndexedDB.
- Сохранение обычных видео, Shorts и чужих публикаций в несколько подборок через меню видео. Хранятся только ID, повторы запрещены, владельцы публикаций сохраняются.
- Страница `#/playlist/:id`: автор, дата обновления, количество и длительность доступных публикаций, список роликов, кнопка «Воспроизвести все».
- Смешанная последовательность через существующие плееры; предыдущая/следующая публикация, позиция, отдельные настройки автоперехода и повтора. Автопереход изначально выключен. Контекст подборки сохраняется в адресе при активации Shorts.
- Перетаскивание на компьютере, кнопки ↑ ↓ на телефоне, удаление записи и самой подборки без удаления видео. Недоступные записи обозначены и пропускаются при воспроизведении.
- Карточки во вкладке канала и компактная подборка открытых плейлистов на его главной. Чужие закрытые подборки недоступны, чужие подборки по ссылке исключены из публичного обнаружения.
- Ограничения объёма: до 100 собственных подборок и 500 записей в каждой.

## Виртуальная монетизация

Условия вынесены в `EARN_CONFIG`: 1 000 подписчиков и 4 000 квалифицированных часов обычных публичных видео за 365 календарных дней **или** 10 млн заинтересованных просмотров публичных Shorts Feed за 90 дней. Повторы Shorts, источники за пределами Feed, приватные, удалённые и доступные по ссылке публикации исключены из соответствующей квалификации. Часы Shorts не прибавляются к часам обычных видео.

Заявка занимает минимум 10 реальных минут. Проверка детерминирована: условия проверяются повторно, отказ сопровождается причиной. Ускоритель статистики не ускоряет часы заявки. При офлайн-обработке существующий шаг симуляции делится в момент проверки: просмотры до подключения остаются без дохода.

Сохранены дата подключения, базовые счётчики и обработанные приросты. Доход рассчитывается из новых событий существующего журнала просмотров. Повторная загрузка, повторный вызов обработчика и импорт того же сохранения не создают повторного начисления. Пауза потребляет прошедший интервал без просмотров и денег.

**Обычные видео:** новые просмотры → часть воспроизведений с рекламой → рекламные показы → рекламный доход → 55% автору. География, категория, метаданные финансовой тематики, сезон, качество, длительность и рекламные форматы меняют результат. Длинные ролики могут получить дополнительные показы. В этой упрощённой модели чистый рекламный доход равен валовому: дополнительных вычетов нет. Доля автора применяется один раз.

**Shorts:** подходящие заинтересованные просмотры Feed распределяются по географии. Каждый месяц в каждой географии есть конечный виртуальный Creator Pool и фоновая аудитория. Каналу выделяется прирост его доли пула; автор получает 45% выделенного. Перераспределение не может превысить размер пула. Дробление одного прироста на несколько событий сохраняет суммарный результат. Повторы увеличивают общие просмотры, но не заинтересованные просмотры для пула. CPM и рекламные показы отдельного Shorts не имитируются. В пояснении модели показаны размеры пулов, доли и выделенные суммы текущего месяца.

**RPM** в интерфейсе модели — доход автора на 1 000 всех новых просмотров после подключения, включая просмотры с выключенной монетизацией. **CPM** обычных видео — рекламный доход на 1 000 рекламных показов до доли автора. Общие просмотры, воспроизведения с рекламой, рекламные показы, доход до распределения, выделение из пула и доход автора хранятся раздельно.

Включение и выключение доступно отдельно для каждого видео. Для Shorts это участие в Shorts Feed. Выключение, смена видимости и удаление не стирают уже заработанные суммы. Пригодность определяется консервативно по явно предоставленным метаданным; жанр фильма, отсутствие сведений и случайность не создают нарушений. Изображение и звук не проверяются.

## Аналитика и расчётные периоды

- Studio: доход за 7/28 дней и всё время, RPM, CPM, обычные видео и Shorts; периоды 7/28/90 дней и всё время, график и таблица публикаций.
- Индивидуальная аналитика: доход, RPM, новые просмотры, воспроизведения с рекламой и показы для обычного видео; выделение из пула и заинтересованные Feed-просмотры для Shorts. Статус отображается также в Studio Content.
- Данные относятся к реальному местному календарю. Дневной журнал хранит последние 400 дней; более ранние значения переходят в накопительный архив без потери денег. График всего канала за большой срок использует месяцы и архив; индивидуальный график сохраняет старый итог отдельной архивной точкой.
- Текущий месяц — estimated revenue. Закрытие завершённого месяца — 7-го числа следующего месяца. Finalized revenue считается отдельно. При доступном закрытом балансе от $100 создаётся simulated payout до целых центов; текущий месяц не выплачивается. Дробные остатки сохраняются.
- Сохраняются до 120 месяцев и последних 120 записей выплат; старые суммы объединяются в архивы. Денежные расчёты сохраняют дробную точность, округление применяется при отображении и виртуальной выплате.

## Сохранность данных и границы модели

Миграция добавляет новые структуры при отсутствии. Существующие публикации, просмотры, подписчики, изображения, даты, сообщество, комментарии, уведомления, подтверждение и аналитика сохраняются. Экспорт включает обложки; импорт проверяет ссылки на изображения до замены состояния и откатывает состояние при ошибке сохранения.

Старые версии не фиксировали видимость и квалификацию в момент каждого просмотра. Поэтому их общая статистика сохранена, но не объявляется квалифицированной задним числом. Достоверный квалификационный журнал начинается с перехода на 5.0; его начало указано в интерфейсе. Исторические просмотры также не превращаются в деньги после подключения.

Все ставки, бюджеты, фоновые аудитории и USD — параметры вымышленной экономики. Модель не воспроизводит реальные ставки по странам, доступность YPP в конкретной стране, проверку видеофайлов, лицензирование музыки, AdSense или реальные переводы. Это локальный симулятор.

## Проверки

Успешно выполнено **@UNIQUE@ уникальных автоматических проверок**, **@EXECUTIONS@ выполнений утверждений** с повторением календарных сценариев в трёх часовых поясах. Дополнительно выполнены **@BROWSER@ браузерные проверки** на синтетических данных. Полные результаты: [test-results-v5.json](@ROOT@/outputs/test-results-v5.json).

| Набор | Результат |
|---|---:|
| Плейлисты и монетизация 5.0 | 108 в каждом из трёх часовых поясов |
| Изображения, экспорт, восстановление и откат | 12 |
| Регрессия сообщества, комментариев, аудитории и подтверждения 4.0 | 89 |
| Регрессия движка, аудитории, нагрузки и хранилища 3.x | 92 |
| Календарь: Москва / Нью-Йорк / Катманду | 39 / 43 / 40 |

Проверены отсутствие ретроактивного дохода, повторного офлайн-начисления и начисления при паузе; On/Off и повторное включение; разные модели, дробная точность Shorts, конечный пул и неизменность суммы при дроблении события; совпадение дневных, месячных, индивидуальных и общих итогов; закрытие месяца и идемпотентные выплаты; удаление видео с сохранением дохода; границы 90/365 дней; архивирование журналов; неверные суммы, версии, повторные ID и небезопасные обложки при импорте.

JavaScript проверен компилятором Node `vm.Script`. В браузере проверены реальные меню и формы, загрузка обложки, refresh, переходы между форматами, автоматическое завершение двухсекундных публикаций, повтор плейлиста, настройки монетизации, графики, выплаты, светлая и тёмная темы, ширина 375 и 1200 пикселей. На проверенных финальных страницах предупреждений и ошибок консоли нет.

Нагрузка на 1 000 публикаций: сутки — **@DAYMS@ мс**, 30 дней — **@MONTHMS@ мс**. Сжатое состояние нагрузочного сценария — около **29,91 МиБ**, сохраняется через существующие снимки IndexedDB. Восстановление большого интервала использует кооперативные паузы существующего загрузчика.

Браузерные тесты использовали отдельный адрес `127.0.0.1:8766`; исходный адрес `127.0.0.1:8765` не изменялся. После финансовых сценариев восстановлена прежняя тестовая копия с созданным плейлистом. Числа дохода на иллюстрациях принадлежат синтетическому тестовому каналу.

Тесты запускаются из папки `outputs` через Node без установки пакетов: `node tests-v5.cjs`, `node tests-v5-assets.cjs`, `node tests-v4.cjs`, `node tests-v3.cjs`, `node tests-calendar.cjs`. У старых тестовых заглушек DOM добавлен метод `contains`; смысловые и нагрузочные пороги сохранены.

## Основа экономической модели

Пороги и раздельная квалификация форматов сверены с [YouTube Help: YPP eligibility](https://support.google.com/youtube/answer/72851). Определения CPM/RPM — [YouTube Help: ad revenue analytics](https://support.google.com/youtube/answer/9314357). Доля обычной рекламы — [YouTube partner earnings overview](https://support.google.com/youtube/answer/72902); принцип распределения Shorts Feed и доля 45% — [YouTube Shorts monetization policies](https://support.google.com/youtube/answer/12504220). Проверено 10 октября 2026 года. В симуляторе используются заданные в запросе условия октября 2026; анонсированные будущие изменения не применяются автоматически.

## Артефакты

- [Плейлист](@ROOT@/outputs/youtrube-v5-playlist.jpg)
- [Доход и график](@ROOT@/outputs/youtrube-v5-revenue.jpg)
- [Детальный график и таблица](@ROOT@/outputs/youtrube-v5-revenue-chart.jpg)
- [Плейлист на телефоне](@ROOT@/outputs/youtrube-v5-mobile-playlist.jpg)
- [Доход на телефоне](@ROOT@/outputs/youtrube-v5-mobile-revenue.jpg)

SHA-256 итогового HTML: `@SHA@`.
'''
body=body.replace('@ROOT@',str(root)).replace('@UNIQUE@',str(len(set(all_labels)))).replace('@EXECUTIONS@',str(len(all_labels))).replace('@BROWSER@',str(len(browser))).replace('@DAYMS@',str(bench[-2]['oneDayMs'])).replace('@MONTHMS@',str(bench[-1]['offline30DaysMs'])).replace('@SHA@',sha)
(root/'outputs/README-v5.md').write_text(body)
print(json.dumps({k:report[k] for k in ['sha256','bytes','uniqueAutomatedAssertions','successfulAssertionExecutions','browserCheckCount']},indent=2))
