from pathlib import Path
p=Path('outputs/index.html');s=Path('work/index-v2-backup.html').read_text()
s=s.replace('[1,2].includes','[1,2,3].includes')
s=s.replace('/type=/.test(attrs)',r'/(?:^|\s)type\s*=/.test(attrs)')
s=s.replace('Math.max(5*60e3,ms/288)','Math.max(15*60e3,ms/144)')
s=s.replace("let state=null", "let state=null")
s=s.replace("v.history.forEach(h=>{for(const k of ['shownInFeed','viewedExposures','swipedAway','rewatches'])h[k]??=0})", "v.history.forEach(h=>{for(const k of ['shownInFeed','viewedExposures','swipedAway','rewatches'])h[k]??=0})")
s=s.replace("if(views){syncChannelTotals();saveState();updateLive()}updateShortControls()", "if(views){recordLocalShort(v,views,rewatches);syncChannelTotals();saveState();updateLive()}updateShortControls()")
s=s.replace("if(v&&!shortPlayback.viewed&&shortPlayback.elapsed>0)","if(v&&!shortPlayback.viewed)")
s=s.replace("location.hash='/studio/analytics'+(e.target.value==='all'?'':'?type='+e.target.value)", "location.hash='/studio/analytics'+(readRoute().query.get('tab')==='audience'?'?tab=audience'+(e.target.value==='all'?'':'&type='+e.target.value):(e.target.value==='all'?'':'?type='+e.target.value))")
s=s.replace('initializeShort(v,false);','if(!v.distribution)initializeShort(v,false);')
s=s.replace('// APP INIT',Path('work/audience-v3.js').read_text()+'\n'+Path('work/storage-v3.js').read_text()+'\n'+Path('work/time-v3.js').read_text()+'\n// APP INIT')
s=s.replace('</style>', '''.audience-note{font-size:12px;color:var(--text-secondary);line-height:1.7;margin:0 0 20px;max-width:950px}.audience-stat-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.audience-stat-grid .stat-card:last-child{grid-column:auto}.audience-structure{display:flex;border-radius:6px;overflow:hidden;height:22px;margin:22px 0}.audience-segment.new{background:#9a86da}.audience-segment.casual{background:#55a9b1}.audience-segment.regular{background:var(--chart)}.audience-legend{gap:20px;margin-top:10px}.audience-legend span:last-child{color:#9a86da}.analytics-tabs{margin:4px 0 22px}#audience-panel .ratio-legend{flex-wrap:wrap}#audience-panel .metric-line strong{white-space:nowrap}@media(max-width:700px){.audience-stat-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.audience-stat-grid .stat-value{font-size:24px}.audience-note{font-size:11px}}
</style>''')
s=s.replace('const s=JSON.parse(raw);','const s=unpackState(JSON.parse(raw));')
s=s.replace('async function boot(){state=loadState();','async function boot(){state=await loadStateForBoot();')
s=s.replace('if(!saveState(true))throw Error(\'Не удалось сохранить резервную копию.', 'if(!await persistState())throw Error(\'Не удалось сохранить резервную копию.')
s=s.replace('if(!saveState(true)){for(const c of state.channels)', 'if(!await persistState()){for(const c of state.channels)')
s=s.replace('const beforeViews=mine().reduce((n,v)=>n+v.views,0);settleTime();','const beforeViews=mine().reduce((n,v)=>n+v.views,0);await settleBootTime();')
s=s.replace('syncChannelTotals();routeChange();saveState(true);if(offlineViews', 'syncChannelTotals();appReady=true;routeChange();saveState(true);if(offlineViews')
s=s.replace("if(!state||document.visibilityState==='hidden')return;settleTime();", "if(!state||!appReady||document.visibilityState==='hidden')return;settleTime();")
s=s.replace("'hashchange',()=>{if(state)routeChange()", "'hashchange',()=>{if(state&&appReady)routeChange()")
s=s.replace("'visibilitychange',()=>{if(!state)return;", "'visibilitychange',()=>{if(!state||!appReady)return;")
s=s.replace("if(state){settleTime();saveState(true)}", "if(state&&appReady){settleTime();saveState(true)}")
s=s.replace("if(state&&appReady){settleTime();saveState(true)}", "if(state&&appReady){stopShorts();settleTime();saveState(true)}")
p.write_text(s)
