from pathlib import Path
p=Path('work/audience-v3.js');s=p.read_text()
s=s.replace("subscribed:{new:0,casual:subs*.35,regular:subs*.2,dormant:subs*.45}","subscribed:{new:0,casual:subs*casual,regular:subs*regular,dormant:subs*(1-casual-regular)}")
s=s.replace("repeatViews:0,reach:{}", "repeatViews:0,subscribersGained:0,births:{},reach:{}")
s=s.replace("stocks:emptyGroups()", "stocks:emptyGroups(),pools:{}")
s=s.replace("['newViewers','views','subscriberViews','repeatViews']", "['newViewers','views','subscriberViews','repeatViews','subscribersGained']")
s=s.replace("for(const [id,hits] of Object.entries(b.byFormat[f].reach))", "for(const [id,count] of Object.entries(b.byFormat[f].births||{}))a.byFormat[f].births[id]=(a.byFormat[f].births[id]||0)+count;for(const [id,hits] of Object.entries(b.byFormat[f].reach))")
s=s.replace('a.stocks=b.stocks;return a','a.stocks=b.stocks;a.pools=b.pools;return a')
s=s.replace("for(const f of ['video','short'])if(row.byFormat[f].reach[old.id]){row.byFormat[f].reach[id]=(row.byFormat[f].reach[id]||0)+row.byFormat[f].reach[old.id];delete row.byFormat[f].reach[old.id]}","{for(const f of ['video','short'])for(const k of ['reach','births'])if(row.byFormat[f][k][old.id]){row.byFormat[f][k][id]=(row.byFormat[f][k][id]||0)+row.byFormat[f][k][old.id];delete row.byFormat[f][k][old.id]}if(row.pools[old.id]){row.pools[id]=(row.pools[id]||0)+row.pools[old.id];delete row.pools[old.id]}}")
s=s.replace("const returning=Math.min(opportunities*.88,active*(1-Math.exp(-Math.max(.02,hours)*p.returnProbability/18))*(.25+fit*.75)),fresh=local?(known?0:1):Math.max(0,opportunities-returning);", "const returning=local?Math.max(0,opportunities-(p.localViewerSeen?0:Math.min(1,opportunities))):Math.min(opportunities*.88,active*(1-Math.exp(-Math.max(.02,hours)*p.returnProbability/18))*(.25+fit*.75)),fresh=local?(p.localViewerSeen?0:Math.min(1,opportunities)):Math.max(0,opportunities-returning);")
s=s.replace("const hits=returning*weight/active", "const hits=local?0:returning*weight/active")
s=s.replace("row.newViewers+=fresh;format.newViewers+=fresh", "row.newViewers+=fresh;format.newViewers+=fresh;format.births[co.id]=(format.births[co.id]||0)+fresh")
s=s.replace("subscriberViews=Math.min(views,", "if(local){p.localViewerSeen=true;const id=p.cohorts.find(co=>co.id.startsWith('local-'))?.id;if(id)format.reach[id]=(format.reach[id]||0)+returning;subscriberViews=state.subscriptions.includes(c.id)?views:0;}\n subscriberViews=Math.min(views,")
s=s.replace("format.subscriberViews+=subscriberViews;c.subscribers", "format.subscriberViews+=subscriberViews;format.subscribersGained+=subscribers;c.subscribers")
s=s.replace("row.stocks={new:totals.new", "row.pools=Object.fromEntries(p.cohorts.map(co=>[co.id,sumGroups(co.groups)]));row.stocks={new:totals.new")
s=s.replace("day.stocks={new:totals.new", "day.pools=Object.fromEntries(p.cohorts.map(co=>[co.id,sumGroups(co.groups)]));day.stocks={new:totals.new")
s=s.replace("reach={},out=", "reach={},births={},out=")
s=s.replace("out.subscribersGained+=h.subscribersGained;for(const f of formats)", "for(const f of ['video','short'])for(const [id,n] of Object.entries(h.byFormat[f].births||{}))births[id]=(births[id]||0)+n;for(const f of formats)")
s=s.replace("const x=h.byFormat[f];out.newViewers", "const x=h.byFormat[f];out.subscribersGained+=x.subscribersGained||0;out.newViewers")
s=s.replace("const pool=sumGroups(co.groups),bornInside=co.id!=='baseline'&&co.at>=cutoff,eligible=bornInside?0:pool;", "const pool=rows.at(-1)?.pools?.[co.id]??(until===state.simulation.now?sumGroups(co.groups):0),eligible=Math.max(0,pool-(births[co.id]||0));")
p.write_text(s)
