from pathlib import Path
p=Path('work/install_v3.py');s=p.read_text();needle="s=s.replace('// APP INIT'"
pos=s.index(needle)
s=s[:pos]+'''# All base UI dates and direct user events use the browser's clock.
s=s.replace('state.simulation.now','RealClock.now()')
s=s.replace('RealClock.now()=to','state.simulation.now=to').replace('RealClock.now()=end','state.simulation.now=end')
s=s.replace('timeScale:120','timeScale:1')
s=s.replace("simulation:{now,speed:1,lastSimulationTimestamp:Date.now()}","simulation:{now,speed:1,lastSimulationTimestamp:Date.now()}")
s=s.replace("if(!wasPublic&&old.visibility==='public')old.publishedAt=RealClock.now();", "")
s=s.replace("publishedAt:RealClock.now(),views:0", "publishedAt:RealClock.now(),realCreatedAt:RealClock.now(),dateStatus:'real',views:0")
s=s.replace('aria-label="Скорость времени"','aria-label="Скорость статистики"')
s=s.replace('1×: одна секунда соответствует двум минутам времени платформы. Пауза останавливает и офлайн-прогресс.','1×, 5× и 20× меняют интенсивность роста статистики. Даты и возраст публикаций идут по реальным часам. Пауза останавливает прирост, включая офлайн. За возвращение обрабатывается не более 30 реальных дней.')
s=s.replace("Math.floor(RealClock.now()/864e5)-days+1)*864e5", "0)") if False else s
s=s.replace("(Math.floor(RealClock.now()/864e5)-days+1)*864e5", "calendarCutoff(days)")
s=s.replace("h.timestamp>=cutoff)","h.timestamp>=cutoff&&h.timestamp<=RealClock.now())")
s=s.replace("new Date(points[i].t).toLocaleDateString('ru-RU',{day:'numeric',month:'short'})", "dateTimeLabel(points[i].t,points[i].hourly)")
s=s.replace("date(points[i].t)", "dateTimeLabel(points[i].t,points[i].hourly)")
''' + s[pos:]
s=s.replace("Path('work/time-v3.js').read_text()+'\\n// APP INIT'", "Path('work/time-v3.js').read_text()+'\\n'+Path('work/calendar-v3.js').read_text()+'\\n// APP INIT'")
p.write_text(s)
p=Path('work/audience-v3.js');s=p.read_text()
s=s.replace('at=Math.floor(t/DAY)*DAY','at=localDay(Math.min(t,RealClock.now()))')
s=s.replace('const hour=((t/3600e3)%24+24)%24','const dt=new Date(t),hour=dt.getHours()+dt.getMinutes()/60')
s=s.replace('hours=(to-start)/3600e3','hours=(to-start)/3600e3*(state.simulation.intensity??state.simulation.speed)')
s=s.replace('const mid=(start+to)/2;','const mid=(start+to)/2,recordAt=Math.max(start,to-1);')
s=s.replace('applyAdaptiveShort(v,exposures,response,to,hours)','applyAdaptiveShort(v,exposures,response,recordAt,hours)')
s=s.replace('views,repeats,to,hours','views,repeats,recordAt,hours')
s=s.replace('historyAdd(v,to,{views','historyAdd(v,recordAt,{views')
s=s.replace('const hours=(to-d.lastDecisionAt)/3600e3;', 'const hours=(to-d.lastDecisionAt)/3600e3*(state.simulation.intensity??state.simulation.speed);')
s=s.replace('phase=function(v,t=state.simulation.now)', 'phase=function(v,t=RealClock.now())')
s=s.replace('cutoff=days?(Math.floor(state.simulation.now/DAY)-days+1)*DAY:0','cutoff=days?calendarCutoff(days):0')
s=s.replace('h.timestamp>=cutoff)','h.timestamp>=cutoff&&h.timestamp<=RealClock.now())')
s=s.replace('historyAdd(v,state.simulation.now,','historyAdd(v,RealClock.now(),')
s=s.replace('0,state.simulation.now,','0,RealClock.now(),')
s=s.replace('known?1:0,state.simulation.now,','known?1:0,RealClock.now(),')
s=s.replace('until=state.simulation.now','until=RealClock.now()')
s=s.replace('cutoff=days?(Math.floor(until/DAY)-days+1)*DAY:p.trackingSince','cutoff=days?calendarCutoff(days,until):p.trackingSince')
s=s.replace('h.at>=Math.floor(cutoff/DAY)*DAY&&h.at<=until','localDay(h.at)>=localDay(cutoff)&&h.at<=until')
s=s.replace('cutoff=period?(Math.floor(state.simulation.now/DAY)-period+1)*DAY:p.trackingSince','cutoff=period?calendarCutoff(period):p.trackingSince')
s=s.replace('h.at>=Math.floor(cutoff/DAY)*DAY','localDay(h.at)>=localDay(cutoff)&&h.at<=RealClock.now()')
s=s.replace('...audienceMetrics(c,1,format,h.at)','...audienceMetrics(c,1,format,Math.min(RealClock.now(),nextLocalDay(h.at)-1))')
p.write_text(s)
