// One writer per browser origin. Web Locks stay held across background throttling.
// The IndexedDB fallback checks ownership atomically at every durable commit.
const SESSION_LEASE_MS=8000;
const SessionCoordinator={
 enforced:false,active:false,closing:false,mode:'none',owner:null,expectedRaw:null,db:null,releaseLock:null,renewTimer:null,epoch:0,committing:false,
 allowed(){return !this.enforced||this.active},
 interactive(){return !this.enforced||this.active&&!this.closing},
 matchesStorage(){if(!this.enforced)return true;try{return localStorage.getItem(CONFIG.key)===this.expectedRaw}catch{return false}},
 capture(){this.expectedRaw=localStorage.getItem(CONFIG.key)},
 closingHint(){try{return JSON.parse(localStorage.getItem(CONFIG.key+'.writerClosed')||'null')}catch{return null}},
 signalClose(){if(this.active&&this.mode==='lease')try{localStorage.setItem(CONFIG.key+'.writerClosed',JSON.stringify({owner:this.owner,at:RealClock.now()}))}catch{}},
 screen(conflict=false,opening=false){const root=$('#app');if(!root)return;root.innerHTML=`<main class="boot-screen" role="status"><span class="brandmark"></span><h1>${opening?'YouTrube':conflict?'Сохранение защищено':'Симулятор открыт в другой вкладке'}</h1><p class="muted readable">${opening?'Открываем ваше пространство…':conflict?'Данные изменились в другой вкладке. Здесь расчёт остановлен, чтобы сохранить ваш прогресс. Можно сохранить отдельную копию этой вкладки и открыть актуальные данные.':'Закройте другую вкладку с этим адресом. Здесь автоматически откроется последнее сохранение, и симуляция продолжится.'}</p>${conflict?'<div class="row gap8 wrap"><button type="button" class="btn outline" data-session-action="export">Экспорт этой вкладки</button><button type="button" class="btn primary" data-session-action="reload">Открыть актуальные данные</button></div>':''}</main>`},
 pause(){if(!this.enforced||!this.active)return;this.active=false;appReady=false;player.playing=false;shortPlayback.playing=false;stateSaveRevision++;clearTimeout(saveTimer);saveTimer=null;this.screen(true);void this.release()},
 check(){if(!this.allowed())return false;if(!this.matchesStorage()){this.pause();return false}return true},
 async openLeaseDB(){if(this.db)return this.db;if(!globalThis.indexedDB)throw Error('Браузер не поддерживает безопасное сохранение между вкладками.');this.db=await new Promise((resolve,reject)=>{const r=indexedDB.open('youtrube.writer',1);r.onupgradeneeded=()=>r.result.createObjectStore('locks');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.onblocked=()=>reject(Error('Хранилище вкладок заблокировано. Закройте другие вкладки симулятора.'))});this.db.onversionchange=()=>{this.pause();this.db.close();this.db=null};return this.db},
 async lease(fn){const db=await this.openLeaseDB();return new Promise((resolve,reject)=>{const tx=db.transaction('locks','readwrite'),store=tx.objectStore('locks'),r=store.get(CONFIG.key);let result=false;r.onsuccess=()=>{try{result=fn(r.result,store)}catch(error){tx.abort();reject(error)}};r.onerror=()=>reject(r.error);tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(tx.error||Error('Не удалось согласовать сохранение вкладок.'));tx.onerror=()=>reject(tx.error)})},
 async acquire(){this.enforced=true;this.active=false;this.closing=false;this.owner??=uid('writer');this.screen(false,true);const epoch=++this.epoch,waitingTimer=setTimeout(()=>{if(epoch===this.epoch&&!this.active)this.screen()},200);const locks=globalThis.navigator?.locks;try{
  if(locks?.request){try{const won=await new Promise((resolve,reject)=>{locks.request('youtrube.writer:'+CONFIG.key,{mode:'exclusive'},async()=>{if(epoch!==this.epoch){resolve(false);return}this.mode='web';this.active=true;resolve(true);await new Promise(release=>this.releaseLock=release);this.releaseLock=null;this.active=false}).catch(reject)});return won}catch(error){if(epoch!==this.epoch)return false}}
  this.mode='lease';while(epoch===this.epoch){const won=await this.lease((record,store)=>{const now=RealClock.now(),hint=this.closingHint(),closed=hint?.owner===record?.owner&&Number.isFinite(hint?.at)&&now-hint.at>=500;if(record&&record.owner!==this.owner&&record.until>now&&!closed)return false;store.put({owner:this.owner,until:now+SESSION_LEASE_MS},CONFIG.key);localStorage.removeItem?.(CONFIG.key+'.writerClosed');return true});if(won){this.active=true;this.renewTimer=setInterval(()=>{void this.lease((record,store)=>{if(!this.active||record?.owner!==this.owner)return false;store.put({owner:this.owner,until:RealClock.now()+SESSION_LEASE_MS},CONFIG.key);return true}).then(ok=>{if(!ok)this.pause()}).catch(()=>this.pause())},2000);return true}await new Promise(resolve=>setTimeout(resolve,1000))}return false
 }catch(error){if(epoch!==this.epoch)return false;throw error}finally{clearTimeout(waitingTimer)}},
 async commit(write){if(!this.check())return false;if(!this.enforced||this.mode!=='lease')return write();const ok=await this.lease((record,store)=>{if(!this.active||record?.owner!==this.owner)return false;if(!this.check())return false;store.put({owner:this.owner,until:RealClock.now()+SESSION_LEASE_MS},CONFIG.key);this.committing=true;try{return write()}finally{this.committing=false}});if(!ok&&this.active&&!storageFailed)this.pause();return ok},
 async release(){clearInterval(this.renewTimer);this.renewTimer=null;if(this.mode==='web'){this.releaseLock?.();return}if(this.mode==='lease')try{await this.lease((record,store)=>{if(record?.owner===this.owner)store.delete(CONFIG.key);return true})}catch{}},
 async finish(){if(!this.enforced)return;this.epoch++;await stateWriteQueue.catch(()=>{});this.active=false;await this.release()}
};
window.addEventListener('storage',e=>{if(SessionCoordinator.enforced&&SessionCoordinator.active&&(e.key===CONFIG.key||e.key===null)&&!SessionCoordinator.matchesStorage())SessionCoordinator.pause()});
document.addEventListener('click',e=>{if(SessionCoordinator.interactive())return;const button=e.target.closest?.('[data-session-action]');e.preventDefault();e.stopImmediatePropagation();if(button?.dataset.sessionAction==='reload')location.reload();else if(button?.dataset.sessionAction==='export'&&state)void exportData()},true);
for(const type of ['submit','change','input','keydown'])document.addEventListener(type,e=>{if(!SessionCoordinator.interactive()){if(type!=='keydown')e.preventDefault();e.stopImmediatePropagation()}},true);
window.addEventListener('pagehide',()=>{if(!SessionCoordinator.enforced)return;if(state&&appReady){settleTime();saveState(true)}SessionCoordinator.closing=true;SessionCoordinator.signalClose();appReady=false;player.playing=false;shortPlayback.playing=false;void SessionCoordinator.finish()});
window.addEventListener('pageshow',e=>{if(e.persisted){void SessionCoordinator.finish().then(()=>boot()).catch(showBootError)}});
