// YOUTRUBE 4.0 — all evidence advances in the existing real-time simulation.
const SOCIAL_LIMITS={ownPosts:80,npcPosts:2,comments:12,replies:12,notifications:60};
const AGE_LABELS=['13–17','18–24','25–34','35–44','45–54','55–64','65+'];
const COUNTRY_LABELS=['Россия','Казахстан','Беларусь','Украина','Германия','Другие страны'];
const DEVICE_LABELS=['Смартфоны','Компьютеры','Планшеты','Телевизоры'];
const CHANNEL_STEPS=[100,1000,10000,100000,1000000],VIDEO_STEPS=[1000,10000,100000,1000000],POST_STEPS=[100,1000,10000];
const largestReached=(n,steps)=>steps.reduce((a,b)=>n>=b?b:a,0);
const normalizeWeights=a=>{const sum=a.reduce((s,n)=>s+n,0);return a.map(n=>n/sum)};
function weightedCounts(total,weights){let remaining=total;return weights.map((w,i)=>{const n=i===weights.length-1?remaining:total*w;remaining-=n;return Math.max(0,n)})}
function integerAllocation(total,weights){const raw=weightedCounts(total,weights),out=raw.map(Math.floor),order=raw.map((n,i)=>({i,r:n-out[i]})).sort((a,b)=>b.r-a.r||a.i-b.i);const remainder=total-out.reduce((a,b)=>a+b,0);for(let j=0;j<remainder;j++)out[order[j].i]++;return out}
function pollPercentages(options){const total=options.reduce((s,o)=>s+o.votes,0);return total?integerAllocation(100,options.map(o=>o.votes/total)):options.map(()=>0)}
function demographicProfile(c){if(c.audienceProfile.demographics)return c.audienceProfile.demographics;const gaming=c.niche==='Игры',education=c.niche==='Обучение';const seed=c.seed;return c.audienceProfile.demographics={since:RealClock.now(),age:normalizeWeights([.06,.22,.27,.20,.13,.08,.04].map((n,i)=>n*(.8+seeded(seed,'age'+i)*.4)*(gaming&&i<2?1.18:education&&i>2?1.10:1))),countries:normalizeWeights([.60,.10,.07,.07,.05,.11].map((n,i)=>n*(.85+seeded(seed,'country'+i)*.3))),devices:normalizeWeights([.55,.26,.07,.12].map((n,i)=>n*(.8+seeded(seed,'device'+i)*.4)))}}
function emptyDemographicEvidence(){return{views:0,age:Array(7).fill(0),countries:Array(6).fill(0),devices:Array(4).fill(0),activity:{}}}
function mergeDemographicEvidence(a,b){if(!b)return a;for(const key of ['age','countries','devices'])b[key].forEach((n,i)=>a[key][i]+=n);a.views+=b.views;for(const [k,n]of Object.entries(b.activity))a.activity[k]=(a.activity[k]||0)+n;return a}
function recordDemographicEvidence(v,views,fresh,t){if(v.channelId!=='me'||views<=0)return;const c=channelBy(v.channelId),p=demographicProfile(c),f=isShort(v)?'short':'video',row=audienceDay(c,t);row.demographics??={};if(t<p.since)return;const e=row.demographics[f]??=emptyDemographicEvidence();p.base??={age:p.age.slice(),countries:p.countries.slice(),devices:p.devices.slice()};const age=normalizeWeights(p.base.age.map((n,i)=>n*(f==='short'?(i<2?1.12:.96):1))),devices=normalizeWeights(p.base.devices.map((n,i)=>n*(f==='short'&&i===0?1.15:1))),countries=normalizeWeights(p.base.countries.map((n,i)=>n*(.97+seeded(c.seed,f+'-country-'+i)*.06)));mergeDemographicEvidence(e,{views,age:weightedCounts(views,age),countries:weightedCounts(views,p.countries),devices:weightedCounts(views,devices),activity:{[(new Date(t).getDay()+6)%7*24+new Date(t).getHours()]:views}});
 // Slowly mix acquired viewers into the current profile; stored evidence is never rewritten.
 const mix=1-Math.exp(-Math.max(0,fresh)/Math.max(1000,c.audienceProfile.totalViewers*2));for(const [key,target]of Object.entries({age,countries,devices}))p[key]=normalizeWeights(p[key].map((n,i)=>n*(1-mix)+target[i]*mix));
}
const recordBeforeSocial=recordAudience;
recordAudience=function(v,opportunities,views,repeats,t,hours,options){initializeSocialVideo(v);const result=recordBeforeSocial(v,opportunities,views,repeats,t,hours,options);recordDemographicEvidence(v,views,result.fresh,t);return result};
const mergeRowsBeforeSocial=mergeAudienceRows;
mergeAudienceRows=function(a,b){mergeRowsBeforeSocial(a,b);if(b.demographics){a.demographics??={};for(const [f,e]of Object.entries(b.demographics))mergeDemographicEvidence(a.demographics[f]??=emptyDemographicEvidence(),e)}return a};
function demographicMetrics(c,days=period,format='all',until=RealClock.now()){const cutoff=days?calendarCutoff(days,until):0,out=emptyDemographicEvidence(),byFormat={video:0,short:0};const rows=[...(!days&&c.audienceProfile.lifetime?[c.audienceProfile.lifetime]:[]),...c.audienceProfile.history];for(const row of rows){if(row.at<cutoff||row.at>until)continue;for(const f of ['video','short']){const e=row.demographics?.[f];if(!e)continue;byFormat[f]+=e.views;if(format==='all'||format===f)mergeDemographicEvidence(out,e)}}return{...out,byFormat}}
function demographicBars(title,labels,values,total){const percentages=total?integerAllocation(100,values.map(n=>n/total)):values.map(()=>0);return `<section class="panel"><h3>${title}</h3>${labels.map((name,i)=>`<div class="demographic-row"><span>${name}</span><div class="demographic-track"><span style="width:${total?values[i]/total*100:0}%"></span></div><button class="text-btn demographic-value" data-action="demographic-value" data-label="${esc(name)}" data-value="${values[i]}" title="${exact(values[i])} просмотров">${percentages[i]}%</button></div>`).join('')}</section>`}
function deepAudiencePanel(){const c=channelBy('me'),type=readRoute().query.get('type'),format=type==='shorts'?'short':type==='video'?'video':'all',m=demographicMetrics(c,period,format),tracked=audienceMetrics(c,period,format).views,max=Math.max(1,...Object.values(m.activity));return `<div class="deep-audience" id="deep-audience"><div class="section-head"><h2>Кто смотрит ваши публикации</h2><span class="tiny muted">${exact(m.views)} просмотров с данными</span></div><p class="audience-note">Агрегированная виртуальная аудитория · учёт с ${date(demographicProfile(c).since)}. Доли относятся к просмотрам, а не к уникальным людям. ${m.views+1e-5<tracked?'Для '+exact(Math.max(0,tracked-m.views))+' старых просмотров демография неизвестна. ':''}История сохраняет профиль на момент просмотра.</p><div class="demographic-grid">${demographicBars('Возраст зрителей',AGE_LABELS,m.age,m.views)}${demographicBars('География',COUNTRY_LABELS,m.countries,m.views)}${demographicBars('Устройства',DEVICE_LABELS,m.devices,m.views)}${demographicBars('Видео и Shorts', ['Видео','Shorts'],[m.byFormat.video,m.byFormat.short],m.byFormat.video+m.byFormat.short)}</div><section class="panel" style="margin-top:20px"><h3>Когда смотрят ваши публикации</h3><p class="panel-subheading">Местное время · понедельник — воскресенье · выбранный формат</p><div class="heatmap-scroll"><div class="heatmap-grid"><span></span>${Array.from({length:24},(_,h)=>`<span class="heatmap-label">${h%3===0?h:''}</span>`).join('')}${['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((d,i)=>`<span class="heatmap-label">${d}</span>${Array.from({length:24},(_,h)=>{const n=m.activity[i*24+h]||0,label=d+', '+h+':00 — '+exact(n)+' просмотров';return `<button class="heat-cell" style="--heat:${n/max}" data-action="heat-value" data-label="${esc(label)}" aria-label="${esc(label)}" title="${esc(label)}"></button>`}).join('')}`).join('')}</div></div><div class="heatmap-value" id="heatmap-value" aria-live="polite">Нажмите на час, чтобы увидеть число просмотров.</div>${!m.views?'<p class="tiny muted">Исторических данных пока нет. Первые просмотры заполнят карту.</p>':''}</section></div>`}
const audiencePanelBeforeSocial=audiencePanel;
audiencePanel=function(){return audiencePanelBeforeSocial().replace(/<\/div>$/,deepAudiencePanel()+'</div>')};
actions['demographic-value']=b=>toast(b.dataset.label+': '+exact(Number(b.dataset.value))+' просмотров');actions['heat-value']=b=>{$('#heatmap-value').textContent=b.dataset.label};

let socialBatchKey=null;
function eventNotification(key,text,route,group='',at=RealClock.now()){const s=state.social;if(s.eventKeys.includes(key))return false;s.eventKeys.push(key);if(s.eventKeys.length>1200)s.eventKeys.splice(0,s.eventKeys.length-1200);const last=group&&state.notifications.find(n=>n.group===group&&!n.read&&(socialBatchKey?n.batch===socialBatchKey:at>=n.at&&at-n.at<10*60e3));if(last){last.items??=[{text:last.text,route:last.route}];last.items.push({text,route});last.items=last.items.slice(-8);last.count=(last.count||1)+1;last.text=last.count+' события: '+last.items.map(x=>x.text).slice(-3).join(' · ');last.route=last.items.every(x=>x.route===route)?route:group==='community'?'channel/me?tab=community':'studio/analytics';last.at=at}else{state.notifications.unshift({id:uid('n'),key,text,route,at,read:false,group,batch:socialBatchKey});state.notifications=state.notifications.slice(0,SOCIAL_LIMITS.notifications)}return true}
function initializeSocialVideo(v){v.visibleComments??=[];v.socialEvidence??={milestone:largestReached(v.views,VIDEO_STEPS),waveAt:Math.max(0,...(v.distribution?.waves||[]).map(w=>w.at)),growthNotified:false};return v.socialEvidence}
function makeCommunityPost(c,{text,type='text',options=[],image=null},at=RealClock.now()){const id=uid('post'),seed=hash(id),weights=normalizeWeights(options.map((x,i)=>optionPreference(c,x)+seeded(seed,'post-option'+i)*.12));return{id,channelId:c.id,type,text:text.trim(),image,publishedAt:at,realCreatedAt:at,editedAt:null,reach:0,likes:0,liked:false,votes:0,simulatedVotes:0,voteCarry:0,userVote:null,closed:false,options:options.map(text=>({id:uid('option'),text:text.trim(),votes:0})),weights,quality:.45+seeded(seed,'quality')*.30+Math.min(.15,text.length/2000),seed,notifiedReach:0,notifiedVotes:0,history:[]}}
function communityTheme(c){return ({Технологии:['Какую сторону технологии разберём в следующем выпуске?',['Устройство и принципы','Практический тест','Удобство в повседневной жизни']],Путешествия:['На чём сосредоточиться в следующем путешествии?',['Маршрут и дорога','Местная культура','Полезные советы']],Дизайн:['Что разобрать в следующем выпуске о дизайне?',['Композицию','Цвет и типографику','Практический разбор']],Игры:['Что интереснее разобрать в следующем игровом выпуске?',['Механики игры','Историю мира','Тактику прохождения']],Обучение:['Какой формат помогает вам учиться?',['Короткий пример','Подробное объяснение','Практическая задача']],Музыка:['О чём поговорим в следующем музыкальном выпуске?',['Ритм','Мелодия','История жанра']],Спорт:['Какой формат спортивного выпуска выбрать?',['Разбор техники','План тренировок','История спорта']],Новости:['Как вам удобнее разбираться в новостях?',['Краткий обзор','Подробный разбор','Ответы на вопросы']],Подкасты:['Что для вас важнее в разговорном выпуске?',['Тема разговора','Вопросы гостю','Ответы слушателям']],Развлечения:['Какой выпуск хотите увидеть дальше?',['История со съёмок','Новая идея','Вопросы и ответы']]})[c.niche]||['Что вам интереснее в следующем выпуске?',['Разбор темы','Ответы на вопросы','История создания']]}
function seedCommunity(s){for(const c of s.channels.filter(c=>c.id!=='me').slice(0,24)){if(!s.community.posts.some(p=>p.channelId===c.id)){const [text,options]=communityTheme(c);s.community.posts.push(makeCommunityPost(c,{text,type:'poll',options},RealClock.now()))}}}
const migrateBeforeSocial=migrateState;
migrateState=function(s){migrateBeforeSocial(s);s.preferences.commentSort??='popular';s.socialVersion??=1;s.community??={posts:[]};s.social??={eventKeys:[],channelMilestone:largestReached(s.channels.find(c=>c.id==='me').subscribers,CHANNEL_STEPS),eligibleNotified:false};s.social.eventKeys??=[];for(const c of s.channels){demographicProfile(c);c.verification??={status:'none',name:null};c.verified??=c.id!=='me'&&c.subscribers>=100000&&seeded(c.seed,'verification')>.55;if(c.verified){c.verification.status='verified';c.verification.name??=c.name}}for(const v of s.videos){initializeSocialVideo(v);for(const x of v.localComments)x.id??=uid('comment');}seedCommunity(s);return s};
function postBy(id){return state.community.posts.find(p=>p.id===id)}
function applyPollVotes(p,total){const next=Math.max(p.simulatedVotes,Math.floor(total));if(next===p.simulatedVotes&&p.votes===next+(p.userVote?1:0))return;p.simulatedVotes=next;const counts=monotonicAllocation(p.simulatedVotes,p.weights);p.options.forEach((o,i)=>o.votes=counts[i]+(p.userVote===o.id?1:0));p.votes=p.options.reduce((s,o)=>s+o.votes,0)}
function votePost(p,optionId){if(!p||p.channelId==='me'||p.type!=='poll'||p.closed||p.userVote||!p.options.some(o=>o.id===optionId))return false;p.userVote=optionId;applyPollVotes(p,p.simulatedVotes);return true}
function communityStep(from,to){const hours=(to-from)/HOUR*(state.simulation.intensity??state.simulation.speed);if(hours<=0)return;for(const p of state.community.posts){if(to<=p.publishedAt)continue;const c=channelBy(p.channelId);if(!c)continue;const age=Math.max(0,((from+to)/2-p.publishedAt)/HOUR),a=audienceTotals(c),active=a.new+a.casual*.45+a.regular,loyalty=c.audienceProfile.loyalty,affinity=c.audienceProfile.topicAffinity[c.niche]||.45,external=8+Math.min(2000,Math.sqrt(Math.max(0,c.subscribers))*1.8)*(seeded(p.seed,'external')>.92?1.8:.35),capacity=Math.max(8,active*.55+c.subscribers*.18+external),rate=capacity/50*Math.exp(-age/64)*(.45+loyalty*.55)*(.6+affinity*.4)*p.quality,delta=Math.max(0,Math.min(capacity-p.reach,rate*hours));p.reach+=delta;p.likes+=delta*(.015+loyalty*.045);if(p.type==='poll'&&!p.closed){p.voteCarry+=delta*(.12+loyalty*.23);applyPollVotes(p,p.voteCarry)}if(delta>0){const at=localDay(Math.max(from,to-1));let row=p.history.at(-1);if(!row||row.at!==at)p.history.push(row={at,reach:0});row.reach+=delta;p.history=p.history.slice(-40)}if(p.channelId==='me'){const reach=largestReached(p.reach,POST_STEPS),votes=largestReached(p.votes,POST_STEPS);if(reach>p.notifiedReach){eventNotification(p.id+':reach:'+reach,'«'+p.text.slice(0,45)+'»: охват '+exact(reach)+' зрителей','channel/me?tab=community&post='+p.id,'community',to);p.notifiedReach=reach}if(votes>p.notifiedVotes){eventNotification(p.id+':votes:'+votes,'«'+p.text.slice(0,45)+'»: '+exact(votes)+' голосов','channel/me?tab=community&post='+p.id,'community',to);p.notifiedVotes=votes}}}}
function verificationRequirements(c=channelBy('me')){return[{ok:c.subscribers>=100000,label:'Не менее 100 000 подписчиков'},{ok:!!c.name?.trim(),label:'Название канала'},{ok:!!safeImage(c.avatar),label:'Загруженная аватарка'},{ok:!!safeImage(c.banner),label:'Загруженный баннер'},{ok:!!c.description?.trim(),label:'Описание канала'},{ok:state.videos.some(v=>v.channelId===c.id&&v.visibility==='public'&&!v.archived),label:'Общедоступное видео или Shorts'}]}
function checkVerificationName(c,nextName=c.name){if((c.verified||c.verification?.status==='pending')&&c.verification.name!==nextName){c.verified=false;c.verification={status:'reapply',name:null};eventNotification('verification:rename:'+hash(nextName),'Название канала изменено. Подайте новую заявку на подтверждение.','studio/customization')}}
function applyVerification(){const c=channelBy('me');if(c.verification.status==='pending'||c.verified||!verificationRequirements(c).every(x=>x.ok))return false;const at=RealClock.now();c.verification={status:'pending',name:c.name,submittedAt:at,reviewAt:at+10*60e3};eventNotification('verification:accepted:'+at,'Заявка на подтверждение принята. Проверка займёт около 10 минут.','studio/customization');return true}
function socialMaintenance(){if(!state?.social)return;const c=channelBy('me');checkVerificationName(c);if(c.subscribers>=100000&&!state.social.eligibleNotified){state.social.eligibleNotified=true;eventNotification('verification:eligible','Ваш канал достиг 100 000 подписчиков. Теперь вы можете подать заявку на подтверждение.','studio/customization')}const review=c.verification;if(review.status==='pending'&&RealClock.now()>=review.reviewAt){const approved=verificationRequirements(c).every(x=>x.ok)&&c.name===review.name;c.verified=approved;review.status=approved?'verified':'rejected';review.decidedAt=RealClock.now();review.reason=approved?'Профиль заполнен и условия выполнены.':'Условия больше не выполняются. Заполните профиль и подайте заявку снова.';eventNotification('verification:decision:'+review.submittedAt,approved?'Проверка завершена: ваш канал подтверждён.':'Проверка завершена: '+review.reason,'studio/customization')}}
function socialMilestones(to){const c=channelBy('me'),reached=largestReached(c.subscribers,CHANNEL_STEPS);if(reached>state.social.channelMilestone){state.social.channelMilestone=reached;eventNotification('channel:subs:'+reached,'На вашем канале '+exact(reached)+' подписчиков','studio/analytics','channel',to)}for(const v of mine()){const s=initializeSocialVideo(v),level=largestReached(v.views,VIDEO_STEPS);if(level>s.milestone){s.milestone=level;eventNotification(v.id+':views:'+level,(isShort(v)?'Shorts':'Видео')+' «'+v.title+'»: '+exact(level)+' просмотров',videoRoute(v),'performance',to)}const latest=v.distribution?.waves.at(-1);if(latest&&latest.at>s.waveAt){s.waveAt=latest.at;eventNotification(v.id+':wave:'+latest.at,'Новая волна продвижения: «'+v.title+'»',videoRoute(v),'promotion',to)}if(!s.growthNotified&&v.distribution?.reachScale>5&&v.distribution.samples>1000){s.growthNotified=true;eventNotification(v.id+':expansion','Расширяется аудитория '+(isShort(v)?'Shorts':'видео')+' «'+v.title+'»',videoRoute(v),'promotion',to)}generateVisibleComments(v,to)}socialMaintenance()}
const simulateBeforeSocial=simulateStep;
simulateStep=function(from,to){simulateBeforeSocial(from,to);communityStep(from,to);socialMilestones(to)};
function verificationIcon(c){return c?.verified?'<span class="verified-badge" title="Подтверждённый канал" role="img" aria-label="Подтверждённый канал">✓</span>':''}
function verifiedBadge(c){return '<span data-verification-marker="'+c.id+'">'+verificationIcon(c)+'</span>'}
function channelLabel(c){return '<span data-channel-label="'+c.id+'">'+esc(c.name)+verifiedBadge(c)+'</span>'}
function verificationPanel(){const c=channelBy('me'),status=c.verification.status,requirements=verificationRequirements(c),eligible=requirements.every(x=>x.ok);return `<section class="panel verification-panel" id="verification-panel"><h2>Подтверждение канала ${verifiedBadge(c)}</h2><p class="panel-subheading">${status==='verified'?'Канал подтверждён':status==='pending'?'На рассмотрении · решение после '+new Date(c.verification.reviewAt).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'}):status==='reapply'?'После смены названия требуется повторное подтверждение':status==='rejected'?esc(c.verification.reason):'Заявка доступна после 100 000 подписчиков'}</p><ul>${requirements.map(x=>`<li>${x.ok?'✓':'○'} ${x.label}</li>`).join('')}</ul>${status==='verified'?'<p class="tiny muted">При изменении названия потребуется новая проверка. Псевдоним можно менять.</p>':status==='pending'?'<p class="tiny muted">Локальная проверка профиля занимает около 10 реальных минут. Статус сохранён; закрытие страницы не отменяет заявку.</p>':btn('verify-apply','Подать заявку','','primary',eligible?'':'disabled')}<p class="post-notice">Подтверждение не влияет на продвижение публикаций.</p></section>`}
const customizationBeforeSocial=customization;
customization=function(){socialMaintenance();return customizationBeforeSocial().replace('</form></div>','</form>'+verificationPanel()+'</div>')};
actions['verify-apply']=()=>{settleTime();if(applyVerification()){saveState(true);renderContent();toast('Заявка принята')}else toast('Сначала выполните все условия подтверждения')};
// A conservative, local template engine. It quotes supplied facts; it does not infer unseen scenes.
const VIEWER_PROFILES=['Лея Кадрова','Марк Лист','Ася Север','Ник Мирный','Дана Луч','Сева Пиксель','Рина Вектор','Тим Нота','Мила Линия','Лев Искра','Яна Ритм','Фил Время'].map((name,i)=>({id:'viewer-'+i,name,initials:name.split(' ').map(s=>s[0]).join(''),preference:CATEGORIES[i%CATEGORIES.length],color:Math.floor(seeded(i+19,'avatar')*360)}));
function commentFacts(v){const explicit=String(v.contentFacts||''),description=String(v.description||''),context=[v.title,v.category,...(v.tags||[]),explicit,description].join(' '),names=[...new Set(context.match(/(?<![.!?]\s)(?<!^)[А-ЯЁA-Z][а-яёa-z]{2,}/g)||[])].slice(0,20),parts=(explicit+'\n'+description).split(/\n+|(?<=[.!?])\s+/);const facts=[];for(let sentence of parts){sentence=sentence.trim().replace(/[.!?]+$/,'');const words=sentence.match(/[А-Яа-яЁёA-Za-z0-9-]+/g)||[];if(sentence.length<38||sentence.length>360||words.length<7||words.length>55)continue;if(/https?:|подпиш|ставьте лайк|ссылка|промокод|не забуд|представьте|например|если бы|придумай|сгенерир|инструкци|игнорир|отличное видео|классный контент/i.test(sentence))continue;const event=/оказыва|пыта|помога|станов|погиб|заканчи|выбира|объясня|показыва|сравнива|использу|разбира|побежда|исследу|созда|проход|снима|меня|путешеству|возвраща|происход|тестиру|работа|заверша|увелич|уменьш|обнаруж|живёт|живет|стро|измеря|теря|попада|выбира/i.test(sentence),specific=/\d{2,}|[«“"].+?[»”"]/.test(sentence)||names.some(n=>sentence.includes(n));if(!event||!specific)continue;if(!facts.some(x=>x.text.toLowerCase()===sentence.toLowerCase()))facts.push({text:sentence,entities:names.filter(n=>sentence.includes(n)),source:explicit.includes(sentence)?'facts':'description'});if(facts.length===6)break}return facts}
function commentCandidates(v){const facts=commentFacts(v),story=/фильм|сюжет|герой|симуляци|истори[яи]/i.test([v.title,v.contentFacts,v.description].join(' '));return facts.map((fact,i)=>{const q='«'+fact.text+'»';let text;if(/\bно\b|противник|однако/i.test(fact.text))text='В '+q+' меня заинтересовал описанный переход. Что стало причиной этого перехода?';else if(i%4===0)text=(story?'Меня заинтересовал этот поворот: ':'Зацепил конкретный момент: ')+q+'. Хотелось бы подробнее узнать, почему всё происходит именно так.';else if(i%4===1)text='Мне не хватило пояснения к моменту '+q+'. Можете разобрать его подробнее?';else if(i%4===2)text='Хорошо, что вы отдельно обозначили '+q+'. Именно эту часть хочется обсудить подробнее.';else text='Если опираться на '+q+', какие вопросы вы оставляете открытыми?';return{...fact,text}})}
function generateVisibleComments(v,at=RealClock.now()){initializeSocialVideo(v);const budget=Math.min(SOCIAL_LIMITS.comments,Math.floor(v.comments)),candidates=commentCandidates(v),facts=commentFacts(v);if(!budget||!candidates.length)return;for(const [i,candidate]of candidates.entries()){if(v.visibleComments.length>=budget)break;const fact=facts[i]?.text;if(!fact||v.visibleComments.some(x=>x.fact===fact||x.text===candidate.text))continue;const preferred=VIEWER_PROFILES.filter(p=>p.preference===v.category),pool=preferred.length?[...preferred,...VIEWER_PROFILES.filter(p=>p.preference!==v.category)]:VIEWER_PROFILES,start=(Math.floor(seeded(hash(v.channelId),'commenter')*pool.length)+i)%pool.length,profile=Array.from({length:pool.length},(_,j)=>pool[(start+j)%pool.length]).find(person=>!state.videos.some(other=>other!==v&&other.channelId===v.channelId&&other.visibleComments?.some(x=>x.profileId===person.id&&x.text===candidate.text)));if(!profile)continue;v.visibleComments.push({id:uid('virtual-comment'),profileId:profile.id,author:profile.name,text:candidate.text,fact,entities:candidate.entities,source:candidate.source,at:Math.min(at,RealClock.now()),likes:Math.floor(seeded(v.seed,i+'likes')*Math.min(40,v.comments*.08)),liked:false,heart:false,pinned:false,replies:[]})}}
function commentCount(v){return Math.floor(v.comments)+v.localComments.length+[...v.localComments,...(v.visibleComments||[])].reduce((n,c)=>n+(c.replies?.length||0),0)}
let commentSort='popular';
function viewerAvatar(comment){const p=VIEWER_PROFILES.find(p=>p.id===comment.profileId);return p?`<span class="avatar small viewer-avatar" style="background:hsl(${p.color} 36% 32%);color:#fff" aria-hidden="true">${esc(p.initials)}</span>`:avatar(channelBy('me'),'small')}
function commentList(v){commentSort=state.preferences.commentSort==='new'?'new':'popular';initializeSocialVideo(v);const own=v.channelId==='me',comments=[...v.localComments,...v.visibleComments].sort((a,b)=>(!!b.pinned)-(!!a.pinned)||(commentSort==='new'?b.at-a.at:(b.likes||0)+(b.liked?1:0)-(a.likes||0)-(a.liked?1:0))||b.at-a.at);return `<div class="social-comment-list" data-comment-list="${v.id}"><div class="comment-sort"><strong>${comments.length?'Обсуждение':'Обсуждение пока не началось'}</strong><select class="select" aria-label="Сортировка комментариев" data-comment-sort="${v.id}"><option value="popular"${commentSort==='popular'?' selected':''}>Сначала популярные</option><option value="new"${commentSort==='new'?' selected':''}>Сначала новые</option></select></div>${comments.map(x=>`<article class="social-comment">${viewerAvatar(x)}<div class="social-comment-body">${x.pinned?'<div class="comment-pinned">Закреплено автором</div>':''}<strong class="tiny">${esc(x.author)}</strong> <span class="tiny muted">${formatRelativeTime(x.at)}</span><p>${esc(x.text)}</p><div class="comment-controls"><button class="text-btn" data-action="comment-like" data-video="${v.id}" data-id="${x.id}" aria-label="Лайк комментарию" aria-pressed="${!!x.liked}">${icon('like')}${exact((x.likes||0)+(x.liked?1:0))}</button>${btn('comment-reply','Ответить','','text-btn',`data-video="${v.id}" data-id="${x.id}"`)}${own?btn('comment-pin',x.pinned?'Открепить':'Закрепить','','text-btn',`data-video="${v.id}" data-id="${x.id}"`)+`<button class="text-btn" data-action="comment-heart" data-video="${v.id}" data-id="${x.id}" aria-pressed="${!!x.heart}">${x.heart?'♥ Сердечко автора':'♡ Сердечко'}</button>`:x.heart?'<span class="tiny">♥ Сердечко автора</span>':''}</div>${x.replies?.length?`<div class="comment-replies">${x.replies.map(r=>`<div class="comment-reply"><strong>${esc(r.author)}</strong> <span class="muted tiny">${formatRelativeTime(r.at)}</span><p>${esc(r.text)}</p></div>`).join('')}</div>`:''}</div></article>`).join('')}<p class="comment-disclosure">${v.visibleComments.length?'Виртуальные зрители обсуждают факты из описания автора. Показана небольшая выборка из агрегированного числа комментариев.':'Виртуальные сообщения появятся при достаточных фактах о содержании и реальных реакциях аудитории. Числовой счётчик учитывается отдельно.'}</p></div>`}
function findComment(v,id){return[...v.localComments,...v.visibleComments].find(x=>x.id===id)}
function refreshCommentUI(v){saveState();const el=$('[data-comment-list="'+v.id+'"]');if(el)el.outerHTML=commentList(v);$$('[data-comments="'+v.id+'"]').forEach(x=>x.textContent=exact(commentCount(v)))}
actions['comment-like']=b=>{const v=videoBy(b.dataset.video),c=v&&findComment(v,b.dataset.id);if(c){c.liked=!c.liked;refreshCommentUI(v)}};
actions['comment-pin']=b=>{const v=videoBy(b.dataset.video),c=v&&findComment(v,b.dataset.id);if(!c||v.channelId!=='me')return;const next=!c.pinned;[...v.localComments,...v.visibleComments].forEach(x=>x.pinned=false);c.pinned=next;refreshCommentUI(v)};
actions['comment-heart']=b=>{const v=videoBy(b.dataset.video),c=v&&findComment(v,b.dataset.id);if(c&&v.channelId==='me'){c.heart=!c.heart;refreshCommentUI(v)}};
actions['comment-reply']=b=>{const v=videoBy(b.dataset.video),c=v&&findComment(v,b.dataset.id);if(!c)return;if((c.replies?.length||0)>=SOCIAL_LIMITS.replies){toast('Достигнут предел ответов в этой ветке');return}const body=`<form id="reply-form" data-video="${v.id}" data-id="${c.id}"><p class="post-notice">Ответ на комментарий ${esc(c.author)}</p><textarea class="input" name="reply" aria-label="Ваш ответ" rows="4" maxlength="1000" required></textarea><button type="submit" class="btn primary" style="margin-top:16px">Отправить ответ</button></form>`;if($('.short-comments')){$('.short-comments').innerHTML=body}else openModal('Ответить на комментарий',body,btn('close-modal','Отмена','','outline'),true)};
showShortComments=function(v){openModal('Комментарии · '+exact(commentCount(v)),`<div class="short-comments"><p class="muted tiny">${esc(v.title)}</p><form class="comment-form" id="short-comment-form" data-id="${v.id}">${avatar(channelBy('me'),'small')}<input name="comment" aria-label="Комментарий Shorts" placeholder="Напишите комментарий" maxlength="1000" required><button type="submit" class="btn">${icon('share')}Отправить</button></form>${commentList(v)}</div>`,btn('close-modal','Закрыть','','outline'),true)};

let postDraft=null;
function postCard(p){const c=channelBy(p.channelId),own=c.id==='me',percent=pollPercentages(p.options),canVote=p.type==='poll'&&!own&&!p.closed&&!p.userVote;return `<article class="post-card" id="post-${p.id}" data-community-post="${p.id}"><div class="post-top"><a href="#/channel/${c.id}">${avatar(c)}</a><div class="post-identity"><a href="#/channel/${c.id}"><strong>${channelLabel(c)}</strong></a><div class="tiny muted">${formatRelativeTime(p.publishedAt)}${p.editedAt?' · изменено':''} · ${new Date(p.publishedAt).toLocaleString('ru-RU',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</div></div></div><p class="post-copy">${esc(p.text)}</p>${p.image?`<img class="post-image" src="${esc(safeImage(p.image))}" alt="Изображение публикации" loading="lazy">`:''}${p.type==='poll'?`<div class="poll-list">${p.options.map((o,i)=>`<button class="poll-choice" data-action="post-vote" data-id="${p.id}" data-option="${o.id}" aria-pressed="${p.userVote===o.id}"${canVote?'':' disabled'}><span class="poll-fill" style="width:${percent[i]}%"></span><span>${esc(o.text)}${p.userVote===o.id?' ✓':''}</span><span>${percent[i]}%</span></button>`).join('')}</div><p class="post-notice">${exact(p.votes)} ${plural(p.votes,'голос','голоса','голосов')} · ${p.closed?'Опрос завершён':own?'Ваш опрос':p.userVote?'Вы проголосовали':'Выберите один вариант'}</p>`:''}<div class="post-footer"><button class="text-btn" data-action="post-like" data-id="${p.id}" aria-pressed="${!!p.liked}" aria-label="Нравится публикация">${icon('like')}<span>${exact(p.likes+(p.liked?1:0))}</span></button><span class="tiny muted">${exact(p.reach)} охват · ${exact(p.likes+(p.liked?1:0)+p.votes)} реакций</span></div>${own?`<div class="post-controls">${btn('post-edit','Изменить','','text-btn',`data-id="${p.id}"`)}${p.type==='poll'&&!p.closed?btn('post-close','Завершить опрос','','text-btn',`data-id="${p.id}"`):''}${btn('post-delete','Удалить','','text-btn',`data-id="${p.id}"`)}</div>`:''}</article>`}
function communityPage(c){const own=c.id==='me',selected=readRoute().query.get('post'),posts=state.community.posts.filter(p=>p.channelId===c.id).sort((a,b)=>b.publishedAt-a.publishedAt);if(selected)posts.sort((a,b)=>(b.id===selected)-(a.id===selected));return `<section class="community-feed" id="community-feed"><div class="community-head"><div><h2>Сообщество</h2><p class="tiny muted" style="margin-top:7px">${own?'Общайтесь с аудиторией между выпусками':'Публикации автора и опросы аудитории'}</p></div>${own?btn('post-create','Создать публикацию','create','primary'):''}</div>${posts.length?posts.map(postCard).join(''):empty('Начните разговор','Поделитесь мыслью, изображением или задайте вопрос в опросе.','')} ${own?'<p class="post-notice">Охват и реакции растут постепенно вместе с активностью вашей аудитории.</p>':''}</section>`}
const channelPageBeforeSocial=channelPage;
channelPage=function(c){if(!c)return channelPageBeforeSocial(c);const html=channelPageBeforeSocial(c),tabsEnd=html.indexOf('</div>',html.indexOf('<div class="tabs"'));const tab=`<button class="tab${channelTab==='community'?' active':''}" role="tab" aria-selected="${channelTab==='community'}" data-action="channel-tab" data-tab="community">Сообщество</button>`;return html.slice(0,tabsEnd)+tab+html.slice(tabsEnd,channelTab==='community'?tabsEnd+6:undefined)+(channelTab==='community'?communityPage(c):'')};
function postEditor(p=null,type=p?.type||'text'){postDraft={id:p?.id||null,type,image:p?.image||null,pending:0};openModal(p?'Изменить публикацию':'Публикация в сообществе',`<form id="post-form"><div class="community-format">${[['text','Текст'],['image','Изображение'],['poll','Опрос']].map(([id,t])=>btn('post-format',t,'',type===id?'primary':'outline',`data-type="${id}"${p?' disabled':''}`)).join('')}</div><div class="field"><label for="post-text">${type==='poll'?'Вопрос для аудитории':'Текст публикации'}</label><textarea class="input" name="text" id="post-text" rows="5" required maxlength="3000" placeholder="Поделитесь мыслью с вашей аудиторией">${esc(p?.text||'')}</textarea></div>${type==='poll'?`<div class="post-editor-options"><label class="tiny muted">От 2 до 4 вариантов ответа</label>${Array.from({length:4},(_,i)=>`<input class="input" name="option${i}" aria-label="Вариант ${i+1}" maxlength="120" placeholder="Вариант ${i+1}${i>1?' (необязательно)':''}" value="${esc(p?.options[i]?.text||'')}"${i<2?' required':''}${p?' disabled':''}>`).join('')}</div>${p?'<p class="post-notice">После публикации варианты сохраняются, чтобы уже поданные голоса не меняли смысл.</p>':''}`:''}${type==='image'?imageInput('post-image','Выбрать изображение')+`<div class="post-edit-preview" id="post-edit-preview">${p?.image?`<img src="${esc(safeImage(p.image))}" alt="Предпросмотр публикации">`:''}</div>`:''}<div class="form-error" id="post-error" role="alert"></div></form>`,btn('close-modal','Отмена','','outline')+'<button class="btn primary" type="submit" form="post-form">'+(p?'Сохранить':'Опубликовать')+'</button>')}
function saveCommunityPost(data){const p=data.id?postBy(data.id):null,c=channelBy('me'),text=String(data.text||'').trim(),options=(data.options||[]).map(x=>String(x).trim()).filter(Boolean);if(!['text','image','poll'].includes(data.type))throw Error('Неизвестный тип публикации.');if(!text||text.length>3000)throw Error('Введите текст от 1 до 3 000 символов.');if(p&&p.channelId!=='me')throw Error('Это публикация другого автора.');if(!p&&state.community.posts.filter(x=>x.channelId==='me').length>=SOCIAL_LIMITS.ownPosts)throw Error('Достигнут предел 80 публикаций. Удалите одну из старых.');if(!p&&data.type==='poll'&&(options.length<2||options.length>4||new Set(options.map(x=>x.toLowerCase())).size!==options.length||options.some(x=>x.length>120)))throw Error('Укажите 2–4 разных варианта до 120 символов.');if(data.type==='image'&&!data.image)throw Error('Выберите изображение.');if(p){p.text=text;p.image=data.image||p.image;p.editedAt=RealClock.now();return p}const created=makeCommunityPost(c,{text,type:data.type,options,image:data.image});state.community.posts.push(created);return created}
actions['post-create']=()=>postEditor();actions['post-edit']=b=>{const p=postBy(b.dataset.id);if(p?.channelId==='me')postEditor(p)};
actions['post-format']=b=>{const draft=postDraft;if(!draft||draft.id||draft.pending)return;const text=$('#post-text').value;postEditor(null,b.dataset.type);$('#post-text').value=text};
actions['post-vote']=b=>{settleTime();const p=postBy(b.dataset.id);if(votePost(p,b.dataset.option)){saveState(true);refreshPost(p)}};
actions['post-like']=b=>{const p=postBy(b.dataset.id);if(p){p.liked=!p.liked;saveState();refreshPost(p)}};
function closePostPoll(p){if(!p||p.channelId!=='me'||p.type!=='poll'||p.closed)return false;p.closed=true;p.closedAt=RealClock.now();eventNotification(p.id+':closed','Опрос завершён: '+exact(p.votes)+' голосов','channel/me?tab=community&post='+p.id);return true}
actions['post-close']=b=>{settleTime();const p=postBy(b.dataset.id);if(closePostPoll(p)){saveState(true);refreshPost(p);toast('Опрос завершён')}};
actions['post-delete']=b=>{const p=postBy(b.dataset.id);if(p?.channelId==='me')confirmModal('Удалить публикацию?','Публикация и результаты опроса будут удалены.','post-delete-confirm','Удалить',`data-id="${p.id}"`)};
actions['post-delete-confirm']=b=>{const p=postBy(b.dataset.id);if(p?.channelId!=='me')return;state.community.posts=state.community.posts.filter(x=>x!==p);saveState(true);closeModal();renderContent();ImageStore.collect();toast('Публикация удалена')};
function refreshPost(p){const el=$('[data-community-post="'+p.id+'"]');if(el)el.outerHTML=postCard(p)}
const handleImageBeforeSocial=handleImage;
handleImage=async function(input){if(input.name!=='post-image')return handleImageBeforeSocial(input);const draft=postDraft;if(!draft||!input.files[0])return;draft.pending++;try{const data=await optimizePostImage(input.files[0]),ref=await ImageStore.put(data);if(postDraft!==draft||!$('#post-edit-preview'))return;draft.image=ref;$('#post-edit-preview').innerHTML=`<img src="${esc(data)}" alt="Предпросмотр публикации">`;toast('Изображение готово')}catch(e){const error=$('#post-error');if(error)error.textContent=e.message;else toast(e.message)}finally{draft.pending--}};
document.addEventListener('change',e=>{if(e.target.dataset.commentSort){commentSort=e.target.value;state.preferences.commentSort=commentSort;const v=videoBy(e.target.dataset.commentSort);if(v)refreshCommentUI(v)}});
document.addEventListener('submit',e=>{if(e.target.id==='post-form'){e.preventDefault();try{if(postDraft.pending)throw Error('Дождитесь обработки изображения.');settleTime();const data=new FormData(e.target);saveCommunityPost({...postDraft,text:data.get('text'),options:[0,1,2,3].map(i=>data.get('option'+i)||'')});saveState(true);closeModal();postDraft=null;channelTab='community';renderContent();toast('Публикация сохранена')}catch(error){$('#post-error').textContent=error.message}}else if(e.target.id==='reply-form'){e.preventDefault();const v=videoBy(e.target.dataset.video),c=v&&findComment(v,e.target.dataset.id),text=String(new FormData(e.target).get('reply')||'').trim();if(!c||!text||text.length>1000)return;c.replies??=[];if(c.replies.length>=SOCIAL_LIMITS.replies)return;c.replies.push({id:uid('reply'),author:channelBy('me').name,text,at:RealClock.now()});saveState(true);if(isShort(v))showShortComments(v);else{closeModal();refreshCommentUI(v)}toast('Ответ сохранён')}});

function notificationsMarkup(){return `<div class="dropdown-heading"><strong>Уведомления</strong>${btn('notifications-read-all','Прочитать все','','text-btn')}</div><div class="notification-panel">${state.notifications.length?state.notifications.map(n=>`<div class="notification-item${n.read?'':' unread'}"><button class="notification-link" data-action="notification-open" data-id="${n.id}">${esc(n.text)}<small class="muted">${formatRelativeTime(n.at)}${n.read?' · прочитано':''}</small></button>${!n.read?btn('notification-read','✓','','text-btn',`data-id="${n.id}" aria-label="Отметить прочитанным"`):''}</div>`).join(''):'<p class="post-notice" style="padding:15px">Важные события вашего канала появятся здесь.</p>'}</div>`}
actions.notifications=b=>{socialMaintenance();dropdown(b,notificationsMarkup())};
actions['notification-open']=b=>{const n=state.notifications.find(x=>x.id===b.dataset.id);if(n){n.read=true;saveState();closeDropdown();location.hash='/'+n.route;updateNotificationBadge()}};
actions['notification-read']=b=>{const n=state.notifications.find(x=>x.id===b.dataset.id);if(n){n.read=true;saveState();const el=$('.dropdown');if(el)el.innerHTML=notificationsMarkup();updateNotificationBadge()}};
actions['notifications-read-all']=()=>{state.notifications.forEach(n=>n.read=true);saveState(true);const el=$('.dropdown');if(el)el.innerHTML=notificationsMarkup();updateNotificationBadge()};
function updateNotificationBadge(){const button=$('[data-action="notifications"]');if(!button)return;button.querySelector('.notification-count')?.remove();const count=state.notifications.filter(n=>!n.read).length;button.setAttribute('aria-label','Уведомления'+(count?', '+count+' непрочитанных':''));if(count){const badge=document.createElement('span');badge.className='notification-count';badge.textContent=count>9?'9+':String(count);badge.setAttribute('aria-hidden','true');button.append(badge)}}
const shellBeforeSocial=shell;
shell=function(studio){shellBeforeSocial(studio);updateNotificationBadge()};
const updateBeforeSocial=updateLive;let lastSocialRender=0;
updateLive=function(){socialMaintenance();updateBeforeSocial();updateNotificationBadge();$$('[data-channel-label]').forEach(el=>{const c=channelBy(el.dataset.channelLabel);if(c)el.innerHTML=esc(c.name)+verifiedBadge(c)});$$('[data-verification-marker]').forEach(el=>{const c=channelBy(el.dataset.verificationMarker);if(c)el.innerHTML=verificationIcon(c)});$$('[data-comments]').forEach(el=>{const v=videoBy(el.dataset.comments);if(v)el.textContent=exact(commentCount(v))});if(RealClock.now()-lastSocialRender>5000){lastSocialRender=RealClock.now();if(!$('.modal')){$$('[data-community-post]').forEach(el=>{const p=postBy(el.dataset.communityPost);if(p)refreshPost(p)});const verify=$('#verification-panel');if(verify)verify.outerHTML=verificationPanel();const discussion=$('[data-comment-list]');if(discussion){const v=videoBy(discussion.dataset.commentList);if(v)discussion.outerHTML=commentList(v)}}}};
async function optimizePostImage(file){if(!file||!/^image\/(jpeg|png|webp|gif|bmp|avif)$/.test(file.type))throw Error('Выберите изображение JPG, PNG или WebP.');if(file.size>30*1024*1024)throw Error('Размер изображения не должен превышать 30 МБ.');const data=await readFile(file),img=await new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('Изображение не удалось открыть.'));image.src=data});const scale=Math.min(1,1280/Math.max(img.naturalWidth,img.naturalHeight)),canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(img.naturalWidth*scale));canvas.height=Math.max(1,Math.round(img.naturalHeight*scale));const ctx=canvas.getContext('2d');if(!ctx)throw Error('Обработка изображений недоступна.');ctx.drawImage(img,0,0,canvas.width,canvas.height);let quality=.82,result=canvas.toDataURL('image/webp',quality);while(result.length>240000&&quality>.4){quality-=.1;result=canvas.toDataURL('image/webp',quality)}return result}
const validateBeforeSocial=validateImport;
validateImport=function(data){
 if(data.socialVersion!==undefined&&data.socialVersion!==1)throw Error('Неизвестная версия сообщества.');
 const bad=()=>{throw Error('Некорректные социальные данные в резервной копии.');},finite=n=>Number.isFinite(n)&&n>=0,shortText=(s,n)=>typeof s==='string'&&s.length<=n,identifier=s=>typeof s==='string'&&/^[-a-zA-Z0-9]+$/.test(s),validImage=s=>s==null||typeof s==='string'&&(/^(asset:[a-zA-Z0-9-]+|data:image\/(webp|png|jpeg|gif)[;,])/.test(s));
 if(data.community){if(!Array.isArray(data.community.posts)||data.community.posts.length>140)bad();const ids=new Set();for(const p of data.community.posts){if(!identifier(p.id)||ids.has(p.id)||!data.channels.some(c=>c.id===p.channelId)||!['text','image','poll'].includes(p.type)||!shortText(p.text,3000)||!validImage(p.image)||!Array.isArray(p.options)||!Array.isArray(p.weights)||p.options.length!==p.weights.length||!Array.isArray(p.history)||p.history.length>40)bad();ids.add(p.id);for(const k of ['publishedAt','realCreatedAt','reach','likes','votes','simulatedVotes','voteCarry','seed','quality','notifiedReach','notifiedVotes'])if(!finite(p[k]))bad();if(p.type==='poll'){if(p.options.length<2||p.options.length>4||new Set(p.options.map(o=>o.id)).size!==p.options.length||p.weights.some(n=>!finite(n))||Math.abs(p.weights.reduce((s,n)=>s+n,0)-1)>1e-6)bad();for(const o of p.options)if(!identifier(o.id)||!shortText(o.text,120)||!Number.isSafeInteger(o.votes)||o.votes<0)bad();if(p.options.reduce((s,o)=>s+o.votes,0)!==p.votes||p.userVote&&!p.options.some(o=>o.id===p.userVote)||p.votes!==p.simulatedVotes+(p.userVote?1:0))bad()}else if(p.options.length||p.weights.length)bad();for(const h of p.history)if(!finite(h.at)||!finite(h.reach))bad()}if(data.community.posts.filter(p=>p.channelId==='me').length>80)bad()}
 if(data.social&&(!Array.isArray(data.social.eventKeys)||data.social.eventKeys.length>1200||data.social.eventKeys.some(k=>!shortText(k,300))||!finite(data.social.channelMilestone)))bad();
 for(const v of data.videos||[]){if(v.contentFacts!==undefined&&!shortText(v.contentFacts,4000))bad();if(v.visibleComments!==undefined){if(!Array.isArray(v.visibleComments)||v.visibleComments.length>SOCIAL_LIMITS.comments)bad();for(const x of v.visibleComments){if(!identifier(x.id)||!shortText(x.author,100)||!shortText(x.text,1400)||!shortText(x.fact,360)||!finite(x.at)||!finite(x.likes)||!Array.isArray(x.replies)||x.replies.length>12)bad()}}for(const x of [...(v.visibleComments||[]),...(v.localComments||[])]){if(x.replies&&(!Array.isArray(x.replies)||x.replies.length>12))bad();for(const r of x.replies||[])if(!identifier(r.id)||!shortText(r.text,1000)||!shortText(r.author,100)||!finite(r.at))bad()}}
 for(const c of data.channels||[]){const p=c.audienceProfile;if(p?.pollPreferences){const genres=p.pollPreferences.genres,topics=p.pollPreferences.topics;if(!genres||!topics||['фантастик','ужас','драм','комеди'].some(k=>!finite(genres[k]))||CATEGORIES.some(k=>!finite(topics[k])))bad()}if(c.verification){const r=c.verification;if(!['none','pending','verified','reapply','rejected'].includes(r.status)||c.verified&&r.status!=='verified'||r.status==='pending'&&(!finite(r.reviewAt)||!finite(r.submittedAt)||!shortText(r.name,80)))bad()}if(p?.demographics){for(const [key,size]of [['age',7],['countries',6],['devices',4]]){const a=p.demographics[key];if(!Array.isArray(a)||a.length!==size||a.some(n=>!finite(n))||Math.abs(a.reduce((s,n)=>s+n,0)-1)>1e-6)bad()}if(!finite(p.demographics.since))bad();if(p.demographics.base)for(const [key,size]of [['age',7],['countries',6],['devices',4]]){const a=p.demographics.base[key];if(!Array.isArray(a)||a.length!==size||a.some(n=>!finite(n))||Math.abs(a.reduce((s,n)=>s+n,0)-1)>1e-6)bad()}}for(const row of [...(p?.history||[]),...(p?.lifetime?[p.lifetime]:[])])for(const e of Object.values(row.demographics||{})){if(!finite(e.views))bad();for(const [key,size]of [['age',7],['countries',6],['devices',4]]){if(!Array.isArray(e[key])||e[key].length!==size||e[key].some(n=>!finite(n))||Math.abs(e[key].reduce((s,n)=>s+n,0)-e.views)>1e-5*Math.max(1,e.views))bad()}if(!e.activity||Object.entries(e.activity).some(([k,n])=>!/^\d+$/.test(k)||+k>167||!finite(n))||Math.abs(Object.values(e.activity).reduce((s,n)=>s+n,0)-e.views)>1e-5*Math.max(1,e.views))bad()}}
 return validateBeforeSocial(data)
};
// Divisor apportionment keeps every option's cumulative vote count monotonic.
function monotonicAllocation(total,weights){if(!total)return weights.map(()=>0);let low=0,high=1;for(let i=0;i<60;i++){const middle=(low+high)/2,sum=weights.reduce((s,w)=>s+Math.floor(w/middle),0);if(sum>total)low=middle;else high=middle}const out=weights.map(w=>Math.floor(w/high));let remainder=total-out.reduce((a,b)=>a+b,0);while(remainder-->0){let best=0;for(let i=1;i<weights.length;i++)if(weights[i]/(out[i]+1)>weights[best]/(out[best]+1))best=i;out[best]++}return out}
const batchBeforeSocial=simulationBatch;
simulationBatch=function*(ms){const previous=socialBatchKey;socialBatchKey=ms>HOUR?'offline:'+RealClock.now():null;try{yield* batchBeforeSocial(ms)}finally{socialBatchKey=previous}};
function optionPreference(c,text){const p=c.audienceProfile;p.pollPreferences??={genres:Object.fromEntries(['фантастик','ужас','драм','комеди'].map(k=>[k,.5+seeded(c.seed,'genre:'+k)])),topics:Object.fromEntries(CATEGORIES.map(k=>[k,(p.topicAffinity[k]||.2)*.7+.3+seeded(c.seed,'community:'+k)*.2]))};const value=text.toLocaleLowerCase('ru');for(const [word,weight]of Object.entries(p.pollPreferences.genres))if(value.includes(word))return weight;const categories={Игры:/игр|механик|прохожд|тактик/,Технологии:/технолог|устройств|тест|принцип/,Обучение:/объясн|уч|задач|пример/,Музыка:/музык|ритм|мелоди|жанр/,Дизайн:/цвет|композиц|типограф|дизайн/,Путешествия:/маршрут|дорог|культур|путешеств/,Спорт:/спорт|трениров|техник/,Подкасты:/гост|разговор|слушател/,Новости:/новост|обзор/,Развлечения:/съём|съем|истори|вопрос/};const found=Object.entries(categories).find(([,re])=>re.test(value));return(found?p.pollPreferences.topics[found[0]]:.5)+seeded(c.seed,'answer:'+value)*.45}
