// Large journals are committed to IndexedDB before replacing the legacy storage entry.
const STATE_INLINE_LIMIT=3*1024*1024;let stateDatabase=null,stateDatabaseOpening=null,stateSaveRevision=0,stateWriteQueue=Promise.resolve();
function packState(s){const copy=JSON.parse(JSON.stringify(s));delete copy.userChannel;for(const v of copy.videos){if(!v.history.length)continue;const columns=[...new Set(v.history.flatMap(h=>Object.keys(h)))];v.historyColumns=columns;v.historyRows=v.history.map(h=>columns.map(k=>h[k]||0));v.history=[]}return copy}
function unpackState(s){if(s?.videos)for(const v of s.videos)if(Array.isArray(v.historyColumns)&&Array.isArray(v.historyRows)){v.history=v.historyRows.map(row=>Object.fromEntries(v.historyColumns.map((k,i)=>[k,row[i]||0])));delete v.historyColumns;delete v.historyRows}return s}
async function openStateDatabase(){if(stateDatabase)return stateDatabase;if(stateDatabaseOpening)return stateDatabaseOpening;stateDatabaseOpening=(async()=>{if(!globalThis.indexedDB)throw Error('IndexedDB недоступен');const db=await new Promise((resolve,reject)=>{const req=indexedDB.open('youtrube.state',1),timeout=setTimeout(()=>reject(Error('Не удалось открыть хранилище статистики')),3500);req.onupgradeneeded=()=>req.result.createObjectStore('snapshots');req.onsuccess=()=>{clearTimeout(timeout);resolve(req.result)};req.onerror=()=>{clearTimeout(timeout);reject(req.error)};req.onblocked=()=>{clearTimeout(timeout);reject(Error('Хранилище статистики заблокировано'))}});db.onversionchange=()=>{db.close();stateDatabase=null;stateDatabaseOpening=null};stateDatabase=db;return db})().catch(e=>{stateDatabaseOpening=null;throw e});return stateDatabaseOpening}
async function loadStateForBoot(){let raw;try{raw=localStorage.getItem(CONFIG.key)}catch{return loadState()}if(!raw)return loadState();const entry=JSON.parse(raw);if(!entry.snapshotRef)return loadState();if(entry.version!==3||entry.storage!=='indexeddb')throw Error('Неизвестный формат сохранения');const db=await openStateDatabase(),serialized=await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readonly'),req=tx.objectStore('snapshots').get(entry.snapshotRef);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});if(!serialized)throw Error('Снимок статистики отсутствует. Исходная запись сохранена.');const loaded=unpackState(JSON.parse(serialized));return validateImport(loaded)}
function storageMessage(text){const el=$('#storage-notice');if(el)el.innerHTML=text?`<div class="storage-error" role="alert">${esc(text)}</div>`:''}
function writeInlineState(serialized){try{localStorage.setItem(CONFIG.key,serialized);storageFailed=false;storageMessage('');return true}catch{storageFailed=true;return false}}
function queueStateSnapshot(serialized,revision){const job=stateWriteQueue.catch(()=>{}).then(async()=>{try{const db=await openStateDatabase();const id=uid('snapshot');await new Promise((resolve,reject)=>{const tx=db.transaction('snapshots','readwrite');tx.objectStore('snapshots').put(serialized,id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error)});if(revision!==stateSaveRevision)return true;const oldRaw=localStorage.getItem(CONFIG.key),oldRef=oldRaw?JSON.parse(oldRaw).snapshotRef:null;if(!writeInlineState(JSON.stringify({version:3,storage:'indexeddb',snapshotRef:id})))throw Error('Недоступно хранилище настроек браузера');try{const tx=db.transaction('snapshots','readwrite'),store=tx.objectStore('snapshots'),req=store.openKeyCursor();req.onsuccess=()=>{const cursor=req.result;if(cursor){if(cursor.key!==id&&cursor.key!==oldRef)store.delete(cursor.key);cursor.continue()}}}catch{}return true}catch{storageFailed=true;storageMessage('Не удалось сохранить статистику. Текущая запись сохранена; экспортируйте резервную копию в настройках.');return false}});stateWriteQueue=job;return job}
async function persistState(){clearTimeout(saveTimer);saveTimer=null;const revision=++stateSaveRevision,serialized=JSON.stringify(packState(state));if(serialized.length<=STATE_INLINE_LIMIT&&writeInlineState(serialized))return true;return queueStateSnapshot(serialized,revision)}
saveState=function(immediate=false){if(!immediate){if(!saveTimer)saveTimer=setTimeout(()=>saveState(true),2500);return true}clearTimeout(saveTimer);saveTimer=null;const revision=++stateSaveRevision,serialized=JSON.stringify(packState(state));if(serialized.length<=STATE_INLINE_LIMIT&&writeInlineState(serialized))return true;queueStateSnapshot(serialized,revision);return false};
const validateImportV2=validateImport;
function finiteRange(n,min=0,max=1e16){return Number.isFinite(n)&&n>=min&&n<=max}
function validCounts(map){return map&&typeof map==='object'&&!Array.isArray(map)&&Object.values(map).every(n=>finiteRange(n))}
validateImport=function(data){
 unpackState(data);const imported=validateImportV2(data);
 for(const c of imported.channels){
  const p=c.audienceProfile;
  if(!Array.isArray(p.cohorts)||!p.cohorts.length||p.cohorts.length>32||new Set(p.cohorts.map(co=>co.id)).size!==p.cohorts.length||!Array.isArray(p.history)||p.history.length>2401)throw Error('Некорректная модель аудитории');
  for(const k of ['trackingSince','baselineViewers','lastDecayAt','lastPublishedAt'])if(!finiteRange(p[k]))throw Error('Некорректная история аудитории');
  for(const k of ['returnProbability','topicTolerance','audienceTrust','longTermSatisfaction','nicheConsistency','loyalty'])if(!finiteRange(p[k],0,1))throw Error('Некорректные предпочтения аудитории');
  for(const k of ['subscribePropensity','likePropensity'])if(!finiteRange(p[k],0,2))throw Error('Некорректная склонность аудитории к взаимодействиям');
  if(!p.formatPreference||!finiteRange(p.formatPreference.short,0,1)||!finiteRange(p.formatPreference.video,0,1)||Math.abs(p.formatPreference.short+p.formatPreference.video-1)>1e-6||!p.topicAffinity||CATEGORIES.some(cat=>!finiteRange(p.topicAffinity[cat],0,1)))throw Error('Некорректные интересы аудитории');
  for(const co of p.cohorts){if(typeof co.id!=='string'||!finiteRange(co.at)||!['video','short','mixed'].includes(co.format))throw Error('Некорректная группа зрителей');for(const k of AUDIENCE_GROUPS)if(!finiteRange(co.groups?.[k])||!finiteRange(co.subscribed?.[k])||co.subscribed[k]>co.groups[k]+1e-6)throw Error('Некорректный состав аудитории')}
  if(Math.abs(audienceTotals(c).subscribers-c.subscribers)>Math.max(1e-5,c.subscribers*1e-7))throw Error('Подписчики не согласованы с аудиторией');
  for(const row of [...p.history,...(p.lifetime?[p.lifetime]:[])]){
   if(!finiteRange(row.at)||!row.byFormat||!validCounts(row.pools)||!validCounts(row.stocks))throw Error('Некорректная аналитика аудитории');
   for(const f of ['video','short']){const x=row.byFormat[f];for(const k of ['views','newViewers','subscriberViews','repeatViews','subscribersGained'])if(!finiteRange(x?.[k]))throw Error('Некорректная статистика зрителей');if(!validCounts(x.reach)||!validCounts(x.births)||x.subscriberViews>x.views+1e-6||x.repeatViews+x.newViewers>x.views+1e-6)throw Error('Некорректная история зрителей')}
  }
 }
 for(const v of imported.videos){
  const d=v.distribution;if(!d.feedback||!Array.isArray(d.waves)||d.waves.length>8||!['normal','failed','slow','viral','evergreen'].includes(d.scenario))throw Error('Некорректные параметры распространения');
  for(const k of ['samples','reachScale','nextRetestAt','startedAt','lastDecisionAt','initialAudience','initialFit','legacyViews','legacyWatchSeconds'])if(!finiteRange(d[k]))throw Error('Некорректные параметры алгоритма');
  for(const k of ['ctr','retention','viewedRate','completion','rewatch','engagement','satisfaction','audienceFit','score'])if(!finiteRange(d.feedback[k],0,3))throw Error('Некорректная обратная связь');
  for(const w of d.waves)if(!finiteRange(w.at)||!finiteRange(w.duration,1)||!finiteRange(w.strength)||!['related','search','retest'].includes(w.reason))throw Error('Некорректная история повторного продвижения');
  for(const k of ['newViewers','returningVisits','uniqueViewers','subscriberViews','nonSubscriberViews','repeatViews','impressionClicks','trackedViews'])if(!finiteRange(v.audienceStats?.[k]))throw Error('Некорректная статистика публикации');
 }
 return imported;
};
const seedShortEcosystemV2=seedShortEcosystem;
seedShortEcosystem=function(){const seeded=state.ecosystem.shortsSeeded;seedShortEcosystemV2();if(!seeded){for(const c of state.channels)if(c.id!=='me'){c.audienceProfile=createAudienceProfile(c,state);refreshAudience(c)}for(const v of state.videos)initializeDistribution(v,channelBy(v.channelId))}};
