const fs=require('node:fs'),vm=require('node:vm'),{performance}=require('node:perf_hooks');
const script=fs.readFileSync('outputs/index.html','utf8').match(/<script>([\s\S]*?)<\/script>/)[1],source=script.slice(0,script.indexOf('// APP INIT'));new vm.Script(script);
const snapshots=new Map();let failSnapshot=false,failPointer=false;
const storage={data:null,getItem(){return this.data},setItem(k,v){if(failPointer)throw Error('quota');this.data=v}};
const document={addEventListener(){},querySelector(){return{innerHTML:'',textContent:'',querySelector(){return null},querySelectorAll(){return[]},classList:{remove(){},toggle(){}}}},querySelectorAll(){return[]},body:{classList:{remove(){},toggle(){}}}};
const db={createObjectStore(){},close(){},transaction(){const tx={};tx.objectStore=()=>({put(value,key){if(failSnapshot)throw Error('quota');snapshots.set(key,value);queueMicrotask(()=>tx.oncomplete?.())},get(key){const req={};queueMicrotask(()=>{req.result=snapshots.get(key);req.onsuccess?.()});return req},delete(key){snapshots.delete(key)},openKeyCursor(){const req={},keys=[...snapshots.keys()];let i=0;const next=()=>queueMicrotask(()=>{req.result=i<keys.length?{key:keys[i++],continue:next}:null;req.onsuccess?.()});next();return req}});return tx}};
const indexedDB={open(){const req={result:db};queueMicrotask(()=>req.onsuccess?.());return req}};
const context=vm.createContext({document,window:{addEventListener(){},scrollTo(){}},location:{hash:'#/settings'},localStorage:storage,indexedDB,Date,performance,console,setInterval(){},setTimeout(){return 1},clearTimeout(){},matchMedia(){return{matches:false}},crypto:globalThis.crypto,URLSearchParams,Map,Set});
const setup=`state=migrateState(freshState());state.videos=[];state.ecosystem.shortsSeeded=true;for(const c of state.channels)c.nextUploadAt=state.simulation.now+10000*DAY;window.testAccess={setClock:()=>{RealClock.now=()=>Date.now()},persist:persistState,load:loadStateForBoot,pack:()=>JSON.stringify(packState(state)),alter:()=>{state.channels[0].description+='changed';},large:()=>{state.channels[0].description='x'.repeat(4*1024*1024);},validate:validateImport,state:()=>state,bootAdvance:settleBootTime,replace:x=>{state=JSON.parse(JSON.stringify(x))},syncAdvance:ms=>advance(ms),example:()=>{const v=makeNPCPublication(channelBy('me'),1,state.simulation.now,'video');state.videos.push(v);const end=RealClock.now()+3600e3;RealClock.now=()=>end;advance(3600e3);return JSON.parse(JSON.stringify(state))}};`;
vm.runInContext(source+setup+'\n})();',context);const api=context.window.testAccess;
(async()=>{const results=[];const check=(b,m)=>{if(!b)throw Error(m);results.push(m)};
check(await api.persist(),'Small save commits inline');check(!JSON.parse(storage.data).snapshotRef,'Small journal keeps the existing localStorage key');api.large();check(await api.persist(),'Large save waits for a committed IndexedDB transaction');let ptr=JSON.parse(storage.data);check(ptr.storage==='indexeddb'&&snapshots.has(ptr.snapshotRef),'Storage pointer refers to an existing snapshot');const loaded=await api.load();check(loaded.channels[0].description===api.state().channels[0].description,'Snapshot loader restores the large state exactly');
const original=storage.data;api.alter();failSnapshot=true;check(!await api.persist()&&storage.data===original,'Failed IndexedDB write preserves the previous durable pointer');failSnapshot=false;failPointer=true;check(!await api.persist()&&storage.data===original,'Failed pointer commit preserves the previous durable save');failPointer=false;check(await api.persist(),'Retry commits after a storage failure');await Promise.resolve();check(snapshots.size<=2,'Snapshot cleanup retains at most two successful checkpoints');const latest=JSON.parse(storage.data);snapshots.delete(latest.snapshotRef);let rejected=false;try{await api.load()}catch{rejected=true}check(rejected&&storage.data===JSON.stringify(latest),'Missing snapshot produces an error without resetting existing data');

const example=api.example();check(api.validate(JSON.parse(JSON.stringify(example))).version===3,'Complete v3 telemetry passes backup validation');const malformed=[data=>delete data.channels[0].audienceProfile.formatPreference,data=>data.channels[0].audienceProfile.history[0].byFormat.video.reach.bad=-1,data=>delete data.videos[0].audienceStats.trackedViews];for(const [i,mutate] of malformed.entries()){const data=JSON.parse(JSON.stringify(example));mutate(data);let caught=false;try{api.validate(data)}catch{caught=true}check(caught,'Incomplete or invalid v3 telemetry rejected before restore '+(i+1));}

const fixedNow=Date.now();context.Date=class extends Date{static now(){return fixedNow}};api.setClock();context.setTimeout=(callback,delay)=>{if(delay===0)queueMicrotask(callback);return 1};const beforeBoot=JSON.parse(JSON.stringify(example));beforeBoot.simulation.lastSimulationTimestamp=fixedNow-10000;api.replace(beforeBoot);api.syncAdvance(10000);const syncVideos=JSON.stringify(api.state().videos),syncChannels=JSON.stringify(api.state().channels);api.replace(beforeBoot);await api.bootAdvance();check(JSON.stringify(api.state().videos)===syncVideos&&JSON.stringify(api.state().channels)===syncChannels,'Cooperative offline loading uses exactly the same simulation as synchronous updates');
console.log(JSON.stringify({passed:results.length,results}));fs.writeFileSync('work/v3-storage-results.json',JSON.stringify({passed:results.length,results},null,2));})().catch(e=>{console.error(e);process.exitCode=1});
