exec(open('work/test_engine.py').read().split('result=run(prefix+body+checks)')[0])
from pathlib import Path
checks2=r'''
const results=[];function assert(b,m){if(!b)throw Error(m);results.push(m)}
state=freshState();state.version=1;state.userChannel.name='Сохранённый канал';state.userChannel.avatar='data:image/png;base64,a';state.userChannel.banner='data:image/png;base64,b';state.userChannel.subscribers=143;state.preferences.theme='dark';state.subscriptions=['c0'];state.history=[{videoId:state.videos[0].id,timestamp:state.simulation.now}];state.user.reactions[state.videos[0].id]='like';const legacy=makeVideo(state.userChannel,0,state.simulation.now);legacy.id='legacy-own';legacy.thumbnail='data:image/png;base64,c';legacy.views=1234.5;legacy.likes=94;legacy.comments=8;legacy.watchSeconds=30000;state.videos.push(legacy);const savedId=state.videos[0].id;const original=JSON.parse(JSON.stringify(state));state=migrateState(state);
assert(state.version===2&&state.videos.every(v=>v.type==='video'),'V1 content receives video type without regeneration');assert(videoBy('legacy-own').views===1234.5&&videoBy('legacy-own').likes===94&&videoBy('legacy-own').comments===8,'Migration preserves publication statistics');assert(state.userChannel.subscribers===143&&state.userChannel.name==='Сохранённый канал','Migration preserves channel and subscriber total');assert(state.userChannel.avatar===original.userChannel.avatar&&videoBy('legacy-own').thumbnail===original.videos.at(-1).thumbnail,'Inline legacy images retained before durable migration');assert(state.preferences.theme==='dark'&&state.subscriptions[0]==='c0'&&state.history[0].videoId===savedId&&state.user.reactions[savedId]==='like','Preferences, subscriptions, reactions and history retained');const length=state.videos.length,nextUpload=state.channels[1].nextUploadAt;state=migrateState(state);assert(state.videos.length===length&&state.channels[1].nextUploadAt===nextUpload,'Metadata migration is idempotent');assert(validateImport(original).version===2,'V1 backup remains importable');seedShortEcosystem();const once=state.videos.length;seedShortEcosystem();assert(state.videos.length===once&&state.videos.filter(isShort).length===40,'Seeded Shorts ecosystem added exactly once');assert(state.userChannel.subscribers===143&&videoBy('legacy-own').views===1234.5,'NPC Shorts do not alter existing user totals');
const own=makeNPCPublication(state.userChannel,300,state.simulation.now,'short');own.id='own-short';state.videos.push(own);assert(own.views===0&&own.shortStats.shownInFeed===0&&own.watchSeconds===0,'Own Shorts begin with zero views/exposure/watch time');const priv=makeNPCPublication(state.userChannel,301,state.simulation.now,'short');priv.id='private-short';priv.visibility='private';state.videos.push(priv);const unlisted=makeNPCPublication(state.userChannel,302,state.simulation.now,'short');unlisted.id='unlisted-short';unlisted.visibility='unlisted';state.videos.push(unlisted);advance(3600e3);
const s=own.shortStats;assert(s.shownInFeed>0&&own.views>0,'Feed exposure produces gradual Shorts views');assert(Math.abs(s.shownInFeed-s.viewedExposures-s.swipedAway)<1e-8,'Viewed and swiped exposures sum to shown-in-feed');assert(Math.abs(own.views-s.viewedExposures-s.rewatches)<1e-8,'Shorts views include measured initial views and repeats');assert(own.impressions===0,'Shorts exposure is separate from ordinary impressions');assert(Math.abs(own.watchSeconds-own.views*own.shortParams.averageViewDuration)<1e-7,'Shorts watch time derives from views and duration');assert(Math.abs(own.traffic.reduce((a,b)=>a+b)-own.views)<1e-7,'Shorts traffic sources sum to views');assert(own.likes<=own.views*.1&&own.dislikes<=own.views*.02&&own.comments<=own.views*.011,'Shorts engagement stays coupled to audience size');assert(priv.views===0&&unlisted.views===0,'Private and unlisted Shorts excluded from simulation');assert(Math.abs(own.history.reduce((n,h)=>n+h.shownInFeed,0)-s.shownInFeed)<1e-7,'Shorts history stores feed exposures consistently');assert(Math.abs(aggregate([own],0).viewedRate-own.shortParams.viewedRate)<1e-8,'Viewed ratio derives from exposure outcomes');
const avgOptions=Array.from({length:200},(_,i)=>makeNPCPublication(state.userChannel,i+400,state.simulation.now,'short'));assert(avgOptions.some(v=>v.shortParams.averageViewDuration>v.duration),'Repeat viewing can produce percentage viewed above 100%');assert(Math.max(...avgOptions.map(v=>v.shortParams.potential))>12&&Math.min(...avgOptions.map(v=>v.shortParams.potential))<.2,'Seeded Shorts potential has a long tail');const sameA=makeNPCPublication(state.userChannel,600,state.simulation.now,'short'),sameB=makeNPCPublication(state.userChannel,600,state.simulation.now,'short');assert(JSON.stringify(sameA.shortParams)===JSON.stringify(sameB.shortParams),'Shorts fate is stable for the same publication seed');
const mixed=aggregate(mine(),0),regular=mine().filter(v=>!isShort(v));assert(Math.abs(mixed.views-mine().reduce((n,v)=>n+v.views,0))<1e-7,'Channel analytics combines both formats');assert(Math.abs(mixed.ctr-regular.reduce((n,v)=>n+v.views,0)/regular.reduce((n,v)=>n+v.impressions,0))<1e-8,'Shorts views do not inflate ordinary video CTR');assert(shortRecommendations().every(isShort)&&recommendations(null,'Все').every(v=>!isShort(v)),'Recommendation engines keep formats separate');assert(new Set(shortRecommendations().map(v=>v.id)).size===shortRecommendations().length,'Shorts recommendation list contains no duplicates');
const before=new Set(state.videos.map(v=>v.id));advance(3*864e5);const newNPC=state.videos.filter(v=>!before.has(v.id)&&v.channelId!=='me');assert(newNPC.length>0&&newNPC.length<=12,'NPC publications arrive in capped simulated-time batches');assert(new Set(newNPC.map(v=>v.publishedAt)).size>1,'NPC authors publish on different clocks');assert(state.channels.filter(c=>c.id!=='me').every(c=>c.nextUploadAt>state.simulation.now),'Offline backlog does not trigger endless publication storms');
const protectedId=state.videos.find(v=>v.channelId==='c0').id;state.history.unshift({videoId:protectedId,timestamp:state.simulation.now});for(let i=0;i<400;i++)state.videos.push(makeNPCPublication(channelBy('c1'),700+i,state.simulation.now,'video'));syncChannelTotals();const beforeTotal=channelBy('c1').totalViews,owned=mine().map(v=>v.id);pruneNPC();syncChannelTotals();assert(state.videos.filter(v=>v.channelId!=='me').length<=280,'NPC content pool is bounded');assert(!!videoBy(protectedId)&&owned.every(videoBy),'Archival preserves history references and own publications');assert(Math.abs(beforeTotal-channelBy('c1').totalViews)<1e-7,'Archival preserves NPC channel lifetime totals');assert(state.subscriptions.includes('c0'),'Archival preserves subscriptions');
advance(30*864e5);assert(own.history.every(h=>Number.isFinite(h.views)&&Number.isFinite(h.shownInFeed)),'Long offline batches leave finite Shorts analytics');assert(Math.abs(own.history.reduce((n,h)=>n+h.views,0)-own.views)<1e-6,'Bucket aggregation preserves Shorts view totals');
const refs=JSON.parse(JSON.stringify(state));refs.videos[0].type='bad"onclick';let rejected=false;try{validateImport(refs)}catch{rejected=true}assert(rejected,'Invalid imported content types rejected');

assert(Math.abs(series([own],7,'views').reduce((n,p)=>n+p.value,0)-aggregate([own],7).views)<1e-6,'Chart daily buckets match selected-period card totals');
const storedRaw=JSON.stringify(state);localStorage.data='{"version":99}';let refused=false;try{loadState()}catch{refused=true}assert(refused&&localStorage.data==='{"version":99}','Unreadable future schemas retained without overwriting storage');localStorage.data=storedRaw;
const fail=makeNPCPublication(state.userChannel,1210,state.simulation.now,'short');fail.id='weak-short';Object.assign(fail.shortParams,{shortsQuality:.15,audienceFit:.3,viewedRate:.3,swipeAwayRate:.7,completionRate:.25,rewatchRate:.02,averageViewDuration:fail.duration*.5,engagementRate:.035,potential:.3});initializeShort(fail);state.videos.push(fail);advance(7*864e5);assert(fail.views>40&&fail.views<500,'Weak Shorts can stall with only a small test audience');
window.upgradeResult=JSON.stringify({passed:results.length,results});
})();window.upgradeResult;
'''
result=run(prefix+body+checks2)
Path('work/upgrade-results.json').write_text(result)
print(result)
