const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),{performance}=require('node:perf_hooks');
const html=fs.readFileSync('outputs/index.html','utf8'),script=html.match(/<script>([\s\S]*?)<\/script>/)[1];new vm.Script(script);
const source=script.slice(0,script.indexOf('// APP INIT'));
let now=Date.UTC(2026,9,8,12),clock=class extends Date{static now(){return now}};
const storage={data:null,getItem(){return this.data},setItem(k,v){this.data=v}};
const document={addEventListener(){},querySelector(){return{innerHTML:'',textContent:'',querySelector(){return null},querySelectorAll(){return[]},classList:{remove(){},toggle(){}}}},querySelectorAll(){return[]},body:{classList:{remove(){},toggle(){}}}};
const context=vm.createContext({document,window:{addEventListener(){},scrollTo(){}},location:{hash:'#/studio/content'},localStorage:storage,Date:clock,performance,console,setInterval(){},setTimeout(){return 1},clearTimeout(){},matchMedia(){return{matches:false}},crypto:globalThis.crypto,URLSearchParams,Map,Set});
context.setWall=t=>now=t;
const checks=`
function tickTest(ms){setWall(RealClock.now()+ms);advance(ms)}const results=[];function check(b,m){if(!b)throw Error(m);results.push(m)}function close(a,b,tol=1e-6){return Math.abs(a-b)<=tol*Math.max(1,Math.abs(a),Math.abs(b))}
function fresh(){state=migrateState(freshState());state.videos=[];for(const c of state.channels)c.nextUploadAt=state.simulation.now+10000*DAY;state.ecosystem.shortsSeeded=true;return channelBy('me')}
function own(i=1,type='video',quality=.7){const c=channelBy('me'),v=makeNPCPublication(c,i,state.simulation.now,type);v.id='own-'+i;Object.assign(v.params,{contentQuality:quality,clickability:quality,retentionPotential:.16+quality*.68,audienceFit:.2+quality*.75,competition:.5,potential:1.3,evergreenFactor:.85});if(isShort(v))Object.assign(v.shortParams,{shortsQuality:quality,potential:1.3});state.videos.push(v);initializeDistribution(v,c);v.distribution.scenario='normal';return v}
let c=fresh(),v=own();tickTest(2*3600e3);check(v.views>0&&c.subscribers>0&&c.audienceProfile.newViewers>0,'A: zero-subscriber channel receives a test audience and conversions');
const smallFirst=v.views; c=fresh();c.subscribers=100000;c.audienceProfile=createAudienceProfile(c,state);refreshAudience(c);v=own();tickTest(2*3600e3);check(v.views>smallFirst&&v.views<100000,'B: active audience increases launch reach without guaranteed subscriber views');
c=fresh();let weak=own(1,'video',.12),good=own(2,'video',.94);weak.distribution.scenario='failed';good.distribution.scenario='viral';let daily=[];for(let i=0;i<7;i++){const before=good.views;tickTest(DAY);daily.push(good.views-before)}check(weak.views<good.views*.12&&weak.distribution.reachScale<.6,'C: weak engagement limits recommendations');check(good.distribution.reachScale>weak.distribution.reachScale*5&&daily[1]>daily[0],'D: strong content expands gradually after test feedback');check(daily.every(x=>x>0&&x<500000),'D: viral growth follows bounded exposure, without a million-view jump');
check(close(good.watchSeconds,good.history.reduce((n,h)=>n+(h.watchSeconds||0),0)),'Watch duration and hourly/daily history remain consistent');check(close(good.traffic.reduce((a,b)=>a+b,0),good.views),'All ordinary traffic sources sum to views');check(close(aggregate([good],0).ctr,good.audienceStats.impressionClicks/good.impressions),'CTR uses actual impression clicks instead of external views');check(good.history.some(h=>(h.impressionClicks||0)>0),'Click evidence persisted in analytical history');const startCtr=good.distribution.feedback.ctr;good.distribution.reachScale=20;tickTest(DAY);check(good.distribution.feedback.ctr!==startCtr,'CTR adapts when distribution reaches broader audience');
const pool=audienceTotals(c),sub=c.subscribers;const oldRegular=pool.regular,oldDormant=pool.dormant;state.videos.forEach(x=>x.visibility='private');tickTest(30*DAY);check(audienceTotals(c).regular<oldRegular&&audienceTotals(c).dormant>oldDormant,'F: inactivity moves viewers between existing audience groups');check(close(audienceTotals(c).total,pool.total)&&close(c.subscribers,sub),'F: inactivity conserves people and subscriptions');state.videos.forEach(x=>x.visibility='public');good.publishedAt=state.simulation.now;good.distribution.initialAudience=formatActive(c,'video');const beforeRecovery=audienceTotals(c).dormant,recoveryViewsBefore=good.views;tickTest(DAY);check(good.views>recoveryViewsBefore&&audienceTotals(c).casual>0,'F: successful new exposure can reactivate known viewers');
c=fresh();v=own(5);tickTest(8*DAY);let before=v.views,searchBefore=v.traffic[2];v.distribution.waves.push({at:state.simulation.now,duration:2*DAY,strength:2,reason:'search'});tickTest(DAY);check(v.views>before&&v.traffic[2]>searchBefore&&phase(v)==='Повторное продвижение','E: rediscovery increases real exposure and matching traffic sources');const oldWaveCount=v.distribution.waves.length;let triggered=false;for(let i=0;i<500&&!triggered;i++){v.seed=i;v.distribution.nextRetestAt=state.simulation.now;v.distribution.lastRediscoveryDay=-1;rediscover(v,c,state.simulation.now);triggered=v.distribution.waves.length>oldWaveCount}check(triggered,'E: organic retest mechanism can trigger a rare second wave');
c=fresh();const short=own(8,'short',.9),long=own(9,'video',.9);tickTest(3*DAY);const s=short.shortStats;check(close(s.shownInFeed,s.viewedExposures+s.swipedAway),'G: Shorts exposure splits into viewed and swiped outcomes');check(close(short.views,s.viewedExposures+s.rewatches)&&close(short.traffic.reduce((a,b)=>a+b,0),short.views),'G: repeat views and traffic remain consistent');check(short.impressions===0&&short.distribution.feedback.completion>0,'G: Shorts engine learns completion separately from thumbnail clicks');check(!close(short.views,long.views,.01),'G: Shorts and ordinary videos follow different curves');
const ap=c.audienceProfile,totals=audienceTotals(c);check(close(totals.subscribers,c.subscribers),'Subscription status is distributed inside audience groups');check(ap.cohorts.every(co=>AUDIENCE_GROUPS.every(k=>co.groups[k]>=0&&co.subscribed[k]>=0&&co.subscribed[k]<=co.groups[k]+1e-7)),'Audience groups and subscription subsets stay nonnegative and bounded');check(close(totals.total,ap.baselineViewers+ap.history.reduce((n,h)=>n+h.newViewers,0)+(ap.lifetime?.newViewers||0)),'Audience is created only by genuinely new viewers');const m=audienceMetrics(c,3);check(m.uniqueViewers<=m.views-m.repeatViews+1e-7&&close(m.uniqueViewers,m.newViewers+m.returningViewers),'Period unique estimate deduplicates returning audience and excludes repeats');check(close(m.subscriberViews+m.nonSubscriberViews,m.views),'Subscriber and non-subscriber view shares sum to views');
const onlyShort=c.audienceProfile.cohorts.filter(x=>x.format==='short');check(onlyShort.length>0&&onlyShort.every(co=>formatMatch(c,co,'video')<formatMatch(c,co,'short')),'Shorts acquisition does not guarantee active long-video audience');
const regularized=ap.cohorts.map(co=>[co,sumGroups(co.groups)]);for(const [co,total] of regularized){co.groups={new:0,casual:0,regular:total,dormant:0};co.subscribed={new:0,casual:0,regular:sumGroups(co.subscribed),dormant:0}}const beforeReturn=ap.totalViewers;for(let i=0;i<4;i++)tickTest(DAY);const periodUnion=audienceMetrics(c,7),dailyUnique=[...new Set(ap.history.map(h=>localDay(h.at)))].slice(-7).reduce((n,t)=>n+audienceMetrics(c,1,'all',Math.min(RealClock.now(),nextLocalDay(t)-1)).uniqueViewers,0);check(periodUnion.uniqueViewers<=dailyUnique+1e-6,'Multi-day unique viewers use union occupancy rather than summing day totals');
state.simulation.speed=0;const freeze=short.views;state.simulation.lastSimulationTimestamp=Date.now()-DAY;settleTime();check(short.views===freeze,'H: pause stops offline simulation');state.simulation.speed=1;state.simulation.lastSimulationTimestamp=Date.now()-3600e3;settleTime();const afterOffline=short.views;settleTime();check(short.views===afterOffline&&afterOffline>freeze,'H: saved timestamp prevents repeated offline credit');
const saved=JSON.stringify(state);saveState(true);const viewsBefore=short.views,subsBefore=c.subscribers;state=loadState();check(videoBy(short.id).views===viewsBefore&&channelBy('me').subscribers===subsBefore,'I: storage round trip preserves publication and channel statistics');const migrationBefore=JSON.stringify(state);migrateState(state);check(JSON.stringify(state)===migrationBefore,'Schema-three migration is idempotent');
const legacy=JSON.parse(JSON.stringify(state));legacy.version=2;legacy.channels.forEach(x=>delete x.audienceProfile);legacy.videos.forEach(x=>{delete x.distribution;delete x.audienceStats;x.thumbnail='asset:original-image'});const legacyStats=legacy.videos.map(x=>[x.id,x.views,x.likes,x.comments,x.watchSeconds]),legacySubs=legacy.channels.map(x=>x.subscribers);migrateState(legacy);check(legacy.version===3&&JSON.stringify(legacy.videos.map(x=>[x.id,x.views,x.likes,x.comments,x.watchSeconds]))===JSON.stringify(legacyStats)&&JSON.stringify(legacy.channels.map(x=>x.subscribers))===JSON.stringify(legacySubs),'I: version-two migration preserves all existing statistics');check(legacy.videos.every(x=>x.thumbnail==='asset:original-image'),'I: image references preserved during migration');
for(const v of state.videos)v.visibility='public';for(let i=0;i<12;i++)tickTest(30*DAY);check(channelBy('me').audienceProfile.history.length<=2400&&channelBy('me').audienceProfile.cohorts.length<=30,'Audience history and cohort count remain bounded over years');check(mine().every(v=>v.history.length<=145&&Number.isFinite(v.views)),'Long running analytical history remains bounded and finite');

c=fresh();v=own(91,'video',.95);const reactivation=cohort('known-inactive',state.simulation.now-DAY,'video',20000,500,.2);reactivation.groups={new:0,casual:1000,regular:2000,dormant:17000};reactivation.subscribed={new:0,casual:25,regular:50,dormant:425};c.audienceProfile.cohorts=[reactivation];c.subscribers=500;refreshAudience(c);const dormantBefore=reactivation.groups.dormant;recordAudience(v,5000,5000,0,state.simulation.now,24);check(reactivation.groups.dormant<dormantBefore&&reactivation.groups.regular>2000,'F: measured return exposure transfers dormant to casual and casual to regular');
c=fresh();v=own(92);recordAudience(v,1,1,0,state.simulation.now,1/60,{local:true});recordAudience(v,1,1,1,state.simulation.now,1/60,{local:true,known:true});check(v.audienceStats.uniqueViewers===1&&v.audienceStats.repeatViews===1&&audienceMetrics(c,0).uniqueViewers===1,'Manual replay adds a repeat view, without creating another unique viewer');location.hash='#/studio/analytics?tab=audience';check(audienceChart(c).includes('<circle'),'All-time graph includes the migration day even when tracking starts at midday');check(btn('publish-type','Shorts','','','data-type="short"').includes('type="button"'),'Format selection cannot accidentally submit the publication form');
const subscriberChannel=channelBy('c0');subscriberChannel.audienceProfile.cohorts=[cohort('test',state.simulation.now,'mixed',100,50)];const testco=subscriberChannel.audienceProfile.cohorts[0];testco.groups={new:0,casual:0,regular:100,dormant:0};testco.subscribed={new:0,casual:0,regular:50,dormant:0};subscriberChannel.subscribers=50;toast=function(){};actions.subscribe({dataset:{id:'c0'}});check(testco.subscribed.regular===51&&testco.subscribed.casual===0,'Manual subscription stays within available audience-group capacity');actions.subscribe({dataset:{id:'c0'}});check(subscriberChannel.subscribers===50&&audienceTotals(subscriberChannel).subscribers===50,'Manual unsubscribe conserves the channel and audience subscriber totals');
c=fresh();v=own(93,'video',.12);v.distribution.scenario='failed';c.subscribers=100000;c.audienceProfile=createAudienceProfile(c,state);refreshAudience(c);v.distribution.initialAudience=formatActive(c,'video');tickTest(7*DAY);const largeWeakViews=v.views;c=fresh();v=own(94,'video',.94);v.distribution.scenario='viral';tickTest(7*DAY);check(v.views>largeWeakViews,'Strong small-channel content can overtake weak large-channel content');
const compact=packState(state),unpacked=unpackState(JSON.parse(JSON.stringify(compact)));const expected=JSON.parse(JSON.stringify(state));delete expected.userChannel;check(JSON.stringify(unpacked)===JSON.stringify(expected),'Column-packed storage preserves every history metric losslessly');

c=fresh();const lifecycleKinds=new Set();for(let i=0;i<160;i++){const candidate=makeNPCPublication(c,i,state.simulation.now,'video');candidate.params.evergreenFactor=.9;initializeDistribution(candidate,c);lifecycleKinds.add(candidate.distribution.scenario)}check(lifecycleKinds.size===5,'All five lifecycle families are reachable through seeded content parameters');v=own(96,'video',.94);v.distribution.scenario='slow';const slowDaily=[];for(let i=0;i<12;i++){const before=v.views;tickTest(DAY);slowDaily.push(v.views-before)}check(slowDaily[7]>slowDaily[0]*3,'Slow-burn publication discovers an audience after a weak first day');check(v.views>0&&slowDaily.at(-1)>0,'Long-term search and repeat exposure retain a nonzero tail');v.params.topicDemand=.15;const lessDemand=distributionRate(v,c,state.simulation.now);v.params.topicDemand=.95;check(distributionRate(v,c,state.simulation.now)>lessDemand,'Category demand changes exposure without overriding content feedback');

c=fresh();const manualShort=own(97,'short'),manualLong=own(98,'video');recordAudience(manualShort,1,1,0,state.simulation.now,1/60,{local:true});recordAudience(manualLong,1,1,0,state.simulation.now,1/60,{local:true});check(audienceMetrics(c,0,'video').uniqueViewers>0&&audienceMetrics(c,0).uniqueViewers===1,'Format filter includes a viewer who discovers Shorts and later watches long video without duplicating channel uniques');
c=fresh();v=own(99);tickTest(3600e3);player.viewRecorded=false;updateLive=function(){};recordWatch(v);check(close(aggregate([v],1).ctr,v.audienceStats.impressionClicks/v.impressions),'Manual clicks are included in period CTR when sharing a bucket with simulated exposure');

c=fresh();v=own(100,'short');v.shortStats.shownInFeed++;shortPlayback.id=v.id;shortPlayback.viewed=false;shortPlayback.elapsed=0;finishShort();check(v.shortStats.swipedAway===1&&v.shortStats.shownInFeed===v.shortStats.viewedExposures+v.shortStats.swipedAway,'Leaving Shorts immediately resolves the exposure as a swipe');finishShort();check(v.shortStats.swipedAway===1,'Repeated unload/route cleanup cannot credit a second swipe');
window.v3Results={passed:results.length,results};
`;
vm.runInContext(source+checks+'\n})();',context,{timeout:60000});fs.writeFileSync('work/v3-results.json',JSON.stringify(context.window.v3Results,null,2));console.log(JSON.stringify(context.window.v3Results));
