from pathlib import Path
p=Path('outputs/index.html');s=Path('work/index-v1-backup.html').read_text()
# Retain the original storage key so existing browsers keep their world.
s=s.replace('version:1,timeScale:120','version:2,timeScale:120')
s=s.replace("version:1,user:","version:2,user:")
s=s.replace('Кадр — видео и идеи','YouTrube — видео и идеи').replace('Кадра','YouTrube').replace('Кадр','YouTrube').replace('КАДР / КАНАЛ','YOUTRUBE / КАНАЛ')
s=s.replace('</span>кадр${studio?', '</span>YouTrube${studio?').replace('kadr-backup-','youtrube-backup-')
s=s.replace('Ваше пространство для историй','Видео, Shorts и ваши истории')
s=s.replace("'Внешние источники'];","'Внешние источники','Лента Shorts'];")
s=s.replace('Array(6).fill(0)','Array(SOURCE_NAMES.length).fill(0)')
s=s.replace("s.version!==CONFIG.version", "![1,2].includes(s.version)")
s=s.replace("return s}}catch(e)", "return migrateState(s)}}catch(e)")
s=s.replace("return freshState()}\nfunction saveState", "return migrateState(freshState())}\nfunction saveState")
s=s.replace("const safeImage=s=>/", "const safeImage=s=>String(s||'').startsWith('asset:')?(assetCache.get(s)||''):/")
s=s.replace("const k=v.id+':'+v.seed+':'+v.category", "const k=v.id+':'+v.seed+':'+v.category+':'+(v.type||'video')")
s=s.replace("if(v.visibility!=='public'||v.publishedAt>to)continue;const c=", "if(v.visibility!=='public'||v.publishedAt>to||v.archived)continue;if(v.type==='short'){simulateShortStep(v,Math.max(from,v.publishedAt),to);continue}const c=")
s=s.replace("const impressions=rate*hours", "const impressions=rate*(to-Math.max(from,v.publishedAt))/3600e3")
s=s.replace("if(!ms)return;let cursor=", "if(!ms)return;npcPublishBudget=12;let cursor=")
s=s.replace("state.simulation.now=to;simulateStep(cursor,to)", "state.simulation.now=to;publishNPCDue(to);simulateStep(cursor,to)")
s=s.replace("state.simulation.now=end;syncChannelTotals()", "state.simulation.now=end;pruneNPC();syncChannelTotals()")
s=s.replace("c.totalViews=vs.reduce((n,v)=>n+v.views,0);c.videoCount=vs.filter(v=>v.visibility==='public').length", "c.totalViews=(c.archivedViews||0)+vs.reduce((n,v)=>n+v.views,0);c.videoCount=(c.archivedCount||0)+vs.filter(v=>v.visibility==='public').length;c.shortCount=vs.filter(v=>v.type==='short'&&v.visibility==='public').length")
s=s.replace("h[k]+=d[k]", "h[k]=(h[k]||0)+d[k]").replace("if(k in h)h[k]=(h[k]||0)+d[k]", "h[k]=(h[k]||0)+d[k]")
s=s.replace("watchSeconds:0};v.history.push(h)", "watchSeconds:0,shownInFeed:0,viewedExposures:0,swipedAway:0,rewatches:0};v.history.push(h)")
s=s.replace("watchSeconds:0};Object.keys(old)", "watchSeconds:0,shownInFeed:0,viewedExposures:0,swipedAway:0,rewatches:0};Object.keys(old)")
s=s.replace("old[k]+=a[k]", "old[k]+=(a[k]||0)").replace("first[k]+=x[k]", "first[k]+=(x[k]||0)")
s=s.replace("v.id!==exclude&&v.visibility==='public'", "v.type!=='short'&&!v.archived&&v.id!==exclude&&v.visibility==='public'")
s=s.replace("function videoCard(v){const c=", "function videoCard(v){if(v.type==='short')return shortCard(v);const c=")
s=s.replace("${navItem('home','Главная','home',route==='home')}${navItem('subscriptions'", "${navItem('home','Главная','home',route==='home')}${navItem('shorts','Shorts','shorts',route.startsWith('shorts'))}${navItem('subscriptions'")
s=s.replace("[['home','Главная','home'],['subscriptions'", "[['home','Главная','home'],['shorts','Shorts','shorts'],['subscriptions'")
s=s.replace("route===r||r==='studio'&&studio", "route===r||r==='shorts'&&route.startsWith('shorts')||r==='studio'&&studio")
s=s.replace("function subscriptions(){const vs=state.videos.filter(v=>v.visibility", "function subscriptions(){const vs=state.videos.filter(v=>!v.archived&&v.type!=='short'&&v.visibility")
s=s.replace("${v.id}", "${v.id}")
# Video route helper keeps all existing viewers, lists and Studio actions intact.
s=s.replace('href="#/watch/${v.id}"','href="#/${videoRoute(v)}"')
s=s.replace('href="#/watch/${latest.id}"','href="#/${videoRoute(latest)}" data-format="${latest.type||\'video\'}"')
s=s.replace('href="#/watch/${top.id}"','href="#/${videoRoute(top)}" data-format="${top.type||\'video\'}"')
s=s.replace("const vs=v?[v]:mine()", "const vs=v?[v]:analyticsVideos()")
s=s.replace("vs=v?[v]:mine(),stats=aggregate(vs)", "vs=v?[v]:analyticsVideos(),stats=aggregate(vs)")
s=s.replace("[video?'Новые подписчики':'Подписчики'", "['Новые подписчики'")
s=s.replace("key==='ctr'?pct(stats[key])", "(key==='ctr'||key==='viewedRate')?pct(stats[key])")
s=s.replace("else if(path==='search')html=", "else if(path==='shorts'||path.startsWith('shorts/'))html=shortsPage(path.slice(7));else if(path==='search')html=")
s=s.replace("function renderContent(){const {path,query}=readRoute();", "function renderContent(){stopShorts();const {path,query}=readRoute();document.body.classList.toggle('shorts-view',path==='shorts'||path.startsWith('shorts/'));")
s=s.replace("updatePlayer();updateDebug()}", "updatePlayer();if(path==='shorts'||path.startsWith('shorts/'))mountShorts(path.slice(7));updateDebug()}")
s=s.replace("function routeChange(){closeDropdown();", "function routeChange(){stopShorts();closeDropdown();")
s=s.replace("if(path!==state.currentRoute)", "if(path!==state.currentRoute)")
s=s.replace("function contentPage(){const vs=mine();", "function contentPage(){const selectedType=readRoute().query.get('type')==='shorts'?'short':'video';const vs=mine().filter(v=>v.type===selectedType);")
s=s.replace("<h1>Контент канала</h1>${btn('create','Создать видео','create','primary')}</div>", "<h1>Контент канала</h1>${btn('create','Создать','create','primary')}</div><div class=\"tabs\">${link('studio/content','Видео','','tab'+(selectedType==='video'?' active':''))}${link('studio/content?type=shorts','Shorts','','tab'+(selectedType==='short'?' active':''))}</div>")
s=s.replace('<div class="table-video"><a', '<div class="table-video" data-format="${v.type}"><a')
s=s.replace("videoDraft={id:v?.id||null,thumbnail:", "videoDraft={type:v?.type||'video',originalThumbnail:null,id:v?.id||null,thumbnail:")
s=s.replace('<form id="video-form"><div class="form-grid">', '<form id="video-form"><div class="publish-types" role="group" aria-label="Тип публикации">${btn(\'publish-type\',\'Видео\',\'play\',v?.type!==\'short\'?\'primary\':\'\',\'data-type="video"\'+(v?\' disabled\':\'\'))}${btn(\'publish-type\',\'Shorts\',\'shorts\',v?.type===\'short\'?\'primary\':\'\',\'data-type="short"\'+(v?\' disabled\':\'\'))}<span class="tiny muted" id="format-hint">${v?.type===\'short\'?\'Вертикальная история · до 3 минут\':\'Горизонтальное видео\'}</span></div><div class="form-grid">')
s=s.replace('value="${v?formatDuration(v.duration):\'10:00\'}"','value="${v?formatDuration(v.duration):\'10:00\'}"')
s=s.replace("if(!title||duration<1||duration>12*3600)", "if(!title||duration<1||duration>(videoDraft.type==='short'?180:12*3600))")
s=s.replace("'Укажите название и длительность от 0:01 до 12:00:00.'", "videoDraft.type==='short'?'Укажите название и длительность Shorts от 0:01 до 3:00.':'Укажите название и длительность от 0:01 до 12:00:00.'")
s=s.replace("patch={title,description:", "patch={type:videoDraft.type,title,description:")
s=s.replace("v.params=params(v,channelBy('me'));state.videos.push(v)", "v.params=params(v,channelBy('me'));if(v.type==='short')initializeShort(v);state.videos.push(v)")
s=s.replace("syncChannelTotals();saveState(true);modal.dataset.busy", "const publishedType=patch.type;syncChannelTotals();saveState(true);modal.dataset.busy")
s=s.replace("if(state.currentRoute==='studio/content')render();else location.hash='/studio/content'", "location.hash='/studio/content'+(publishedType==='short'?'?type=shorts':'');render()")
s=s.replace("if(file.size>8e6)", "if(file.size>100e6)").replace('не должен превышать 8 МБ','не должен превышать 100 МБ')
s=s.replace("data?.version!==1", "![1,2].includes(data?.version)")
s=s.replace("v.traffic.length!==6", "![6,7].includes(v.traffic.length)")
s=s.replace("return data}\nasync function importData", "return migrateState(data)}\nasync function importData")
s=s.replace("const data=validateImport(JSON.parse(await file.text()));", "const parsed=JSON.parse(await file.text());const data=validateImport(parsed);pendingAssets=parsed.assets||{};delete data.assets;")
s=s.replace("async function optimizeImage", "async function optimizeImage")
s=s.replace("kind==='banner'?[1440,480]:[960,540]", "kind==='banner'?[1440,480]:kind==='short'?[540,960]:[960,540]")
s=s.replace("const image=await optimizeImage(input.files[0],kind);", "const source=input.files[0];const image=await optimizeImage(source,kind==='thumbnail'&&draft.type==='short'?'short':kind);if(kind==='thumbnail')draft.originalThumbnail=source;const stored=await ImageStore.put(image);")
s=s.replace("draft[kind]=image;", "draft[kind]=stored;")
s=s.replace("state=freshState();imageCache.clear();", "state=migrateState(freshState());ImageStore.clear();imageCache.clear();")
s=s.replace("const url=location.href.split('#')[0]+'#/watch/'+id", "const url=location.href.split('#')[0]+'#/'+videoRoute(v)")
s=s.replace("player.playing=false}else", "player.playing=false;shortPlayback.playing=false}else")
# Section appended inside the existing closure. The original init is upgraded below.
init=s.index('// APP INIT')
s=s[:init]+Path('work/extension.js').read_text()+'''\n// APP INIT (v1 state remains under the same browser storage key)
async function boot(){state=loadState();document.documentElement.dataset.theme=state.preferences.theme;$('#app').innerHTML='<main class="boot-screen"><span class="brandmark"></span><h1>YouTrube</h1><p class="muted">Открываем ваше пространство…</p></main>';await ImageStore.open();await migrateImages();seedShortEcosystem();const beforeViews=mine().reduce((n,v)=>n+v.views,0);settleTime();const offlineViews=mine().reduce((n,v)=>n+v.views,0)-beforeViews;syncChannelTotals();window.addEventListener('hashchange',routeChange);routeChange();saveState(true);if(offlineViews>=1)setTimeout(()=>toast('Пока вас не было: +'+exact(offlineViews)+' просмотров'),400);if(!ImageStore.available)toast('Хранилище изображений недоступно. Используется резервное сохранение в браузере.');}
boot().catch(error=>{console.error(error);$('#app').innerHTML='<main class="boot-screen"><h1>Не удалось открыть данные</h1><p>Исходные данные сохранены в браузере. Перезагрузите страницу или восстановите резервную копию.</p></main>'});
setInterval(()=>{if(!state||document.visibilityState==='hidden')return;settleTime();updateLive();saveState()},2000);
document.addEventListener('visibilitychange',()=>{if(!state)return;if(document.visibilityState==='hidden'){settleTime();saveState(true);player.playing=false;shortPlayback.playing=false}else{settleTime();updateLive();updatePlayer();saveState()}});
window.addEventListener('pagehide',()=>{if(state){settleTime();saveState(true)}});window.addEventListener('beforeunload',()=>{if(state){settleTime();saveState(true)}});
})();
</script>
</body>
</html>
'''
s=s.replace('</style>',Path('work/shorts.css').read_text()+'\n</style>')
s=s.replace("if(v.thumbnail)return safeImage(v.thumbnail);", "const resolved=safeImage(v.thumbnail);if(resolved)return resolved;")
s=s.replace("state.simulation.now=end;pruneNPC();", "state.simulation.now=end;fastForwardNPCSchedules(end);pruneNPC();")
s=s.replace("if(!['public','unlisted','private'].includes(v.visibility))", "if(!['public','unlisted','private'].includes(v.visibility))")
s=s.replace("v.tags.some(x=>typeof x!=='string')||", "v.tags.some(x=>typeof x!=='string')||(v.type&&!['video','short'].includes(v.type))||")
s=s.replace("const beforeViews=mine()", "await ImageStore.collect();const beforeViews=mine()")
s=s.replace("${c.banner?safeImage(c.banner):art(", "${safeImage(c.banner)||art(")
s=s.replace("c.banner?safeImage(c.banner):art(", "safeImage(c.banner)||art(")
s=s.replace("YOUTRUBE / КАНАЛ", "YouTrube / КАНАЛ")
s=s.replace('<span>Показы</span><strong data-impressions="${latest.id}">${exact(latest.impressions)}</strong>', '<span>${isShort(latest)?\'Показано в ленте\':\'Показы\'}</span><strong data-${isShort(latest)?\'shown\':\'impressions\'}="${latest.id}">${exact(isShort(latest)?latest.shortStats.shownInFeed:latest.impressions)}</strong>')
s=s.replace('<span>CTR</span><strong>${pct(latest.params.ctr)}</strong>', '<span>${isShort(latest)?\'Продолжили смотреть\':\'CTR\'}</span><strong>${pct(isShort(latest)?latest.shortParams.viewedRate:latest.params.ctr)}</strong>')
s=s.replace('${formatDuration(latest.duration*latest.params.retention)}', '${formatDuration(isShort(latest)?(latest.views?latest.watchSeconds/latest.views:0):latest.duration*latest.params.retention)}')
s=s.replace("set('[data-impressions]',", "set('[data-shown]',el=>exact(videoBy(el.dataset.shown)?.shortStats?.shownInFeed));set('[data-impressions]',")

p.write_text(s)
print('Updated existing index.html:',p.stat().st_size,'bytes')
